### ISSUE TITLE
Create Required annotation for Operation fields

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1003]
Currently distinguishing what fields on Operations are required is hard and would require reading the code. This issue is to create a Required annotation class that can be used to annotate the fields that are required. The default Operation.validate method can then be updated to check for these fields. The Operation example documentation can also be updated to list the fields with these annotations.

**Comment by p013570** [comment]
# Migration steps
If you have any custom operations then you will need to make some minor changes.

Add the Required annotation to any required Operation fields.

Update your tests for your custom operations as follows:

OperationTest is now an abstract class, so for any custom Operation tests classes you will need to change:

```java
public class CustomOperationTest implements OperationTest
```

```java
public class CustomOperationTest extends OperationTest
```

Implement the new test method, getOperationClass(). For example:
```java
@Override
public Class<? extends Operation> getOperationClass() {
    return CustomOperation.class;
}
```

If you have required fields then override the test method getRequiredFields() and return a Set containing the field names. For example:

```java
@Override
protected Set<String> getRequiredFields() {
    return Sets.newHashSet("requiredField1", "requiredField2");
}
```

**Comment by t616178** [comment]
Merged into develop.
