### ISSUE TITLE
fix jcs exception

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#1012]
When killing the road traffic example with ^C, JCS throws an exception.

**Comment by d47853** [comment]
Tomcat does not allow new classes to load in shutdown hooks which is causing the errors. I've replaced the shutdown hook a context listener implemented by the ApplicationConfig. 

However these will not be activated in the event of an interrupt signal (Ctrl + C). JCS adds a shutdown hook by itself so that if this were to occur the cache should be shut down normally. Unfortunately, in the case of tomcat, this causes the NoClassDefFoundError. Therefore as a work-around I have replaced the JcsCacheService with the HashMapCacheService.

**Comment by p013570** [comment]
Merged into develop.
