### ISSUE TITLE
Upgrade to swagger-ui v3.x

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#1040]
This will also involve updating the project to support the new OpenAPI 3.0 specification. A list of all the changes from v2.x to v3.x can be found here:

https://blog.readme.io/an-example-filled-guide-to-swagger-3-2/

**Comment by n3101** [comment]
This belongs with the other up-versioning for v2.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2608
