### ISSUE TITLE
Increase default value of accumulo.maxBufferSizeForBatchWriterInBytes

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1053]
The default value of `accumulo.maxBufferSizeForBatchWriterInBytes` is set to 1,000,000 in `AccumuloProperties`. This is less than 1MB. Much better ingest performance can be obtained if this is set to 100MB. Suggest increasing the default to 100,000,000.

**Comment by t616178** [comment]
Merged into develop
