### ISSUE TITLE
Handlers in spark-accumulo-library don't set column families

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1055]
Handlers for operations that return Spark RDDs or Dataframes on the `AccumuloStore` don't set the column families to read (e.g. in `GetJavaRDDOfElementsHandler`). So they are not taking advantage of the locality groups, and are reading unnecessary data.

This can be solved by using `InputConfigurator.fetchColumns(...)`.

This doesn't affect the results that are returned, so it hasn't been marked as a bug, but the intention was that all operations that can take advantage of the locality groups do so, so arguably it is a bug.

**Comment by p013570** [comment]
The columns are set for these operations using the InputConfigurator.fetchColumns method in the AccumuloStore.updateConfiguration method.

@gaffer01 - can this issue be closed?

**Comment by gaffer01** [comment]
You're right, it's done in the `addIterators` method which then calls `updateConfiguration`. Closing this now.
