### ISSUE TITLE
Aggregation on multiple properties and schema changes

### ISSUE THREAD

**Issue by ddseapy** [gchq/Gaffer#1058]
Got a couple issues that I've been spending some time with workarounds and want to make sure I'm not missing anything.  Am working with accumulo store, in case that is relevant.  If there is documentation somewhere that I'm missing that addresses these feel free to just point me to it, as I could easily have missed it.  Thanks!

1. I find myself sometimes wanting to aggregate a property based on other properties (not just the one I'm aggregating on), specifically based on the timestamp (ie. often something simple like grabbing the latest).  From a looking at the code I'm not sure a reason it couldn't be supported (at least in the accumulo case) but it didn't seem like it is.  Writing a schema i've found myself just wrapping the timestamp in the property so it's not that big of a deal, but adds some duplication and can prevent me from using something simple like a primitive type.

2.   For my use-case I need to be flexible in allowing the creation of new types of elements.  Is there any documentation on migrating to a schema with an added element group?  Will simply providing a new schema at runtime with the new element group be an issue, or does it require an export/import to a new accumulo data store?  I can add the new type into a groupBy field instead of making it a element group, but seems a bit wrong to do so.

These aren't always issues, but on a couple element groups they are.

**Comment by james010101101** [comment]
Hi, 
For 1) 
For the general case of aggregation of a property based on other properties that'll require a bit of thought on our end, your right it isn't currently supported.

Can you elaborate on your use case for this to help guide our thinking?

Just a thought based on what you've said so far, 
If you've got a bunch of elements and just want to aggregate a property based on the "latest" value
If you don't change your groupBy at query time, then you can use the first bifunction https://github.com/gchq/koryphe/blob/master/src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/First.java
 As in Accumulo at least, the elements will be sorted latest->oldest for each element id & groupBy (If you've put the timestamp in the Accumulo timestamp column) 

For 2) 
The good news is You can be flexible in allowing new element groups to be created and you don't need to do any import/export to/from tables, bad news you still do need to do a little work, 
Once you have your updated schema, all you need to do is update the Accumulo table's iterators with the new schema's.
And We have a utility for this 
https://github.com/gchq/Gaffer/blob/master/store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/utils/AddUpdateTableIterator.java

You need to provide a comma separated list of schema file paths,  a store Properties file path and the argument: update.

You can do this programatically through the class by calling main method with the above arguments.
Admittedly It's not the most publicly facing API at the moment, we've had some other thoughts around storing schema's in some kind of central location - which could also then make it much simpler to update them on the stores. But we've not really looked at this too much.

**Comment by ddseapy** [comment]
for #1 - Unfortunately I can't go into the specific use-case.  In general the issue arises when there are a subset of the properties that are metadata about the element which can be used to determine how many of the other properties are to be aggregated. One example is timestamp but there can be others.  The non-timestamp properties will be in the schema's groupBy so that the data is not lost and can be queried on if necessary.  However there are many times we don't want to query on the metadata, but rather just want it used to provide the aggregated results of the non-metadata properties.  Hope that helps.  This can all be solved by bundling the metadata properties into each non-metdata property whos aggregation it affects, however it would be nice if that wasn't the necessary.  Thanks for pointing me to the First operator, as it would make sense to use that in situations where we will not change the groupBy and just need the timestamp for aggregation.

for #2 - In general, what are the limitations on what can change in the schema when using the AddUpdateTableIterator class?  The comments say you can change the validationFunction and the aggregateFunction, and you mentioned you can add an element group.  That makes sense that it would be just an iterator change.  Specifically, would there be any issues in me adding a new property (whether groupBy or not) to an existing element group?  I understand that something like changing the groupBy list on an existing element group would likely require me writing a map-reduce job or an export/import of some kind.

Thanks!

**Comment by ddseapy** [comment]
Also, apologies for creating 2 unrelated issues/questions in one issue.

**Comment by ddseapy** [comment]
Wrt First biFunction, since visibilities are treated similar to a removed groupBy in accumulo at query time, the function could produce incorrect results even if I'm not explicitly overriding the groupBy in my query.

**Comment by p013570** [comment]
1 - When we write the Koryphe library to handle the aggregation/filtering we thought about allowing multiple properties to be passed to a single aggregator function. It adds additional complexity and we didn't have a use case for it so we chose just to implement the basics initially. With validation and filtering we allow multiple properties to be passed to a Predicate by using KoryphePredicate2, KoryphePredicate3, etc. So, we could follow this same pattern create similar classes for aggregating multiple properties. I'll open up a separate issue and put some more information in that issue to describe how it would work.

2 - Ah sorry, yes we are missing a 'migration' section in the Accumulo Store README. I'll create a separate issue to add some documentation for that. In the meantime... here are the limitations:

You can do the following:
- add new groups
- add new non-groupBy properties (including visibility and timestamp), but they must go after the other properties
- rename properties
- change aggregators
- change validators
- change descriptions

You cannot do the following:
- rename groups
- remove any properties (groupBy, non-groupBy, visibility or timestamp)
- add new groupBy properties
- reorder any of the properties. In the Accumulo store we don't use any property names, we just rely on the order the properties are defined in the schema.
- change the way properties or vertices are serialised - i.e don't change the serialisers.
- change which properties are groupBy

Please note, that the validation functions in the schema can be a bit dangerous. If an element is found to be invalid then the element will be permanently deleted from the table. So, be very careful when making changes to your schema that you don't accidentally make all your existing elements invalid as you will quickly realise all your data has been deleted. For example, if you add a new property 'prop1' and set the validateFunctions to be a single Exists predicate. Then when that Exists predicate is applied to all of your existing elements, those old elements will fail validation and be removed.

If you have existing data, then before doing any form of upgrade or change to your table I would strongly recommend using the accumulo shell to clone the table so you have a backup so you can easily restore to that version if things go wrong. Even if you have an error like the one above where all your data is deleted in your table you will still be able to quickly revert back to your backup. Cloning a table in Accumulo is very simple and fast (it doesn't actually copy the data). If you have a table called 'table1', you can do something like the following in the Accumulo shell
```bash
> offline -t table1
> clone table1 table1-backup
> offline -t table1-backup

#Do you upgrades
# - deploy new gaffer jars to accumulo
# - run the AddUpdateTableIterator class to update table1

> online -t table1

# Check table1 is still healthy, run a query and check the iterators are successfully aggregating and filtering elements correctly.

> droptable -t table1-backup
```

**Comment by ddseapy** [comment]
I'll close this issue since others have been created.

1) If no one else needs to aggregate on multiple properties and since it's also probably never a blocker, I don't think it's a high priority.  Especially if it complicates the schema config.  If I have time to write it and think of a way to do it cleanly I'll throw up a pr to have you all look at it.

2) Adding the info you both just provided on accumulo table migrations is very helpful, thanks.  I'm sure others will find it very useful in the readme.
