### ISSUE TITLE
Allow multiple properties to be aggregated using a single aggregate function

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1060]
We need to update the SchemaElementDefinition class to allow a ElementAggregator to be provided. Then getFullAggregator, getIngestAggregator and getQueryAggregator methods will need to be updated to use combine the Type aggregators and the schema element definition aggregator.

We need to restrict which properties can be aggregated at the same time. For example, you should not be allow to aggregate a groupBy property and a non-groupBy property in the same Binary Operator. When ingest aggregation is applied, only the non-groupBy properties are aggregated so we need Binary Operators that only apply to non-groupBy properties. The different types of properties are: groupBy, non-groupBy, visibility, timestamp. 

As schemas can be split up into different files we probably should have another think about the structure of these files and in which file the new ElementAggregator functions go. The aggregation logic is Store specific so it shouldn't be mixed up with the other data schema parts. 

We could change the schema files (dataSchema, dataTypes, storeTypes) to be something like:

- schema
- types
- serialisation   (store specific)
- validation    (overrides type validation and allows you to validate multiple properties at once)
- aggregation   (overrides type aggregation and allows you to aggregate multiple properties at once)

**Comment by p013570** [comment]
Requirement for this came from #1058.

**Comment by gaffer01** [comment]
> We need to update the SchemaElementDefinition class to allow a ElementAggregator to be provided. Then getFullAggregator, getIngestAggregator and getQueryAggregator methods will need to be updated to use combine the Type aggregators and the schema element definition aggregator.

Not sure I understand what this means. What does an ElementAggregator do? What if the type aggregators and element aggregators disagree on what to do?

If multiple properties need to be aggregated by one function then they could be put in one property. If you were maintaining a mean and need to update the sum and the number of items then those 2 fields could be made into one property which could then easily be aggregated with a normal aggregation function. Is there a good use-case which can't be satisfied by this approach?

Not sure the extra complexity that this will introduce (which feels like a lot) is justified. Users already find writing a schema the hardest thing to do. Too much generality will result in a framework that is too hard to use.

**Comment by ddseapy** [comment]
I've been doing as you said, bundling them all in a property together.  Essentially I have a couple properties that affect how the rest of the properties get aggregated.  Instead of duplicating each property in all of the rest and writing a custom type for all them it's been easier making them all one property.

An example might be timestamp and prop1 affect the others (int, double, date...), so the options are:

* Write serializers & aggregators for each bundled property: (timestamp, prop1, int), (timestamp, prop1, double), (timestamp, prop1, date)....

* Write one serializer & aggregator for (timestamp, prop1, int, double, date...) and put them in one property


I've gone with the later option for now.  Don't know that it's a problem, but doesn't seem ideal.  It would be nice to be able to specify a function to aggregate two elements, which would allow using the properties without duplicating the data throughout the properties or collapsing them all into one giant property.  Again, might be more trouble than it's worth to implement element-level aggregation, don't know.

**Comment by gaffer01** [comment]
OK, thanks that helps.

We need to decide whether our fundamental unit of aggregation is a single property or whether it can be more than 1. I tend to think that for the type of custom aggregation you're specifying it maybe should be one property as they are somehow logically related. But if they're the only properties you have then they end up nested (and the main properties map only has 1 key) which is a bit odd.

We'll have to see how much complexity it adds.

**Comment by p013570** [comment]
OK, I've pretty much finished implementing the change. The change has added an extra section to the Schema but this is optional so hopefully it won't complicate things for novice users of Gaffer. This was a bit of complexity around the change due to not be able to aggregation multiple properties together if they are stored in different places. For example - we will not allow groupBy and non-groupBy properties to be aggregated using the same BinaryOperator.

I've done a bit of updating of the Schemas to encourage users to just have 2 schema files - Elements Schema and Types Schema. Then if they need advanced aggregation or validation they can do that in separate files, Aggregation Schema and Validation Schema. I've also updated the documentation for the wiki. Below is the output that will be added to the wiki if this branch is accepted and merged in.



### Schemas

The code for this example is [Schemas](https://github.com/gchq/Gaffer/blob/master/doc/src/main/java/uk/gov/gchq/gaffer/doc/dev/walkthrough/Schemas.java).

This example delves into more detail on Schemas. As we have seen previously there are 2 main components to schemas: the Elements schema and the Types schema.

It is worth remembering that your schema can be broken up further if required. 
For example if you have a Graph that is made up of 5 different data sources, you may find it easier to develop and maintain by splitting your schema into multiple parts, for example 5 Element Schemas and 1 Types schema.
When you construct your Gaffer graph you must provide all the Schema parts. These will then be merged together to form a 'master' schema for the Graph.

We will talk through some more of the features you can add to your Schemas to make them more readable and to model your data more accurately.


#### Elements schema
The elements schema is designed to be a high level document describing what information your Graph contains - like the different types of edges and entities and the list of properties associated with each.
Essentially this part of the schema should just be a list of all the entities and edges in the graph. 
Edges describe the relationship between a source vertex and a destination vertex. 
Entities describe a vertex. We use the term "element" to mean either and edge or and entity.

When defining an element we must provide a "group". This is a unique string that defines the type of an element.
Groups must be completely unique and cannot be shared between edges and entities.

Edges must have the following:
- source - this is the type of object that will be used as the source vertex in your graph. The value here is a string similar to a property type (it could be the same type as a property type).
- destination - similar to source, it can either be the same or a different type.
- directed - we need to tell Gaffer if the edge is directed or undirected. Currently, the easiest way to do this is to create a type called "true", "false" and define that type in the Type schema as being a boolean with a filter predicate to check the boolean is true or false

Entities must have a vertex field - this is similar to the source and destination fields on an edge.


Edges and Entities can optionally have the following fields:
- description - this is a simple string that should provide some context and explain what the element is.
- parents - this should be an array of parent group names. Note - the parent groups must relate to the same element type as the child, for example an edge cannot have an entity as a parent. Elements can inherit any information from multiple parent elements - fields will be merged/overridden so the order that you defined your parents is important. Any fields that are defined in the child element will also merge or override information taken from the parents.
- properties - Properties are be defined by a map of key-value pairs of property names to property types. The property type should be described in the Types schema.
- groupBy - by default Gaffer will use the element group and it's vertices to group similar elements together in order to aggregate and summarise the elements. This groupBy field allows you to specify extra properties that should be used in addition to the element group and vertices to control when similar elements should be grouped together and summarised.
- visibilityProperty - if you are using visibility properties in your graph, then ensure the sensitive elements have a visibility property and then set this visibilityProperty field to that property name so Gaffer knows to restrict access to this element.
- timestampProperty - if you are using timestamp property in your graph, then set this timestampProperty field to that property name so Gaffer knows to treat that property specially.
- aggregate - this is true by default. If you would like to disable aggregation for this element group set this to false.

These 2 optional fields are for advanced users. They can go in the Elements Schema however, we have split them out into separate Schema files Validation and Aggregation so the logic doesn't complicate the Elements schema.
- validateFunctions - an array of selections and predicates to be applied to an element. This allows you to validate based on multiple properties at once - like check a timestamp property together with a time to live property to check if the element should be aged off. Individual property validation is best done as a validateFunction in the property type definition in Types schema.
- aggregateFunctions - an array of selections and binary operators to be applied to an element. This allows you to aggregate based on multiple properties at once. It is important to note that different types of properties (groupBy, non-groupBy, visibility, timestamp) cannot be aggregated in the same aggregate function. Individual property aggregation is best done as a aggregateFunction in the property type definition in the Types schema.

Here is an example of an Elements schema


```json
{
  "edges": {
    "RoadUse": {
      "description": "A directed edge representing vehicles moving from junction A to junction B.",
      "source": "junction",
      "destination": "junction",
      "directed": "true",
      "properties": {
        "startDate": "date.earliest",
        "endDate": "date.latest",
        "count": "count.long"
      },
      "groupBy": [
        "startDate",
        "endDate"
      ]
    },
    "RoadHasJunction": {
      "description": "A directed edge from each road to all the junctions on that road.",
      "source": "road",
      "destination": "junction",
      "directed": "true"
    }
  },
  "entities": {
    "Cardinality": {
      "description": "An entity that is added to every vertex representing the connectivity of the vertex.",
      "vertex": "anyVertex",
      "properties": {
        "edgeGroup": "set",
        "hllp": "hllp",
        "count": "count.long"
      },
      "groupBy": [
        "edgeGroup"
      ]
    }
  }
}
```


Here is the Validation Schema. It contains advanced validation, that is applied to multiple properties within an Element group.


```json
{
  "edges": {
    "RoadUse": {
      "validateFunctions": [
        {
          "selection": [
            "startDate",
            "endDate"
          ],
          "predicate": {
            "class": "uk.gov.gchq.koryphe.impl.predicate.IsXLessThanY"
          }
        }
      ]
    }
  }
}
```


Here is the Aggregation Schema. It contains advanced aggregation, that is applied to multiple properties within an Element group.
The multi property aggregate function defined here overrides the relevant single property aggregate functions defined in the Types schema.


```json
{
  "edges": {
    "RoadUse": {
      "aggregateFunctions": [
        {
          "selection": [
            "startDate",
            "endDate"
          ],
          "binaryOperator": {
            "class": "uk.gov.gchq.gaffer.doc.dev.aggregator.ExampleTuple2BinaryOperator"
          }
        }
      ]
    }
  }
}
```



#### Types
All types used in the elements schema must be defined in the types parts of the schema. These Types explain to Gaffer what types of properties to expect and how to deal with them.

For each type you must provide the following information:

- class - this is the Java class of the type

You can optionally provide the following:

- description - a string containing a description of the type
- validateFunctions - an array of predicates that will be executed against every type value to validate it. To improve performance put quicker/low cost functions first in the array.
- aggregateFunction - the aggregate binary operator to use to aggregate/summarise/merge property values of the same type together.
- serialiser - an object that contains a field class which represents the java class of the serialiser to use, and potentially arguments depending on the serialiser. If this is not provided Gaffer will attempt to select an appropriate one for you - this is only available for simple Java types.

Here are some example Types

```json
{
  "types": {
    "junction": {
      "description": "A road junction represented by a String.",
      "class": "java.lang.String"
    },
    "road": {
      "description": "A road represented by a String.",
      "class": "java.lang.String"
    },
    "anyVertex": {
      "description": "An String vertex - used for cardinalities",
      "class": "java.lang.String"
    },
    "count.long": {
      "description": "A long count that must be greater than or equal to 0.",
      "class": "java.lang.Long",
      "validateFunctions": [
        {
          "class": "uk.gov.gchq.koryphe.impl.predicate.IsMoreThan",
          "orEqualTo": true,
          "value": {
            "java.lang.Long": 0
          }
        }
      ],
      "aggregateFunction": {
        "class": "uk.gov.gchq.koryphe.impl.binaryoperator.Sum"
      }
    },
    "true": {
      "description": "A simple boolean that must always be true.",
      "class": "java.lang.Boolean",
      "validateFunctions": [
        {
          "class": "uk.gov.gchq.koryphe.impl.predicate.IsTrue"
        }
      ]
    },
    "date.earliest": {
      "description": "A Date that when aggregated together will be the earliest date.",
      "class": "java.util.Date",
      "validateFunctions": [
        {
          "class": "uk.gov.gchq.koryphe.impl.predicate.Exists"
        }
      ],
      "aggregateFunction": {
        "class": "uk.gov.gchq.koryphe.impl.binaryoperator.Min"
      }
    },
    "date.latest": {
      "description": "A Date that when aggregated together will be the latest date.",
      "class": "java.util.Date",
      "validateFunctions": [
        {
          "class": "uk.gov.gchq.koryphe.impl.predicate.Exists"
        }
      ],
      "aggregateFunction": {
        "class": "uk.gov.gchq.koryphe.impl.binaryoperator.Max"
      }
    },
    "set": {
      "class": "java.util.TreeSet",
      "aggregateFunction": {
        "class": "uk.gov.gchq.koryphe.impl.binaryoperator.CollectionConcat"
      }
    },
    "hllp": {
      "class": "com.clearspring.analytics.stream.cardinality.HyperLogLogPlus",
      "aggregateFunction": {
        "class": "uk.gov.gchq.gaffer.sketches.binaryoperator.HyperLogLogPlusAggregator"
      },
      "serialiser": {
        "class": "uk.gov.gchq.gaffer.sketches.serialisation.HyperLogLogPlusSerialiser"
      }
    }
  }
}
```



#### Full Schema
Once the schema has been loaded into a graph the parent elements are merged into the children for performance reasons. This is what the full schema created from the above example schema parts looks like:

```json
{
  "edges" : {
    "RoadUse" : {
      "properties" : {
        "startDate" : "date.earliest",
        "endDate" : "date.latest",
        "count" : "count.long"
      },
      "groupBy" : [ ],
      "directed" : "true",
      "source" : "junction",
      "destination" : "junction",
      "aggregateFunctions" : [ {
        "binaryOperator" : {
          "class" : "uk.gov.gchq.gaffer.doc.dev.aggregator.ExampleTuple2BinaryOperator"
        },
        "selection" : [ "startDate", "endDate" ]
      } ],
      "validateFunctions" : [ {
        "predicate" : {
          "class" : "uk.gov.gchq.koryphe.impl.predicate.IsXLessThanY"
        },
        "selection" : [ "startDate", "endDate" ]
      } ]
    },
    "RoadHasJunction" : {
      "properties" : { },
      "groupBy" : [ ],
      "description" : "A directed edge from each road to all the junctions on that road.",
      "directed" : "true",
      "source" : "road",
      "destination" : "junction"
    }
  },
  "entities" : {
    "Cardinality" : {
      "properties" : {
        "edgeGroup" : "set",
        "hllp" : "hllp",
        "count" : "count.long"
      },
      "groupBy" : [ "edgeGroup" ],
      "description" : "An entity that is added to every vertex representing the connectivity of the vertex.",
      "vertex" : "anyVertex"
    }
  },
  "types" : {
    "junction" : {
      "description" : "A road junction represented by a String.",
      "class" : "java.lang.String"
    },
    "road" : {
      "description" : "A road represented by a String.",
      "class" : "java.lang.String"
    },
    "anyVertex" : {
      "description" : "An String vertex - used for cardinalities",
      "class" : "java.lang.String"
    },
    "count.long" : {
      "validateFunctions" : [ {
        "class" : "uk.gov.gchq.koryphe.impl.predicate.IsMoreThan",
        "orEqualTo" : true,
        "value" : {
          "java.lang.Long" : 0
        }
      } ],
      "aggregateFunction" : {
        "class" : "uk.gov.gchq.koryphe.impl.binaryoperator.Sum"
      },
      "description" : "A long count that must be greater than or equal to 0.",
      "class" : "java.lang.Long"
    },
    "true" : {
      "validateFunctions" : [ {
        "class" : "uk.gov.gchq.koryphe.impl.predicate.IsTrue"
      } ],
      "description" : "A simple boolean that must always be true.",
      "class" : "java.lang.Boolean"
    },
    "date.earliest" : {
      "validateFunctions" : [ {
        "class" : "uk.gov.gchq.koryphe.impl.predicate.Exists"
      } ],
      "aggregateFunction" : {
        "class" : "uk.gov.gchq.koryphe.impl.binaryoperator.Min"
      },
      "description" : "A Date that when aggregated together will be the earliest date.",
      "class" : "java.util.Date"
    },
    "date.latest" : {
      "validateFunctions" : [ {
        "class" : "uk.gov.gchq.koryphe.impl.predicate.Exists"
      } ],
      "aggregateFunction" : {
        "class" : "uk.gov.gchq.koryphe.impl.binaryoperator.Max"
      },
      "description" : "A Date that when aggregated together will be the latest date.",
      "class" : "java.util.Date"
    },
    "set" : {
      "aggregateFunction" : {
        "class" : "uk.gov.gchq.koryphe.impl.binaryoperator.CollectionConcat"
      },
      "class" : "java.util.TreeSet"
    },
    "hllp" : {
      "serialiser" : {
        "class" : "uk.gov.gchq.gaffer.sketches.serialisation.HyperLogLogPlusSerialiser"
      },
      "aggregateFunction" : {
        "class" : "uk.gov.gchq.gaffer.sketches.binaryoperator.HyperLogLogPlusAggregator"
      },
      "class" : "com.clearspring.analytics.stream.cardinality.HyperLogLogPlus"
    }
  }
}

```

**Comment by ddseapy** [comment]
Looks good to me.  The ExampleTuple2BinaryOperator class and aggregateFunctions config make it seem very straightforward and flexible.  Satisfies my use-case.

**Comment by p013570** [comment]
# Migration Steps
There isn't actually any migration required for this issue, but we have changed our recommendations on how to split up your schema files and you may find it helpful to follow the new guidelines.

dataSchema.json -> elements.json
dataTypes.json + storeTypes.json -> types.json

If you have a storeSchema file containing a vertex serialiser we recommend renaming this file to serialisation.json.

If you have any advanced validation (multiple property validation) in your dataSchema then we recommend you pull this out into a separate file - validation.json.

**Comment by p013570** [comment]
Merged into develop.
