### ISSUE TITLE
Create GraphHook to add additional operations to an operation chain

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1063]
The AddOperationsToChain GraphHook should be configured via json. It should allow extra operations to be inserted into the chain at various points:
- start
- end
- before all operations of a given type
- after all operations of a given type

The json could look something like this:

```json
{
  "start": [
    {
      "class": "uk.gov.gchq.gaffer.operation.Operation1"
    },
    {
      "class": "uk.gov.gchq.gaffer.operation.Operation2"
    }
  ],
  "end": [
    {
      "class": "uk.gov.gchq.gaffer.operation.Operation3"
    }
  ],
  "before": {
    "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements": [
      {
        "class": "uk.gov.gchq.gaffer.operation.Operation4"
      }
    ],
    "uk.gov.gchq.gaffer.operation.impl.get.GetElements": [
      {
        "class": "uk.gov.gchq.gaffer.operation.Operation5"
      }
    ]
  },
  "after": {
    "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements": [
      {
        "class": "uk.gov.gchq.gaffer.operation.Operation6"
      },
      {
        "class": "uk.gov.gchq.gaffer.operation.Operation7"
      }
    ],
    "uk.gov.gchq.gaffer.operation.impl.get.GetElements": [
      {
        "class": "uk.gov.gchq.gaffer.operation.Operation8"
      }
    ]
  }
}
```

This could be used to limit the number of results returned from the Graph via GetElements or GetAllElements, by inserting a Limit operation at required points.

**Comment by d21211122** [comment]
Looks good - could we specify these so they can be tailored for different auth tokens, though?

**Comment by p013570** [comment]
We will need to be careful how this is implemented with NamedOperations to ensure the OperationChain within a NamedOperation is also updated.

**Comment by m55624** [comment]
we will need to have multiple sections in the json:
"auth1": {
"start": 
"end": 
...
},
"auth2": {
"start": 
"end": 
...
},

The map would need to be ordered so it would need to be a LinkedHashMap and then you would have to start at the top and find the first auth that a user has and use the start, end operations from that section.

**Comment by p013570** [comment]
Merged into develop.
