### ISSUE TITLE
If validation fails, AddElements should return a reason why

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1090]
When adding elements, if validation fails then a useful error message containing the reason why it failed should be return. Currently it is can be very difficult to work out which property is invalid.

Example: when calling AddElements with an incorrect property type valve (String instead of int). Will fail operation, and describe the element is not valid, but does not provide the details regarding why and what is invalid with the given element. finding the faulty property requires debugging through the code, instead of looking at debug logs.

**Comment by GCHQDeveloper404** [comment]
```
@Test
    public void shouldIdentifyPropertyIsOfWrongType() throws Exception {
        federatedStore.initialise("testFederatedStore", null, STORE_PROPERTIES);

        AddElements op = new AddElements.Builder()
                .input(new Edge.Builder()
                               .group("BasicEdge")
                               .source("testSource")
                               .dest("testDest")
                               .property("property1", "testProp")//<- wrong type
                               .build())
                .build();

        federatedStore.execute(op, new User("testUser"));

        assertEquals(1, getElements().size());

    }
```

**Comment by GCHQDeveloper404** [comment]
I think this requires a change in Koryphe
class: IsA 
line: 40.

❓ @p013570 
I need it to create logging or something to be able to provide details as to what failed, maybe?
or cancel and kill issue gh-1090?

returning with a boolean from a complex multi-check, its not possible to identify that "property1" is the wrong type.

**Comment by p013570** [comment]
Merged into develop.
