### ISSUE TITLE
Implement Age-off for the ParquetStore

### ISSUE THREAD

**Issue by ac74475** [gchq/Gaffer#1100]
Create an operation which loads in the current snapshot of data and filters it based on the AgeOff function. It is probably best to do this on a per group directory basis.  Then you would delete previous snapshots.
This will need some thinking around how to manage users reading the data at the time of the AgeOff operation running.

**Comment by gaffer01** [comment]
Can someone clarify how this relates to #1303 ?

**Comment by p013570** [comment]
Currently the Parquet Store has special implementations for primitive predicates for some of Gaffer/Koryphe's core predicates like IsMoreThan. See ParquetFilterUtils.addPrimitiveFilter. I believe this means the IsMoreThan predicate can be applied more efficiently. AgeOff is just another predicate that is quite simple and #1303 is to add specific logic in ParquetFilterUtils to deal with the AgeOff predicate efficiently in a similar way to IsMoreThan.

**Comment by gaffer01** [comment]
Thanks, that makes sense.

**Comment by p013570** [comment]
Merged into develop.
