### ISSUE TITLE
Improve how the Parquet Index is generated

### ISSUE THREAD

**Issue by ac74475** [gchq/Gaffer#1103]
Currently the index is generated by taking the min and max statistics for each column related to the Gaffer identifiers. This causes a problem when the identifier is split into more than 1 column as the second column's last value may not be the max value. Really this needs to get the first and last row in each file and record the value for each column related to the Gaffer identifier.
This would then allow for the accurate targeting of filters to files when the identifier is split over more than one column.

**Comment by p013570** [comment]
Merged into develop.
