### ISSUE TITLE
Allow the indexing of selected properties in the ParquetStore

### ISSUE THREAD

**Issue by ac74475** [gchq/Gaffer#1104]
It should be possible to index Gaffer properties as well as the identifiers.
The naive way would be to do the same as we do for the indexing the Destination. It may be possible to improve the indexing to require less storage when indexing columns by having a master copy of the data sorted by a record ID and for each index property or identifier store that value along with the recordID. This will slow down the query's slightly but it would drastically reduce storage if indexing many columns.

**Comment by n3101** [comment]
We are not supporting parquet in v2.0, so this will not be done.
