### ISSUE TITLE
Validate the names of Groups and properties

### ISSUE THREAD

**Issue by ac74475** [gchq/Gaffer#1110]
If a group contains '=' then it will break the parquet store.
If a property contains '=', '.' or '_' then it will break the parquet store.
Currently the property names are checked in the SchemaUtils class for the Parquet store however both of these should be enforced for all the stores to allow for easy migration between stores.

**Comment by p013570** [comment]
This could causes serious problems for anyone who has an '=' in one of they groups. There is no easy way in Gaffer to migrate Gaffer group names in an existing Accumulo or HBase table. Therefore this would mean users could not update to this version of Gaffer.

Property names can easily be changed in Gaffer on Accumulo/HBase, users would just need to rename the property in their schema then run the table update utility.

Could the parquet store escape these characters? Then we could just log a warning for users?

**Comment by p013570** [comment]
OK, to standardise this we are going to require all group names and property names to be simply alpha numeric characters.

**Important** if you have a group name that isn't currently alpha numeric this will break your existing data in Accumulo and HBase. If this is the case for you, please get in touch and we can either delay making this change or provide you with advice on migrating your data.

**Comment by m55624** [comment]
# Migration Steps

All Element groups must now match a specific regex.  Groups can only contain alpha numeric characters and pipes (|).

The same applies for all Element properties.  The regex that must be matched is the same, alpha numeric characters and pipes.

**Important** if you have a group name that isn't currently alpha numeric (including pipes) this will break your existing data in Accumulo and HBase. If this is the case for you, please get in touch and we can provide you with advice on migrating your data.

**Comment by p013570** [comment]
Merged into develop.
