### ISSUE TITLE
Java 9 migration

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#1119]
There are a number of performance improvements that can be realised by enabling projects to be run in a Java 9 environment, even without making use of any additional language features:

https://www.sitepoint.com/inside-java-9-part-ii/

Java 9 is due to land in September, and some sources are advocating migrating codebases to take advantage of some of the new platform improvements.

Migration guide available here:

https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-2C896CA8-927C-4381-A737-B1D81D964B7B

It'd obviously difficult to quantify any performance improvements without carrying out the migration, but this might be interesting in the future.

PS. This really needs a "p:very low" label!

**Comment by n3101** [comment]
@t616178 Now looking at upgrading to Java 11.

**Comment by t92549** [comment]
Gaffer now has a java11 profile to run with Java 11
