### ISSUE TITLE
Error in AccumuloStore wiki page

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1122]
There are 2 errors:

- The table that shows the key, value pair that is created for an `Entity` in the classic key package is wrong - there isn't a `01` at the end of the row-key and it should say "timestamp" under the timestamp column and "all other properties" should be moved under "value".
- The hyperlinks in the line "See the Key-packages part of the Implementation details section of this guide for more..." are broken.

**Comment by p013570** [comment]
Merged into develop-1.0.0
