### ISSUE TITLE
Move clearspring serialisers, aggregators to their own subpackage

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1123]
The serialisers and aggregators for classes from the data sketches library are in a `datasketches` subpackage. We should create a `clearspring` subpackage for serialisers and aggregators for sketches from the clearspring library and move the existing HyperLogLog serialiser and aggregator into there.

**Comment by m607123** [comment]
# Migration

HyperLogLogPlus aggregator and serialiser are now in the subpackage:
uk.gov.gchq.gaffer.sketches.clearspring.cardinality

Any references should in future be updated accordingly.

**Comment by t616178** [comment]
Merged into develop-1.0.0.
