### ISSUE TITLE
Inconsistent behaviour between the 2 Accumulo key-packages

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1124]
See code below - there are differences between how the 2 key packages in the `AccumuloStore` work for `GetElementsInRanges` queries. Maybe it's intentional that they can do different things - if so this should be documented. It's also not really clear what the `IncludeIncomingOutgoingType` option means when using `EdgeSeed`s - all the examples in the wiki that use this option use `EntitySeed`s.

Marked as a bug as I don't think it was intentional that there was any difference in the results of queries from the two key packages.

    Schema schema = new Schema.Builder()
                .edge("EDGE", new SchemaEdgeDefinition.Builder()
                        .source("string")
                        .destination("string")
                        .build())
                .type("string", String.class)
                .build();

        AccumuloProperties propsByteEntity = new AccumuloProperties();
        propsByteEntity.setStoreClass(MockAccumuloStore.class);
        propsByteEntity.setKeyPackageClass(ByteEntityKeyPackage.class.getName());

        AccumuloProperties propsClassic = new AccumuloProperties();
        propsClassic.setStoreClass(MockAccumuloStore.class);
        propsClassic.setKeyPackageClass(ClassicKeyPackage.class.getName());

        Graph graphBE = new Graph.Builder()
                .graphId("1")
                .addSchema(schema)
                .storeProperties(propsByteEntity)
                .build();
        Graph graphClassic = new Graph.Builder()
                .graphId("2")
                .addSchema(schema)
                .storeProperties(propsClassic)
                .build();

        List<Element> elements = new ArrayList<>();
        Element e1 = new Edge.Builder()
                .group("EDGE")
                .source("A")
                .dest("B")
                .directed(true)
                .build();
        Element e2 = new Edge.Builder()
                .group("EDGE")
                .source("A")
                .dest("C")
                .directed(false)
                .build();
        elements.add(e1);
        elements.add(e2);

        graphBE.execute(new AddElements.Builder().input(elements).build(), new User());
        graphClassic.execute(new AddElements.Builder().input(elements).build(), new User());

        GetElementsInRanges op = new GetElementsInRanges.Builder()
                .input(new Pair<>(new EdgeSeed("A", "A"), new EdgeSeed("A", "Z")))
                .inOutType(SeededGraphFilters.IncludeIncomingOutgoingType.INCOMING)
                .build();

        CloseableIterable<? extends Element> res = graphBE.execute(op, new User());
        for (Element e : res) {
            System.out.println(e);
        }
        res.close();
        // Returns 1 edge
        res = graphClassic.execute(op, new User());
        for (Element e : res) {
            System.out.println(e);
        }
        res.close();
        // Returns 4 edges

**Comment by p013570** [comment]
Merged into develop.
