### ISSUE TITLE
Serialisers of group-by properties for ordered stores should be consistent

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1134]
If the serialiser for a group-by property isn't consistent (i.e. the same object may potentially be serialised in two different ways) then ingest aggregation in the `AccumuloStore` will not work properly. This is because the group-by properties will not necessarily appear in the correct order (note this is a different, but related, issue to the need for the group-by properties to preserve ordering - here the property may not be comparable so ordering won't be preserved but it's still important for all of the same group-by properties to appear in consecutive rows). Currently the only indication a user will get of that is the warning message "serialiser is used for a 'group by' property in an ordered store and it does not preserve the order of bytes" (as the serialiser will presumably be marked as not preserving ordering).

An example of this would be if a user used a `FreqMap` as a group-by property. The serialiser iterates through the `HashMap` writing out the keys and values. The ordering of the keys is not guaranteed so the same map may serialise in 2 different ways.

Options - the first of these is probably best:
- Introduce a method on `Serialiser` to indicate whether the serialisation is consistent. Check that this is true for any property that is used in a group-by in `AccumuloStore` and other similar stores.
- Add Javadoc to `Serialiser` which says that it is assumed that `Serialiser` is consistent (this would require a non-breaking change to `FreqMapSerialiser`).

We should think about how this relates to the current warning message if a serialiser for a group-by property does not preserve ordering (see #1135) - are they independent concepts or should there be a hierarchy: doesn't preserve ordering and may not be consistent; consistent but may not preserve ordering or there might not be an ordering; consistent and preserve ordering?

To a user who specifies a group-by property that isn't serialised consistently then this would appear to be a bug as they might get results in which the ingest aggregation has not happened. Hence this issue is marked as a bug as we should reject such a schema for stores that can't deal with it.

**Comment by m607123** [comment]
# Migration

Serialisers for groupBy properties and vertices are now required to be consistent - if a user tries to create a schema with a serialiser for a groupBy property or vertex that is inconsistent, it will now be rejected.

SerialisationFactory has also been changed to select new serialisers, so if you have existing data already, you will need to manually hardcode the serialisers into the schema, to avoid them potentially changing.

**Comment by p013570** [comment]
Merged into develop.
