### ISSUE TITLE
Clarify warning message "serialiser is used for a 'group by' property in an ordered store and it does not preserve the order of bytes"

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1135]
The `SchemaOptimiser` warns if the serialiser used for a group by property does not preserve the ordering of the property (see line 112). This warning message is confusing:

- It doesn't tell the user how worried they should be - they have to guess at the implications - does it mean that they will get incorrect results (presumably not as if so it should be an error), does it mean that performance will be slower, does it mean that range scans won't work?
- Currently the fact that the serialiser doesn't preserve ordering doesn't cause any issues at all (although see #1134). In future, if we we optimise queries that specify filters on the first N of the group-by properties then the serialiser would need to preserve the ordering.

**Comment by p013570** [comment]
New serialisation documentation for the wiki:

##### Serialisers
Gaffer will automatically choose serialisers for you for some core types.
Where possible you should let Gaffer choose for you, as it will choose the optimal
serialiser for the type and your usage.

For custom types you will need to write your own serialiser. When manually
choosing a serialiser for your schema you will need to take the following into
consideration.

For vertex serialisation and groupBy properties you must choose serialisers that
are consistent. A consistent serialiser will serialise the equal objects into
exactly the same values (bytes). For example the JavaSerialiser and
FreqMapSerialiser are not consistent.

When using an ordered store (a store that implements the ORDERED StoreTrait),
this includes Accumulo and HBase, you need to check whether the serialisers are
ordered.

 - for vertex serialisation you must use a serialiser that is ordered
 - for groupBy properties we recommend using a serialiser that is ordered, however it is not essential. In fact it will not cause any problems at present. In the future we plan to add features that would only be available to you if your groupBy properties are serialised using ordered serialisers.
 - all other properties can be serialised with ordered/unordered serialisers.

**Comment by p013570** [comment]
Merged into develop.
