### ISSUE TITLE
Override Operation.shallowClone() for all Concrete implementations

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1137]

**Comment by GCHQDeveloper404** [comment]
default implementations needs to be overridden with a concise clone method, that avoids the expensive serialisation-deserialisation.

**Comment by GCHQDeveloper404** [comment]
After gh-955 is completed and merged.

**Comment by p013570** [comment]
So basically all implementations of Operation needs to override/implement the shallowClone method. This is intended to be a very shallow clone - simply just creating a new instance of the operation and copying all the fields across (without cloning the fields).

For example for AddElements:

```java
public AddElements shallowClone() {
    return new AddElements.Builder()
        .validate(validate)
        .skipInvalidElements(skipInvalidElements)
        .input(elements)
        .options(options)
        .build();
}

Then adding a unit test to check all fields were copied successfully.

**Comment by p013570** [comment]
Merged into develop.

**Comment by m55624** [comment]
***Migration Steps***

All new and current Operation implementations must implement a ShallowClone method.  This method should perform a shallow clone that will create a new instance and copies the fields across.  It should not fully clone the fields.
