### ISSUE TITLE
Shaded jar for time-library

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1151]
It would be useful if the pom of time-library specified a shaded jar. This jar could then be deployed to the tablet servers of an Accumulo store to allow properties from this library to be used. The pom should include:

    org.roaringbitmap:RoaringBitmap
    uk.gov.gchq.gaffer:bitmap-library
    uk.gov.gchq.gaffer:sketches-library

**Comment by p013570** [comment]
Merged into develop.
