### ISSUE TITLE
Throw error if GetElements builder does not set the seeds

### ISSUE THREAD

**Issue by ac74475** [gchq/Gaffer#1154]
If a user builds a GetElements operation and doesn't specify any input then it should throw an error, if they pass in an empty Iterable then it should quietly return no results.

**Comment by p013570** [comment]
Currently we validate the entire operation chain before it is executed. If the GetElements operation is used in a chain then the input will initially be null. It is only set after the previous operation in the chain is executed. So we would need to add a secondary validation stage, so in addition to validating at the beginning of the chain, we would need to validate just before we execute each individual operation.

Currently the GetElements input is just validated in the GetElementsHandler classes.

**Comment by ac74475** [comment]
The behaviour is the same with the ParquetStore as the AccumuloStore. I just thought we could alert the user if they do not set the input, while still working as it currently does if it is a stage in an operation chain. So from what @p013570 wrote this is just a matter of each GetElementsHandler throwing an error if the input is null.

**Comment by m607123** [comment]
Merged into develop.
