### ISSUE TITLE
Parquet store - maximise use of index for view filters

### ISSUE THREAD

**Issue by ac74475** [gchq/Gaffer#1160]
When generating the path to filter mapping, we could make use of the indices to reduce the number of files to query by applying the following logic within the ParquetFilterUtils class.
If the selection column is not indexed then return set of all paths in graph/Group=X,
Otherwise:
IsEqualTo - returns the list of files which could contain the desired value
IsLessThan(OrEqual) - returns the list of files which could contain the desired value and all files before them
IsMoreThan(OrEqual) - returns the list of files which could contain the desired value and all files after them

If only one column in the selection then:
And - find the intersection of the two sets of paths
Or - merge the two sets of paths
Not - return set of all paths in graph/Group=X

If there are multiple columns in the selection then:
And - pick the set of paths with the fewest number of files
Or - return set of all paths in graph/Group=X
Not - return set of all paths in graph/Group=X

**Comment by p013570** [comment]
Merged into develop.
