### ISSUE TITLE
Improve Ingest for Parquet store from RDD

### ISSUE THREAD

**Issue by ac74475** [gchq/Gaffer#1186]
Currently with the ingest process for very large volumes of data, the aggregation job will take a long time or fail due to Spark wanting all the pre-aggregated data in memory. This often causes data to have to be spilled to disk which is very costly.

Therefore I propose the ingest process from RDD's could be changed to:
- take a sample of data to generate suitable split points or take the previous data's index as the split points
- write out the unsorted data into folders for each range of vertex and src values
- aggregate each folder adding in the existing corresponding data (This will prevent the whole lot of data needing to me in memory at once and should make the solution much more scalable)
- load in the whole groups data, sort by vertex/src and write out to desired number of files
- copy over the src folder's data and sort by dest to generate the dest sorted data
- generate the indices

**Comment by gaffer01** [comment]
Merged into develop.
