### ISSUE TITLE
HBase backend using deprecated class HTable

### ISSUE THREAD

**Issue by mbrukman** [gchq/Gaffer#1190]
The [HBase backend is using the `HTable` class](https://github.com/gchq/Gaffer/blob/94f97b4aedf6ed3342ece4f042a2cbec4a90038b/store-implementation/hbase-store/src/main/java/uk/gov/gchq/gaffer/hbasestore/HBaseStore.java#L159-L168). It has been deprecated in HBase 1.0 and the `Table` class should be used instead.

As we can see in the [Javadoc for `HTable` in HBase 1.3.0](https://static.javadoc.io/org.apache.hbase/hbase-client/1.3.0/org/apache/hadoop/hbase/client/HTable.html):

> `HTable` is no longer a client API. Use [`Table`](https://static.javadoc.io/org.apache.hbase/hbase-client/1.3.0/org/apache/hadoop/hbase/client/Table.html) instead. It is marked InterfaceAudience.Private as of hbase-1.0.0 indicating that this is an HBase-internal class as defined in Hadoop Interface Classification. There are no guarantees for backwards source / binary compatibility and methods or the class can change or go away without deprecation.

**Comment by p013570** [comment]
@mbrukman - thanks for spotting this, we will get this changed before we release Gaffer 1.0.0.

**Comment by p013570** [comment]
@mbrukman - if you you would like to contribute and make the change yourself, then you just need to sign our [contributor license agreement](https://github.com/gchq/Gaffer/wiki/GCHQ-OSS-Contributor-License-Agreement-V1.0) first.

**Comment by p013570** [comment]
Merged into develop.
