### ISSUE TITLE
Question: How would you implement shortest path and other graph algorithms?

### ISSUE THREAD

**Issue by supamanda** [gchq/Gaffer#1199]
Hi,

There's an example for implementing 2-hop as a named query, but it's not clear how to implement more complex graph algorithms, e.g. shortest path. How would you do it?

Thanks,
Amanda

**Comment by p013570** [comment]
Hi Amanda,

The best way to implement it would be as a new Gaffer Operation. That way you can write the logic in Java and register the Operation in Gaffer so it can be easily executed just like you would execute a GetElements operation. Alternatively you can write the logic in some other language and execute Operations on the REST API.

To write a new Operation that you would need to write 2 files:
- an implementation of Operation to hold the config/inputs for your algorithm, e.g for Shortest Path that class could have: Object start, Object end, Integer maxHops.
- an implementation of OperationOutputHandler. This is the class where the algorithm logic should live. Deciding how to write that logic is the hard bit. You have several options - see below.

Once you have these 2 classes you can then register them with the Store.

We are hoping to start work on these sorts of operations in a few months time. We have done some work on exporting to GraphX in issue #792.


In terms of the algorithm logic, you could write the algorithm logic yourself and make calls to other operations like GetAdjacentIds to hop around the graph. The specific logic would be different depending on the types of Entities and Edges you have in your Graph. For example we suggest adding a Cardinality Entity to all vertices so you can get a quick estimate of how connected a vertex is. If your graph has these Cardinalities then you can use these in your algorithm, in shortest path you could make use of these to help decide which edges to traverse down.
Alternatively you could delegate to one of the spark operations like GetRDDOfAllElements or export to GraphX.

Hope that helps.
