### ISSUE TITLE
Optimise the removal of properties in the Parquet Store

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1203]
To be done after #1179.

If a user asks for only a subset of properties to be returned in a query we should be able to skip deserialising them. This will only work if those properties are not used in Transforms or Filters.

**Comment by ac74475** [comment]
This will require the pruned Parquet schema being passed into the ReadContext when calling the ElementReadSupport.init() method instead of the full schema.

**Comment by jsamesgsfus123** [comment]
Hi Friends ,
There i use a new best image compression tool  https://optimizejpeg.com/  to compress my image/png/jpef/gif and it works faster without  lossing image quality.
