### ISSUE TITLE
Improve parsing of GB Road Traffic Count data set

### ISSUE THREAD

**Issue by ctas582** [gchq/Gaffer#1207]
The [GB Road Traffic Counts](https://data.gov.uk/dataset/gb-road-traffic-counts) data set was updated in May 2017 to include the counts up to and including 2016. The current parser and element generator cannot be used with this updated version of the data set as:

* 2 new columns have been added
* not all fields are quoted
* the date format has changed

**Comment by t616178** [comment]
Merged into develop.
