### ISSUE TITLE
Unit tests for ImportKeyValuePairRDD and ImportRDDOfElements should use standard temp directory

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1220]
The unit tests `ImportKeyValuePairRDDToAccumuloHandlerTest` and `ImportRDDOfElementsHandlerTest` create temporary directories in the current directory - they should use `CommonTestConstants.TMP_DIRECTORY` as other unit tests do.

`ImportRDDOfElementsHandlerTest` should use `ClassTagConstants.ELEMENT_CLASS_TAG` rather than creating its own class tag (line 51). The same applies to `ImportKeyValuePairRDDToAccumuloHandlerTest`.

**Comment by p013570** [comment]
Merged into develop.
