### ISSUE TITLE
Add an OperationChainHandler for the FederatedStore

### ISSUE THREAD

**Issue by m607123** [gchq/Gaffer#1243]
Implement the handling of OperationChains on a per-graph basis, delegating the chain to each graph, and storing each output in a ChainedIterable.

**Comment by m607123** [comment]
Since each Operation now has its' own Map of Options, how should the Map from each Operation be handled in relation to the overall OperationChain? If the Map of each Operation differs, should this be ignored/merged/handled some other way?

**Comment by t616178** [comment]
Merged into develop.
