### ISSUE TITLE
Review approach to deleted entries in the Accumulo store

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1248]
We don't currently provide any way for a user to delete entries from an Accumulo Store. The removal of invalid elements (which is done in the iterators that run at compaction time) isn't deletion in this sense. A user could still manually delete entries from the Accumulo table. Our operations should respect the deletion flags on key-values, for both standard queries and the queries that return Spark RDDs.

**Comment by p013570** [comment]
Merged into develop.
