### ISSUE TITLE
Rename addinputMapperPair(s) to addInputMapperPair(s)

### ISSUE THREAD

**Issue by m55624** [gchq/Gaffer#1261]
The typo currently in MapReduce.java.  addinputMapperPair needs to change to addInputMapperPair and all uses updating.

**Comment by m55624** [comment]
# Migration Steps

For any Operation that implements the MapReduce.java interface, the builder used addinputMapperPair but has now been corrected to addInputMapperPair.

When using this addinputMapperPair, all usages must be updated to addInputMapperPair

**Comment by p013570** [comment]
Merged into develop.
