### ISSUE TITLE
Question: Operation specific config not being read 

### ISSUE THREAD

**Issue by supamanda** [gchq/Gaffer#1271]
hi again :)

I'm trying to add trace logging when I run my operation without affecting everyone else's, but it seems to just use whatever the defaults are. I've traced through and it looks like when it's deserialising the custom config stored at Hadoop_Configuration_Key in the operation, it reads -17 as the length and then ignores any of the config. Am I doing something wrong? Is there some other way of adding custom config?

The code I'm using is below: 

```
val customhadoopconffile = new FileInputStream("/path/to/myconf.xml")
val conf = new Configuration()
conf.addResource(customhadoopconffile)
val baos = new ByteArrayOutputStream()
val dataoutput = new DataOutputStream(baos)
conf.write(dataoutput)
val myhadoopconf = new String(baos.toByteArray(), "UTF-8")

...

val operation = new GetRDDOfElements.Builder().input(new EntitySeed("0.0.0.0")).option("Hadoop_Configuration_Key", myhadoopconf).sparkContext(sc).build()
```

myconf.xml is:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><configuration>
  <property>
    <name>AccumuloInputFormat.GeneralOpts.LogLevel</name>
    <value>5000</value>
  </property>
</configuration>
```

Thanks,
Amanda

**Comment by gaffer01** [comment]
Apologies for the delay in responding.

You're right, there is a bug. Serialising the byte array to a string as it is currently done isn't safe. I'll change it to base 64 encode the byte array and use that as the string.

Thanks for finding the bug.

**Comment by p013570** [comment]
Merged into develop.
