### ISSUE TITLE
GetAdjacentIds with a view containing entity filters is invalid

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1275]
We should validate the GetAdjacentIds operations and if the view contains any entities with filters then we should throw an exception.

When an GetAdjacentIds operation is handled it does not load any entities so no entity filters can be applied.

**Comment by m607123** [comment]
There only seems to be a test for the MapStore implementation of the GetAdjacentIds, @p013570 would you like similar tests writing for the other Store implementations as well?

**Comment by m607123** [comment]
# Migration
When building a GetAdjacentIds operation, please ensure that entities **do not have any**:
- preAggregationFilter
- postAggregationFilter
- postTransformFilter

attached to them whatsoever, else the operation will fail validation and throw an IllegalArgumentException.

**Comment by p013570** [comment]
Merged into develop.
