### ISSUE TITLE
Remove doc module and wiki pages

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1288]
The doc has been moved to [gaffer-doc](https://github.com/gchq/gaffer-doc).

We should delete /doc and /library/spark/spark-doc

The only wiki page that should be kept is:
https://github.com/gchq/Gaffer/wiki/GCHQ-OSS-Contributor-License-Agreement-V1.0

We also need to make sure all links point to the new gaffer-doc url. For example there is a link in the federated store README that points to the wiki that will need updating.

**Comment by d47853** [comment]
There's a few dead links in accumulo-store/README.md that points to accumulo-store/Getting-Started.md (Which doesn't exist). Where should this link point to?

**Comment by p013570** [comment]
It should point to somewhere in here: https://gchq.github.io/gaffer-doc/getting-started/user-guide.html

**Comment by p013570** [comment]
Merged into develop.
