### ISSUE TITLE
Create Transform operation

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1292]
Create a new Filter operation that takes an iterable of elements and an ElementTransform. The handler should just apply the transformations to the elements.

**Comment by m607123** [comment]
Would it be wise to potentially combine this with #1291 ? The functionality will be quite similar, insomuch that it's applying a predicate and returning a filtered iterable of elements.
I can of course simply make the Stream implementations in #1291 more general, and just have the operation & handler interact with these.

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
Please note, this operation will note be available be default until this bug is fixed: https://github.com/gchq/Gaffer/issues/1341
