### ISSUE TITLE
When using a Graph Library we need a mechanism for applying updates to the schema or properties

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1314]
1st attempt.
```
gaffer.store.class=uk.gov.gchq.gaffer.federatedstore.FederatedStore
gaffer.store.properties.class=uk.gov.gchq.gaffer.store.StoreProperties
```

a month later, redeploy
```
gaffer.store.class=uk.gov.gchq.gaffer.federatedstore.FederatedStore
gaffer.store.properties.class=uk.gov.gchq.gaffer.store.StoreProperties
gaffer.federatedstore.graphIds=edgeGraph
...ect
```

error thrown because the federatedStore properties file is now different to the one that exists in the library that contains federatedStore details.

**Comment by GCHQDeveloper404** [comment]
link gh-1297

**Comment by GCHQDeveloper404** [comment]
link gh-1304

**Comment by p013570** [comment]
This is not really specific to the FederatedStore, but to any properties or schema that are persisted in the Graph Library that need to be updated. We need a mechanism for updating schemas/properties in the Graph Library. For now users will have to manually update the GraphLibrary before using it.

**Comment by p013570** [comment]
#1430 will add a AddSchema and AddStoreProperties operations, which will fix this issue too.
