### ISSUE TITLE
FederatedStore deadlock after failed addGraph.

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1316]
Bug replication:

Error is thrown while adding a graph with Schama collision gh-1304.
But the schema belonging to the failed "add graph" has been added to the graphLibrary, which is unexpected by user.

Every subsequent add graph with correct and legal schema will now fail.
Suspected because the in memory schema held in the FedStore instance has been updated with the previously wrong schema.

Can be recovered using a removeGraph with the failing graphId. then the subsequent correct addGraph works.

**Comment by p013570** [comment]
Merged into develop.
