### ISSUE TITLE
FederatedStore user seeing graphIds they don't have access too.

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1321]
check/test

User1 adds graph1.
User2 asks get all graphIds
User2 can see graph1. //Wrong.

**Comment by p013570** [comment]
This may mean we have to refactor the FederatedAccessHook. The logic may need to live in the FederatedStore instead so it can be reused.

**Comment by GCHQDeveloper404** [comment]
branch: gh-1321-FederatedStore-hiding-graphIds
Error
```
GetElementsIT.shouldGetElements()
```
```
java.lang.AssertionError: GetRelatedElements failed with parameters: 
includeEntities=true 
includeEdges=true 
directedType=UNDIRECTED 
inOutType=OUTGOING
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by GCHQDeveloper404** [comment]
commit 4f74328

**Comment by p013570** [comment]
Merged into develop.
