### ISSUE TITLE
addGraph shallow clone add graphAuths

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1326]
AddGraph Shallow clone doesn't copy graphAuths

**Comment by GCHQDeveloper404** [comment]
Auth graphs are created private.

**Comment by GCHQDeveloper404** [comment]
@Override
    public AddGraph shallowClone() throws CloneFailedException {
        return new Builder()
                .graphId(graphId)
                .schema(schema)
                .storeProperties(storeProperties)
                .parentSchemaIds(parentSchemaIds)
                .parentPropertiesId(parentPropertiesId)
                .options(options)
                .graphAuths(graphAuths.toArray(new String[graphAuths.size()]))  //potentially needs tidying
                .build();
    }

**Comment by GCHQDeveloper404** [comment]
AddGraph Tests wasn't picking this up.

**Comment by p013570** [comment]
Merged into develop.
