### ISSUE TITLE
Spark operation examples don't show how to specify Hadoop conf

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1328]
The examples for operations such as `GetJavaRDDOfAllElements` don't show how the Hadoop configuration can be passed in as an option. Passing this option in isn't essential if you're running your code either via the `hadoop` command or within a Spark job that has been configured with Hadoop, but it means you can't override properties in the configuration.

**Comment by p013570** [comment]
Please note these examples have now been moved to the gaffer-doc module, so any changes need to be applied there.

**Comment by p013570** [comment]
This has been done in gaffer-doc.
