### ISSUE TITLE
Validate the user is not null for operations.

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1360]

**Comment by PammyS** [comment]
@GCHQDeveloper404 if this is still open I'll be happy to take this task, please assign it to me

**Comment by p013570** [comment]
Hi @PammyS,

Yes it is still open, thank you. 

It looks like @m607123 did some work on it on branch gh-1360-validate-user-operations, but I'm not sure how far he got with it. Either work off his branch or feel free to start again and branch off develop.

Just make sure you have signed our [Contributors License Agreement](https://github.com/gchq/Gaffer/wiki/GCHQ-OSS-Contributor-License-Agreement-V1.0)

@GCHQDeveloper404 - can you add a description to this issue please.

**Comment by m607123** [comment]
Hi @PammyS!

Unfortunately this kind of fell by the wayside, so far I've only added a null check to the OperationChainValidator, and the FederatedOperation handlers.

I spent a short amount of time considering a way to either add the check into each implementation of OperationHandler, or some more efficient way using the interface itself - perhaps some new validation?

Hope this helps, perhaps @GCHQDeveloper404 may be able to advise on the desired outcome.

**Comment by GCHQDeveloper404** [comment]
@PammyS Yes please, take this on. Sorry I missed these messages.

**Comment by PammyS** [comment]
@GCHQDeveloper404 @p013570 @m607123 
Thanks all! I have signed the agreement. 
@m607123  which branch have you worked on?

**Comment by m607123** [comment]
@PammyS The branch name is:
gh-1360-validate-user-operations

**Comment by PammyS** [comment]
@p013570 Hi
I am not able to push code 
seems like i don't have required access

**Comment by p013570** [comment]
Hi @PammyS,

You will need to create a fork of the Gaffer repository then create a pull request to merge your branch in to gchq/Gaffer from [your fork]/Gaffer.

This might help: https://help.github.com/articles/fork-a-repo/

**Comment by p013570** [comment]
Merged into develop.
