### ISSUE TITLE
FederatedAccess Public access

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1362]
Test and Check.

**Comment by p013570** [comment]
Merged into develop.

**Comment by GCHQDeveloper404** [comment]
# Migration Step
### isPublic
All graphs are defaulted to private access, unless you update the access authorisation of your graphs and users, the quickest and easiest step is to set you graph within Federated Store to be public access.

Within properties file `gaffer.federatedstore.<graphId>.isPublic=true`
or within properties object `setTrueGraphIsPublicValue(<graphId>);`

### Operation Keys
The public constants for federated operations options have been renamed, but the string values remain the same.
`GRAPH_IDS` -> `KEY_OPERATION_OPTIONS_GRAPH_IDS`
`SKIP_FAILED_FEDERATED_STORE_EXECUTE` -> `KEY_SKIP_FAILED_FEDERATED_STORE_EXECUTE`
