### ISSUE TITLE
Add a custom score to NamedOperations

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1364]
We have a GraphHook called OperationChainLimiter, that limits the combination of operations that are allowed to be executed at the same time.

Each operation can be given a score and when an operation chain is executed the scores for each operation is summed. The total score for the operation chain is then compared against an allowed maximum score for the given user.

This works well for normal operations. Named Operations and potentially other operations in the future may need to have a variable score depending on how it is configured. So it would be useful to have another interface:

```java
public interface ScoreResolver {
    int getScore(final Operation operation);
}
```

AddNamedOperation needs to be updated to take an optional extra field 'score' that should be persisted in the Named Operation Cache. We would then need to write a NamedOperationScoreResolver that looks up the score for the NamedOperation in the Named Operation Cache. If the Named Operation does not have a score then return null and the score can be resolved by the default mechanism in ScoreOperationChainHandler.

We would then need to configure ScoreOperationChainHandler to have a map of Operation class to implementation of ScoreResolver. If the operation is not in this map then we can just default to using the configured opScores map.

**Comment by m607123** [comment]
No migration required - compatible with Gaffer V1.0.2.
Any existing NamedOperations will still function exactly as before, however their scores will default to the value of the score in the opScores.properties file.

Now when using the AddNamedOperation operation, an optional "score" field can be passed in, to assign a custom score to a particular NamedOperation, which will override the score in the properties file.

**Comment by p013570** [comment]
Merged into develop.
