### ISSUE TITLE
GraphLibrary addProperties

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1375]
GraphLibrary when adding a property takes in an ID for that property `graphLibrary.addProperties(final String propertiesId, final StoreProperties properties)`. I believe this will clash and be out of sync with the properties internal id `props.getId()`

I think it should be examined and possibly changed to...

```
    public void addProperties(final StoreProperties properties) {
        if (null != properties) {
            final String id = properties.getId();
            validateId(id);  //in here already throws exception for nulls!
            if (propertiesExists(id)) {
                throw new OverwritingException("trying to override properties: " + id);
            }
            _addProperties(id, properties);
        }

    }

    protected abstract boolean propertiesExists(final String id);
```

**Comment by m55624** [comment]
The same exists for Schemas.  Currently addSchema also takes an id, and the Schema that is added contains an id field.  They will clash and could differ with unexpected id's being stored.

**Comment by p013570** [comment]
Merged into develop.
