### ISSUE TITLE
Change All Spark Operations to accept Spark Session

### ISSUE THREAD

**Issue by james010101101** [gchq/Gaffer#1379]
Some spark based operations accept sparksessions, while some acceptJavaSparkContext's, this should be standardised so all operations accept sparksessions, 

A better method of supplying the spark sessions to the operations is needed, currently a spark session is provided as a mandatory option on each operation, which has the side effect that spark operations can't be run over the rest service.

I propose we change this so that you create a gaffer "spark context" (inheriting from the gaffer context object)  in your store if you enable spark operations, which will then contain a spark session.which can be retrieved in the handler

**Comment by p013570** [comment]
#Migration Steps
The GraphHook interface has changed so it now takes a Context object instead of just the user object.

**Comment by p013570** [comment]
Merged into develop.
