### ISSUE TITLE
API report for GCHQ Graph

### ISSUE THREAD

**Issue by lvc** [gchq/Gaffer#1390]
Hi,

Here is the report on API changes and backward binary compatibility for the GCHQ Graph library: https://abi-laboratory.pro/java/tracker/timeline/gchq-graph/

The report is generated by the https://github.com/lvc/japi-compliance-checker tool for jars at http://central.maven.org/maven2/uk/gov/gchq/gaffer/graph/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library to be aware of past and future API changes.

The tool checks all public API methods and classes. Please let me know if it should not check some parts of the API.

Please also let me know if you'd like to see more components of the library in the tracker.

Thank you.

![gchq-graph-2](https://user-images.githubusercontent.com/1517837/31326114-0c1bcabe-accd-11e7-93b0-9ecbd4f40fe3.png)
![gchq-graph-1](https://user-images.githubusercontent.com/1517837/31326113-0c1bc5c8-accd-11e7-8a65-d57e68f1671b.png)

**Comment by p013570** [comment]
Hi @lvc,

That is very useful, thank you for sharing it. It does highlight several breaking changes when upgrading to 1.0.0-RC3. But, once we have completed our version 1.0.0 release, we expect the API will be much more stable.

Thanks.
