### ISSUE TITLE
Allow Edges to be bidirectional

### ISSUE THREAD

**Issue by supamanda** [gchq/Gaffer#1395]
hi,
It looks like you can store directional or not directional edges. Is it possible to store bidirectional edges (aside from storing two copies of the edge)?
Thanks,
Amanda

**Comment by p013570** [comment]
Hi Amanda,

Not at the moment. Currently you would just have to store the Edge both ways around. I don't think it would be too hard to update the Edge class to allow the direction to set to bidirectional. I'll add it to the backlog of issues.

Is it something that you would use if we implemented it?

Thanks.

**Comment by gaffer01** [comment]
Is there any difference between a bi-directional edge and an undirected edge? Are there any domains where you would want to have an undirected edge and a bi-directed edge in the same graph? e.g. in a road network graph you would use directed edges for one-way streets and undirected edges for two-way streets.

**Comment by supamanda** [comment]
From my point of view, it seems clearer to be able to distinguish in the data whether the edge is bi-directed or undirected - but I am far from an expert in this field. I don't know whether you would have undirected and bi-directed edges in the same graph, and I also don't know whether it would have a negative effect on performance if you did allow it.

Validation failed if I tried to store an undirected edge element when the edge's schema had directed set to true, so I ended up storing two copies of the edge (one for each direction). I haven't yet tried leaving the directed setting out of the schema - does that work?

**Comment by p013570** [comment]
@supamanda - regarding the validation, I believe you have this in your schema:

```json
{
  "edges": {
    "NetflowCount": {
      ...
      "directed": "true",
      ...
    }
  }
}

{
  "types": {
    "true": {
      "description": "A simple boolean that must always be true.",
      "class": "java.lang.Boolean",
      "validateFunctions": [
        {
          "class": "uk.gov.gchq.koryphe.impl.predicate.IsTrue"
        }
      ]
    }
  }
}
```

If you want to allow both directed and undirected direction values to be set then you could just rename the "true" type to "either" and then just delete the IsTrue validation function. The result would be:

```json
{
  "edges": {
    "NetflowCount": {
      ...
      "directed": "either",
      ...
    }
  }
}

{
  "types": {
    "either": {
      "description": "A simple boolean that can be true or false",
      "class": "java.lang.Boolean"
    }
  }
}
```

**Comment by supamanda** [comment]
Great! Thanks for that, I'll try it out.

**Comment by p013570** [comment]
I don't think this is required as it can be largely achieved already.
