### ISSUE TITLE
Shaded jar for time-library is missing common util

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1402]
The shaded jar for time-library is missing a dependency on `uk.gov.gchq.gaffer:common-util` which means that the `RBMBackedTimestampSet` class can't find `CommonTimeUtil`.

**Comment by p013570** [comment]
It is also missing other Gaffer and Koryphe dependencies. It was assumed that this shaded jar would be used alongside the Accumulo shaded iterators jar. To allow it to be used without the accumulo jar I will add all dependencies to each of the shaded library jars - road-traffic-generators, bitmap-library, time-library, sketches-library.

**Comment by p013570** [comment]
I've made the code changes but it significantly increases the file size of those shaded jars. Not sure we really want to do that.

**Comment by p013570** [comment]
To avoid coupling libraries together and to keep the file sizes smaller, we will keep these shaded jars distinct and require users to always use the accumulo shaded jar and then any of the extra libraries they want.
