### ISSUE TITLE
Add test coverage monitoring

### ISSUE THREAD

**Issue by a09631** [gchq/Gaffer#142]
There is currently no way to monitor the level of test coverage for the project.  We should have some simple metrics in order to keep track of the level of coverage to ensure this isn't trending downward.

**Comment by t616178** [comment]
We could potentially use Coveralls to do this for us.

https://coveralls.io

**Comment by p013570** [comment]
I was thinking about using [codecov](https://github.com/integrations/codecov) which also integrates nicely with github.

**Comment by t616178** [comment]
The following changes have been applied in order to get codecov integration working:

    A new profile has been created (-Ptravis), specifically for building Gaffer on Travis. This is required since the previous profile used in the Travis build process required setting the Maven Surefire plugin's forkCount property to 0, which breaks JaCoCo and prevents the test reports from being generated.
    Since the forkCount property must be set to 1, the tests fail due to memory issues in the Travis containerised environment. To resolve this, fork reuse has been disabled and the amount of heap memory available to the Java process has been increased (-Xmx3072m).

If there are any issues with the Travis build process in future (entirely possible, as I'm not sure how marginal the build process is on memory at the moment), this approach may need to be revisited.

**Comment by p013570** [comment]
Merged into develop.
