### ISSUE TITLE
Reassess usage of mocking in Federated Store unit tests

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1429]
In the past Mockito became difficult to update to act as it should. When removing Mockito and using the correct instance bugs where highlighted. It maybe beneficial to remove the remaining Mockitos from `FederatedStoreTest`.

**Comment by m55624** [comment]
I have just looked through these tests and there is only two Mockito uses, both of which are needed and act correctly.  I don't think there is anything to do on this.
