### ISSUE TITLE
Create AddSchemaToLibrary and AddStorePropertiesToLibrary Operations

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1430]
The Add Schema operation will add schemas to the GraphLibrary to be used within the FederatedStore

**Comment by GCHQDeveloper404** [comment]
Add new useful schema to the library to be used within federated store.

**Comment by GCHQDeveloper404** [comment]
Add StoreProperties was appended.

It should be known that both handlers delegates methods to GraphDelegate class. Which is currently not 100% correct because of the defaults to schema and store properties from the store. which is wrong for a FederatedStore. This is being corrected in another ticket, once all are merged this will resolve without duplication of efforts.

**Comment by p013570** [comment]
Merged into develop.
