### ISSUE TITLE
Add Max example to ExamplesFactory

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1450]
Add a new interface method to ExamplesFactory:

```java
Max max();
```

Add a new implementation to DefaultExamplesFactory. See [doc](https://gchq.github.io/gaffer-doc/getting-started/operation-examples.html#max-example) for some examples of using the Max operation.

Hook the example up in the DefaultExamplesFactory.generateExample method, i.e. add a new if block for:
```java
else if (operation instanceof Max) {
    return max(); 
}
```

**Comment by t616178** [comment]
Merged into develop.
