### ISSUE TITLE
Add Min example to ExamplesFactory

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1451]
Add a new interface method to ExamplesFactory:

```java
Min min();
```

Add a new implementation to DefaultExamplesFactory. See [doc](https://gchq.github.io/gaffer-doc/getting-started/operation-examples.html#min-example) for some examples of using the Min operation.

Hook the example up in the DefaultExamplesFactory.generateExample method, i.e. add a new if block for:
```java
else if (operation instanceof Min) {
    return min(); 
}
```

**Comment by t616178** [comment]
Merged into develop.
