### ISSUE TITLE
Add ToMap example to ExamplesFactory

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1452]
Add a new interface method to ExamplesFactory:

```java
ToMap toMap();
```

Add a new implementation to DefaultExamplesFactory. See [doc](https://gchq.github.io/gaffer-doc/getting-started/operation-examples.html#tomap-example) for some examples of using the ToMap operation.

Hook the example up in the DefaultExamplesFactory.generateExample method, i.e. add a new if block for:
```java
else if (operation instanceof ToMap) {
    return toMap(); 
}
```

**Comment by t616178** [comment]
Merged into develop.
