### ISSUE TITLE
FederatedStore Cache method generics

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1458]
The "add" & "get" to the cache can be of different types because of method generics instead of class generics locking the two together. Can this be examined and improved.

`final Pair<GraphSerialisable, FederatedAccess> fromCache = CacheServiceLoader.getService().getFromCache(CACHE_SERVICE_NAME, graphId);`

The Pair contents types is lost. So adding & getting could have mismatched pairs.
In addition there is nothing that links Value types together with adding & getting.

**Comment by p013570** [comment]
@GCHQDeveloper404 please can you add some more detail to this issue?

**Comment by GCHQDeveloper404** [comment]
FederatedStore.addGraphToCache() adds a value which is a pair as a value (GraphSerialisable & FederatedAccess).

FederatedStore.getGraphFromCache() gets a pair back but due to type erasure and method generics 
can be change into any types the returns pair is, this could lead to bugs.

```

 public void addGraphToCache(final Graph graph, final FederatedAccess access, final boolean overwrite) throws CacheOperationException {
        Pair<GraphSerialisable, FederatedAccess> pair = new Pair<>(new GraphSerialisable.Builder().graph(graph).build(), access); // HERE TYPE IS ADDED
        final ICacheService service = CacheServiceLoader.getService();
        try {
            if (overwrite) {
                service.putInCache(CACHE_SERVICE_NAME, graph.getGraphId(), pair);
            } else {
                service.putSafeInCache(CACHE_SERVICE_NAME, graph.getGraphId(), pair);
            }
        } catch (final CacheOperationException e) {
            throw new CacheOperationException(String.format(ERROR_ADDING_GRAPH_TO_CACHE_GRAPH_ID_S, graph.getGraphId()), e);
        }
    }

public GraphSerialisable getGraphSerialisableFromCache(final String graphId) {
        final Pair<GraphSerialisable, Integer> fromCache = CacheServiceLoader.getService().getFromCache(CACHE_SERVICE_NAME, graphId); // HERE RETURN TYPE COULD BE COMPLETLY DIFFERENT
        return (null == fromCache) ? null : fromCache.getFirst();
    }

    public FederatedAccess getAccessFromCache(final String graphId) {
        final Pair<Integer, FederatedAccess> fromCache = CacheServiceLoader.getService().getFromCache(CACHE_SERVICE_NAME, graphId); // HERE RETURN TYPE COULD BE COMPLETLY DIFFERENT
        return fromCache.getSecond();
    }
```

**Comment by GCHQDeveloper404** [comment]
protection when adding pairs to the cache. the internal types of the pair could have inconsistencies.
