### ISSUE TITLE
Improved approach to loading data into Parquet store from Accumulo store

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1464]
Data can currently be loaded from an Accumulo store into a Parquet store by using a `GetRDDOfAllElements` operation followed by an `ImportRDDOfElements` operation. This approach does not take advantage of the sorting of the Accumulo data. The elements are written out to a temporary directory, and then resorted.

It would be better to take each Accumulo tablet and write that out as sorted Parquet files. Each tablet contains 3 types of key-value corresponding to Entitys, "forward" edges and "backwards" edges. These would be written out to different Parquet files (under the group=G/ directories for entities and forwards edges or under the sorted-by-destination directory for backwards edges). These files would already be sorted and partitioned. This should significantly speed up ingest into the Parquet store from the Accumulo store. The resulting files may not be uniformly sized, e.g. if there is an Accumulo tablet containing only edges out of a single high-degree vertex, but this is probably a trade worth making if the ingest time is improved.

This approach should take advantage of the option to directly read RFiles in `GetRDDOfAllElements` as this means the export can be done without imposing additional load on Accumulo's tablet servers.

**Comment by gaffer01** [comment]
Reopening - no explanation of why the 'invalid' label was added or why the issue was closed.

**Comment by n3101** [comment]
We are not supporting parquet in v2.0, so this will not be done.
