### ISSUE TITLE
Parquet store reader is slow

### ISSUE THREAD

**Issue by ac74475** [gchq/Gaffer#1466]
The Parquet stores reader is running a lot slower than expected. Tests before the Spark upgrade had getElements queries running in less than a seconds and now they are taking minutes.

**Comment by ac74475** [comment]
This looks like it is down to the individual file sizes being large rather than any particular bug in the code. There is now a limit on the number of files you can output based on how many Parquet writers you can have open in memory at any time, which is why it has not got slower as I have had to output to less files. A way around this would be to have more memory allocated to each Spark executor.

**Comment by ac74475** [comment]
So while the larger the files the slower the read will be, it is actually the Parquet version that makes the biggest difference. When we went from 1.8.1 it took 600ms to query a 60MB file for a single value. After upgrading the Spark version and therefore the Parquet version to 1.8.2 the time to do the same query on the same data now takes 75219ms.

**Comment by n3101** [comment]
@ac74475 

> When we went from 1.8.1 it took 600ms to query a 60MB file for a single value. After upgrading the Spark version and therefore the Parquet version to 1.8.2 the time to do the same query on the same data now takes 75219ms.

Three and a half years later... I see we are currently running parquet 1.8.3. Is the performance still a problem? 

If so, we will be doing version upgrades in Gaffer2.0 and this will have to wait til then.

**Comment by n3101** [comment]
We are not supporting parquet in v2.0, so this will not be done.
