### ISSUE TITLE
SplitStore from Iterable of Elements

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1469]
The only way of adding split points to an Accumulo table is to use `SampleDataForSplitPoints` followed by `SplitStore`. This is difficult to use if the source data is only available as an iterable, e.g. if it's on Kafka.

We should create a way for a user to create some split points based on an iterable of elements.

**Comment by p013570** [comment]
# Migration Steps
There is no breaking change and no immediate migration required. However, the SplitStore operation has been deprecated and we recommend you update to use SplitStoreFromFile when possible.

**Comment by p013570** [comment]
Merged into develop.
