### ISSUE TITLE
Investigate possible performance improvements for the GetWalks operation

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#1485]
Usage of GetWalks operation has the potential to bring lots of data in memory. The operation implementation should be checked to ensure that typical usage does not result in issues with excessive memory usage.

**Comment by t616178** [comment]
Several possible avenues for performance improvement:

* pruning of orphaned edges while the elements are being added to the temporary store (reduces overall memory consumption and reduces the amount of data to process when determining the walks)
* Perform walk creation in reverse (starting from known walk destinations and tracing back to start may be more efficient than starting with the initial seed vertices).

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
The GetWalks handler now prunes the cached results after each hop to reduce the amount of memory held, however this can be disabled.
