### ISSUE TITLE
Improve logic and documentation for setting number of reducers in AddElementsFromHdfs

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1490]
There are 3 fields: numReduceTasks, minReduceTasks and maxReduceTasks.

In the accumulo handler it appears to use the numReduceTasks initially to configure the reducer, but then when it configures the partitioner it overrides the value based on the number of splits.

It is confusing and I'm not sure the logic is correct.

**Comment by gaffer01** [comment]
I don't think there's any need for an option to set the number of reducers. It's best to use one reducer for each tablet, and this should be the default. Early versions of Gaffer didn't have the option to set the number of reducers, and this was based on Accumulo's recommended approach.

The times that isn't the best idea are described in the documentation, quoted below. Suggest we remove (or deprecate) the option to set the number of reducers.

If there's believed to be a bug in the logic for using the minimum and maximum numbers, then can this be explained here, as it was tested fairly carefully when it was added.

>By default the number of reducers used in the MapReduce job that converts data into the correct form is the same as the number of tablets. There are at least two scenarios where this is not ideal. First, if a large amount of data is being added into a table with a small number of tablets, then the number of reducers will be too small (i.e. each reducer will have a very large amount of work to do). Second, if a small amount of data is being added into a table with a large number of tablets, then the number of reducers will be too great, and there will be a large amount of unnecessary task creation. There are two options on the AddElementsFromHdfs operation that can be used to set the minimum and maximum number of reducers that are used in the MapReduce job

**Comment by m55624** [comment]
I think there is a bug in the logic of min and max reducers.  If a max is set it will default to using all the max reducers.  If the max and min is set it should surely try and find the correct number of reducers (based on the tablets) and then correct itself based on the min/max set, not just default to using as many as possible up to the max.  This could end up not being efficient, adding a small amount of data with a large maximum, a large amount of unnecessary task creation.

**Comment by m55624** [comment]
# Migration Steps

There is no breaking change and no immediate migration required, however setting the specific number of reduce tasks in an addElementsToHdfs Job has been reduced, and we recommend you set the min and/or max number of reduce tasks instead.  This will allow Accumulo to choose the right number of reducers for the task.

**Comment by p013570** [comment]
Merged into develop.
