### ISSUE TITLE
Parquet Store generates too many files for HDFS to handle when importing RDD 

### ISSUE THREAD

**Issue by ac74475** [gchq/Gaffer#1493]
The is an issue where importing an RDD with lots of partitions and wanting to split the data into lots of files per group, will worst case cause 
<number of partitions> x <number of files per group> x <number of groups> files to be generated which HDFS will struggle to handle.

**Comment by gaffer01** [comment]
This bug was fixed during the major rewrite of the Parquet store in #1884 .
