### ISSUE TITLE
Add debug operation option to print full stack trace to user

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1501]
it would be useful to re-run the a operations after a failure with option debug set to true to provide a user with in-depth knowledge of what failed, instead of append error messages together and passing upwards to give the user something useful.

**Comment by p013570** [comment]
Where should the option go? 

If a user executes an operation chain containing multiple operations, the option should only be required in one place, perhaps on the OperationChain object. 

If a user executes a single operation, then the option would have to go on that single operation. 

So basically it just needs to go on the outermost operation. Would that be obvious enough for a user?

**Comment by m607123** [comment]
Could potentially just be an Entry in the options Map that all Operations have - I don't know how that map is propagated in an OperationChain if at all, could add some functionality to check the OperationChain and all its' operations for a "debug" option in their maps?

**Comment by p013570** [comment]
@m607123 yeah I suppose we could just scan all operations and see if any of operation has the debug option set.

**Comment by p013570** [comment]
I've been looking into this and as we already have the gaffer.error-mode.debug property that can enable/disable debugging. If a system admin wants to allow users of Gaffer to view full stack traces of the exceptions then they should enable the debug property. I don't think users then need to worry about disabling/enable debug for specific queries.
