### ISSUE TITLE
Investigate other graph analytics

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1508]
What other graph analytic should we expose as Gaffer operations?

The outcome of this issue should be to create other GitHub issues relating to the chosen operations we want to create.

**Comment by t616178** [comment]
Here's a quick list of some of the analytics which are available via the Spark Graphframes/GraphX APIs (which might be easy to implement via our ```GetGraphFrameOfElements``` operation):

**Graphframes**

* Connected components
* Strongly connected components
* Label propagation (neighbourhood detection)
* Triangle count

**GraphX**

* Degree counting

**GraphX (via Sparkling Graph)**

* Closeness centrality
* Eigenvector centrality
* HITS
* Degree centrality
* Neighborhood Connectivity
* Vertex Embeddedness
* Local Clustering Coefficient
* Freeman’s network centrality
* Modularity
* Adamic/Adar
* Common Neighbours
* Link prediction
