### ISSUE TITLE
Clicking explore button in Swagger UI causes the static banner to be added again

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1518]
To test this you can add the following system properties to the road-traffic-demo pom:
```xml
<gaffer.properties.app.banner.description>DEMO</gaffer.properties.app.banner.description>
<gaffer.properties.app.banner.colour>#1b75bb</gaffer.properties.app.banner.colour>
```

Then when you start the road traffic demo you will see the banner is added at the top. If you then click the 'Explore' button, the banner is duplicated.

**Comment by t616178** [comment]
Merged into develop.
