### ISSUE TITLE
AddElementsFromHdfs deduplicates Elements that have aggregation disabled and identical keys

### ISSUE THREAD

**Issue by supamanda** [gchq/Gaffer#1527]
Hi again,

I'm still looking at the netflow data I've mentioned in other questions. I specified in the schema that Netflow edges are not to be aggregated and each edge represents a single netflow event in the original csv with probably different properties.

When I use the startTime property as the timestamp (I have to nano precision, but storing at millis), only one record is stored in accumulo even if I have >1 record with the same source+destination+timestamp. I've also tried using the default timestamp and this is resulting in more missing records. I've checked the element generator, and all the elements are being generated correctly.

Here is some example records from the CTU13 dataset (previously mentioned) that demonstrates the problem.
These two records have the same source (::) and destination (ff02::1:ff97:a3eb), and the timestamps both map to 2011/08/12 15:59:53.173 (converted to a long), and only the first one was in accumulo
```
[2011/08/12 15:59:53.173326,0.0,ipv6-icmp,::,130,   ->,ff02::1:ff97:a3eb,null,MRQ,0,null,1,86,86,flow=Background]
[2011/08/12 15:59:53.173341,90.500267,ipv6-icmp,::,135,   ->,ff02::1:ff97:a3eb,null,NNS,0,null,6,468,468,flow=Background]
```
These two records have the same source (::) and destination (ff02::1:ff9d:312f), and the timestamps map to different values: 2011/08/12 16:09:48.275 and 2011/08/12 16:09:48.276, and both records are in accumulo
```
[2011/08/12 16:09:48.275895,0.500047,ipv6-icmp,::,135,   ->,ff02::1:ff9d:312f,null,NNS,0,null,2,156,156,flow=Background]
[2011/08/12 16:09:48.276904,0.0,ipv6-icmp,::,130,   ->,ff02::1:ff9d:312f,null,MRQ,0,null,1,86,86,flow=Background]
```

Do you have any suggestions about how I can change my config / ingest to ensure that all my events are stored separately?

Thanks,
Amanda

**Comment by gaffer01** [comment]
The `timestamp` isn't necessary. Specifying the timestamp as the startTime causes the same records to be deduped in Accumulo as you found. We'd recommend not using the timestamp (using it in situations where it is safe to do so might cause very minor performance benefits).

If by "default timestamp" you mean not specifying the timestamp field then that is odd, as that should work. The following code shows how the same edge will appear multiple times in the data if no aggregation is specified:

    Schema schema = new Schema.Builder()
                .type("timestamp", new TypeDefinition.Builder()
                        .clazz(Long.class)
                        .build())
                .type("string", new TypeDefinition.Builder()
                        .clazz(String.class)
                        .build())
                .type("boolean", Boolean.class)
                .edge("EDGE", new SchemaEdgeDefinition.Builder()
                        .source("string")
                        .destination("string")
                        .directed("boolean")
                        .property("p", "timestamp")
                        .aggregate(false)
                    .build())
                .build();

        AccumuloProperties properties = new AccumuloProperties();
        properties.setStoreClass(SingleUseMockAccumuloStore.class.getName());

        Graph graph = new Graph.Builder()
                .config(new GraphConfig.Builder().graphId("test").build())
                .addSchema(schema)
                .storeProperties(properties)
                .build();
        Edge edge = new Edge.Builder()
                .source("A")
                .dest("B")
                .group("EDGE")
                .property("p", 1L)
                .build();

        List<Element> elementList = new ArrayList<Element>();
        elementList.add(edge);
        elementList.add(edge);

        AddElements add = new AddElements.Builder().input(elementList).build();

        graph.execute(add, new User());

        GetAllElements g = new GetAllElements.Builder().build();
        CloseableIterable<? extends Element> res = graph.execute(g, new User());
        for (Element e : res) {
            System.out.println(e);
        }

This returns:

    Edge[source=A,destination=B,directed=false,group=EDGE,properties=Properties[p=<java.lang.Long>1]]
    Edge[source=A,destination=B,directed=false,group=EDGE,properties=Properties[p=<java.lang.Long>1]]

Can you share your schema?

**Comment by supamanda** [comment]
Yep, by default timestamp I meant leaving the timestampProperty out of the schema. 

I've been getting these results with bulk ingest - do you think that is what's affecting it?

Here is the original schema and generator [schema_and_generator.zip](https://github.com/gchq/Gaffer/files/1486012/schema_and_generator.zip)

**Comment by p013570** [comment]
Hi @supamanda,

Thanks for pointing this out. I've just been investigating it and I believe we have a problem with AddElementsFromHdfs for elements with aggregation disabled.

The AddElementsFromHdfs triggers a MapReduce job and it looks like it will deduplicate elements that have an identical Key (Same source, destination, direction, group, groupBy properties).

To work around this issue I think you have the following options:
- add a unique property to the groupBy. If you were to add something like a random number or the timestamp (assuming it is unique but I suppose that is not guaranteed) then the Key would be different and the MapReduce job wouldn't deduplicate them.
- enabling aggregation for that group and defining aggregators for the properties.
- don't use AddElementsFromHdfs - instead just add the data via one of the other mechanisms, like AddElements or AddElementsFromKafka.

I haven't looked into a fix yet. When we have an idea of the complexity I will update you with a timescale.

**Comment by p013570** [comment]
@gaffer01 - I'm tempted to just disable the Reduce part of the MapReduce operation if the schema contains groups with aggregation disabled. This would mean Accumulo would have to do more work in its compactions to aggregate the data. I can't really come up with any other way. Does that seem acceptable to you?

**Comment by p013570** [comment]
OK, looks like the fix is going to be quite straight forward. I'm just testing it now. 
I'm aiming to release a patch by the end of Wednesday.

**Comment by supamanda** [comment]
Great! Thank you :)

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
Hi @supamanda,

This has now been fixed and released in version 1.1.1. Thanks again for spotting the issue and sorry for the hassle. Please let us know how you get on with it in version 1.1.1.

**Comment by supamanda** [comment]
Hi @p013570 

No worries :)

I've been experimenting with the same data, and still having a problem. The discrepancy is smaller now but it is inconsistent between ingests. My counts by protocol are below: the first and second ingests were both done with gaffer v1.1.1. 

Protocol type | Expected ingest count | First ingest count | Second ingest count 
------|------|------|------
 arp| 10545|10545|10545
 esp| 47|47|47
 gre| 4|4|4
 icmp| 516603|516603|516603
 igmp| 38709|38709|38709
 ipnip| 1|1|1
 ipv6| 216|216|216
ipv6-icmp| 1120|1120|1120
 ipx/spx| 267|267|267
 llc| 7|7|7
 pim| 140|140|140
 rarp| 19|19|19
 rsvp| 7|7|7
 rtcp| 22208|22208|22208
 rtp| 27652|27652|27652
 **tcp**| 4442479**|**4442478**|**4442473**
 **udp**|**29316444**|**29316420**|**29316421**
 udt| 115|115|115
 unas| 16|16|16

I identified 2 missing records from the first ingest:
The first is a tcp event which should generate one Netflow edge with our schema
```
2011/08/11` 11:35:45.617342,248.283707,tcp,147.32.84.59,49403, ->,74.125.232.200,80,SRPA_FSPA,0,0,22,5643,1098,flow=Background-Established-cmpgw-CVUT
```
The second was a udp event which should generate 2 Netflow edges with our schema, but only stored the flipped dest-> src edge
```
2011/08/14 03:45:37.194900,0.000221,udp,147.32.85.34,63301,  <->,147.32.80.9,53,CON,0,0,2,326,86,flow=To-Background-UDP-CVUT-DNS-Server
```

I'm still looking into whether I can find some pattern behind why certain events are missing, but wondering if you might have any insight?

**Comment by gaffer01** [comment]
Which version of Accumulo are you using? Some versions of Accumulo have a bug where bulk imports can lose data.

**Comment by supamanda** [comment]
We've got accumulo v1.7.3 - I just had a look through the release notes and the silent data loss fix went in 1.6.4 and 1.7.1 so I'm guessing this version should be ok - or maybe there's still a problem no one else has picked up yet...? I'll keep looking and see about upgrading to 1.8.1. If you've got any more ideas please let me know :)

**Comment by p013570** [comment]
OK. If it is not too much effort, it would definitely be worth upgrading to 1.8.1 - there are some significant performance improvements for ingest and Gaffer is now built against 1.8.1. The update won't cause any problems for your existing data in Accumulo.

**Comment by gaffer01** [comment]
Where are you getting the ingest counts from? From running a `GetAllElements` and counting, or from the Accumulo web page, or via a Spark job?

**Comment by supamanda** [comment]
I got the counts in a few different ways (to sanity check):

- I introduced a Protocol entity with vertex set to the protocol type and an aggregated count property, and then created one for each Netflow edge
- I wrote a Gaffer operation called CountByProtocol (based on CountGroups) that I used to pulled out the protocol from the Netflow edge
- I used spark to read in all of the Netflow edges, grouped by protocol and then counted
- I used spark to read in all of the NetflowCount edges, grouped by protocol and summed on count
- I used spark to read in the original csv, added a column setting the count to 1 if it's a unidirectional row and 2 if it's bi-directional, and grouped by protocol and then summed on my new column

I can give you pieces of my code if that would help?

I don't have a straight forward script to identify exactly which records are missing in each run - I ran many spark commands to iteratively reduce the set of records I was looking at by comparing counts by protocol type, state, label, duration, src/dest port (though you need to massage the original data a bit to orient the records and duplicate the records correctly to match what is expected in Gaffer). I have kept the history of at least one of my spark sessions which I could clean up and share as well if that would also be helpful?
