### ISSUE TITLE
Create a NamedViews cache similar to NamedOperations 

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1544]
The logic should be very similar to NamedOperations, but the cache should be able to handle adding and retrieving a NamedView. The cache should also be able to return all the NamedViews available.

NamedViews do not need to be locked down to user roles. It should be assumed that all users are allowed to access all NamedViews.

Subtask of #1542.

**Comment by m55624** [comment]
Merged into parent branch #1542.
