### ISSUE TITLE
Improve error messages in Proxy Store

### ISSUE THREAD

**Issue by devx36** [gchq/Gaffer#1559]
Currently, when the result limit is hit in the proxy store an exception is thrown which has the entire response in the message detail. Could this instead contain only the detail of the underlying exception

**Comment by p013570** [comment]
Currently the ProxyStore generates new exceptions with complex error messages. If the delegate REST server returns a Gaffer Error object as a response, we should just deserialise it and use the contents of that in the Proxy Store exception.

**Comment by p013570** [comment]
Merged into develop.
