### ISSUE TITLE
Improve the Swagger documentation

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#1570]
Currently the Swagger documentation is incomplete. Given the extent to which the generated swagger.json file is used throughout the project documentation (as the main graphical entry point to the REST API and as part of the Gaffer documentation), this should be improved.

This will involve editing the interface classes in the core-rest project and adding more documentation using the Swagger annotations.

**Comment by t616178** [comment]
Here's a (non-exhaustive) list of some documentation improvements which could be made:

* More information in the description fields for each service method
* More top-level API information (via the @Info and @SwaggerDefinition annotations in the SwaggerDefinitionConfigV2 interface)
* Fuller descriptions of parameters using the @ApiParam annotation
* Addition of @ApiModel annotations to key data objects
* Documentation of the Gaffer extension header via the @Extension annotation

**Comment by p013570** [comment]
Merged into develop.
