### ISSUE TITLE
Create Functions to extract Elements from Walks

### ISSUE THREAD

**Issue by m607123** [gchq/Gaffer#1573]
The current implementation of the Walk class only allows for trivial extraction of nested Iterables of Edges, however new functionality will also require the extraction of Entities as well, which is not possible in this fashion.
These new functions, ExtractWalkEdges & ExtractWalkEntities, would allow the symmetric extraction of both Edges and Entities, implementing the IterableFunction class from the Koryphe library.

**Comment by p013570** [comment]
Merged into develop.
