### ISSUE TITLE
Should we deprecate/remove the ability to set timestampProperty in the Schema

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1576]
This ability is causing a lot of problems in Accumulo and HBase. Should we remove it?

**Comment by gaffer01** [comment]
I don't know why the Schema allows a timestampProperty to be set. It can't be taken advantage of using any of the query APIs (unlike say the visibility property which is a key part of queries). If it can be specified then it should be a store property - a store could for some reason require some particular value to be provided when ingesting and could offer options for getting that from a property, or specifying a random generator.

So vote we deprecate the timestampProperty in the schema.

**Comment by p013570** [comment]
Just been looking into moving it into a store property. It does cause the Accumulo key packages to become a bit untidy. They now need to know about the schema and this new timestamp property. Also,  any classes that serialise/deserialise the key packages also need to know about this new property.

I think the timestamp property should still be part of the schema, as it is applicable to a given schema. If we put it in the store properties then those properties are tied to the schema and they should be independent.

Perhaps we create a new config field in the Schema. This could be useful in other ways for other stores too. This config field would allow advanced users to set the timestampProperty for use in Accumulo/HBase. I've created a pull request to demonstrate this.

**Comment by gaffer01** [comment]
If the timestamp becomes part of the store properties then that ties them to a schema, if it specifies that the timestamp should be set to a property (it could specify a class to be used to generate the timestamp, e.g. randomly, in which case it wouldn't be tied to a schema).

If the property goes in a config option in the schema, then that ties the schema to a particular store type.

Either option has problems. But the config option may be best.

**Comment by p013570** [comment]
Agreed. We have a nice modular schema approach where you can split your schema up into small modules. Elements and types are the normal 2. But we suggest you can split out aggregation if you want to apply the schema to a  2 stores, one that supports aggregation and one that doesn't. Similarly you could split out the config into a separate schema that you use only when running on Accumulo.

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
# Migration Steps
No migrations steps required, however the "timestampProperty" field in the schema has been deprecated.  In Gaffer version 2.0 this will likely be removed.

Instead of setting the timestampProperty you will need to add a config setting to the schema. We do not recommend using this, it is an advanced feature. However, if you have existing data then you must continue using this feature and will need to migrate to using the Schema config instead. For example, if you previously had a schema like:

```json
{
    "timestampProperty": "time"
}
```

this should be replaced with:

```json
{
    "config": {
        "timestampProperty": "time"
    }
}
```
