### ISSUE TITLE
Accumulo query time aggregation may aggregate non-aggregated groups

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1577]
If your schema contains a mixture of aggregated and non-aggregated groups, Accumulo will apply query time aggregation to all groups.

**Comment by gaffer01** [comment]
Are there any situations in which you might want to apply query time aggregation to a group which is marked as not requiring ingest aggregation? The schema still requires aggregators to be provided for all properties, which is strange if properties in non-aggregation groups can't be aggregated.

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
@gaffer01 - actually properties within groups that have aggregation disabled do not need to have aggregators defined.

So if you tried to apply query aggregation to a non-aggregated group there may not be any aggregators defined. So currently if you disable aggregation for a group it is completely disabled, both ingest and query. 

You could use the [Aggregate](https://gchq.github.io/gaffer-doc/getting-started/operations/aggregate.html) operation in a chain to apply aggregation separately and when you run that operation you can specify aggregate functions to use for the different properties. This aggregation would normally just be done on a single node in a single jvm.
