### ISSUE TITLE
AddElementsFromHdfs Reducer doesn't aggregate elements in HBase

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1581]
The reducer is configured to use the HBase key, which includes the timestamp. As the timestamp is set to the current time in milliseconds (or a random number after #1565), no elements will have the same key and therefore no aggregation will occur. This will put a lot of load on HBase to aggregate the elements and causes a lot of unnecessary data to be passed around.

**Comment by n3101** [comment]
HBase is no longer supported.
