### ISSUE TITLE
NPE in AccumuloStoreRelation

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1605]
The following code in the `buildScan(final String[] requiredColumns, final Filter[] filters)` method in `AccumuloStoreRelation` can throw a `NullPointerException`:

    Output<RDD<Element>> operation =
        new FiltersToOperationConverter(view, store.getSchema(), filters).getOperation();
    operation.setOptions(options);

The `getOperation` method on `FiltersToOperationConverter` can return null if it identifies that the filters it is passed will always result in no results. This can be seen by running `df.filter("group = 'abc'")` where `abc` is not a group in the schema and `df` is a DataFrame obtained by running the `GetDataFrameOfElements` method. To fix this the `operation.setOptions(options)` call should be moved to after the null check and a unit test added to check that an empty DataFrame is returned when the above filter is applied.

**Comment by t616178** [comment]
Merged into develop.
