### ISSUE TITLE
AddElementsFromHdfsHandler updates the splitsFilePath whether supplied or not

### ISSUE THREAD

**Issue by m55624** [gchq/Gaffer#1622]
Currently in the AddElementsFromHdfsHandler.doOperation method the the splitsFilePath is updated to use the workingPath whether the splitsFilePath is already provided or not.

This causes a FileNotFound exception when the operation is run.

There should be a simple null check to check if the splitsFilePath is already supplied, and if so, don't update it.

**Comment by t616178** [comment]
Merged into develop.
