### ISSUE TITLE
Register existing ScoreResolvers by default

### ISSUE THREAD

**Issue by m607123** [gchq/Gaffer#1672]
As new operations are being added which require implementations of ScoreResolver, the system should be redesigned to make it easier to configure.

Existing ScoreResolvers should be registered by default, and the ScoreOperationChainHandler should automatically find the necessary resolver from this registration (probably just a Map of ScoreResolver to class).

In future, if a new ScoreResolver is added to Gaffer, this should also be added to the default ScoreResolvers, while still allowing external Resolvers to be configured via a json file.

**Comment by t616178** [comment]
Merged into develop
