### ISSUE TITLE
Should we attempt to make Gaffer a more general purpose framework?

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1687]
Gaffer offers a lot more than just a graph database, you get quite a lot of functionality out of the box and on the other hand a lot of normal graph operations are not included (shortest path, page rank, etc.). It is likely that someone may want to use some of Gaffer's functionality without wanted to store their data in a graph format. Currently you can actually use Gaffer without any Edges, i.e just rows in a table, indexed by a single id (the vertex), but this isn’t very obvious.

Here are some of Gaffer's features that could be reused independent of it being a graph database:
- NamedOperations (and NamedViews)
- Job Tracker (basic implementation)
- Operations and handlers
- Pluggable components
- Aggregation/summarisation
- Age off/continuous validation
- Graph hooks
- REST API
- UI
- Python shell

When you start using Gaffer a lot of the above features are optional and can be independently enabled/disabled, so I don’t think we necessarily need to split these components up any further. 

If someone wants to use Gaffer purely for the operation/handler api then we/they could implement a new Store that does not implement Get/Add and just register any custom operations and handlers - perhaps we should actually create a store for this purpose now?

I guess what we could do is remove/decouple any references to ‘graph' in our core libraries. This would involve things like:
- Rename Graph to GafferConnector
- Rename GraphHooks to Hooks
- Rename GraphLibrary to GafferLibrary
- In the UI we could easily hide the Graph view if there are no Edges in the schema. Leaving just the query builder and table view.
- Regarding the Schema, we have a couple of options (similarly with Views)
  - Just leave it as it is, but highlight that Edges aren’t required (likewise Entities aren’t required). 
  - Remove Edges from the Schema and create a GraphSchema that extends Schema and adds Edges.
  - Try to make the Element class more generic so it has a list of IDs. Entities would then just have a single vertex ID and Edges would have source, destination and directed IDs.

**Comment by n3101** [comment]
An interesting hypothesis, but there will probably never be enough effort available to attempt this.
