### ISSUE TITLE
Scoring a complex nested operations may return the wrong score

### ISSUE THREAD

**Issue by m607123** [gchq/Gaffer#1690]
Currently the DefaultScoreResolver does not handle nested operations, ie implementations of the Operations interface. 

This is okay in most cases as the ScoreOperationChainHandler does recursively score nested operations. But if custom ScoreResolvers are included that delegate a nested operation to the DefaultScoreResolver, then these nested operations will not be scored individually.

Therefore the logic in ScoreOperationChainHandler should be moved to DefaultScoreResolver to fully handle nested operations. We also need to be careful to prevent infinite recursion.

**Comment by p013570** [comment]
Merged into develop.
