### ISSUE TITLE
Expose the input type of named operations

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#1721]
For standard operations, you can use the GetSerialisedFields endpoint to get the input type of the operation. However for Named operations it is more difficult: you have to get the operation chain, extract the first operation, then look it up. It would be useful for the UI to have this information available to it in the named operation detail so the extra call wouldn't have to be made.

Something like if the first operation is: 

GetElementsInRanges: {"input": "uk.gov.gchq.gaffer.commonutil.pair.Pair<uk.gov.gchq.gaffer.data.element.id.ElementId, uk.gov.gchq.gaffer.data.element.id.ElementId>"}
GetElements: {"input": "uk.gov.gchq.gaffer.data.element.id.ElementId"}
GetElementsWithinSet: {"input": "uk.gov.gchq.gaffer.data.element.id.EntityId"}
GetAdjacentIds: {"input": "uk.gov.gchq.gaffer.data.element.id.ElementId"}
GetElementsBetweenSets: {"input": "uk.gov.gchq.gaffer.data.element.id.EntityId", "inputB": "uk.gov.gchq.gaffer.data.element.id.EntityId"}

**Comment by p013570** [comment]
Work has been started on branch gh-1721-named-op-input-type, however I think we may want the input type information to be part of the NamedOperationDetail object.

**Comment by p013570** [comment]
Merged into develop.
