### ISSUE TITLE
Queries on an Accumulo Store may skip over data that has the same vertex/source/dest and timestamp

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1737]
There is a 'limitation' in Accumulo where you can't have 'many' rows with the same Key. When you scan over the rows, the scanner reads the data in batches. After the first batch Accumulo tries to work out where to restart the scan and will skip over rows that have a key equal to one already read. To fix this we will set the timestamp to a random number for non aggregated groups. Aggregated elements work already as the elements with the same key are aggregated together, so there are never duplicate rows with the same key.

**Comment by p013570** [comment]
The AccumuloStoreConstants.DEFAULT_TIMESTAMP constant has been deleted. If you have not configured the timestamp value then it will now be set to a random number (previously it was set to 1).

This will mean if you are using AddElementsFromHdfs and not setting a timestamp then the Reducer will not reduce anything. A separate issue will fix this later.

**Comment by gaffer01** [comment]
Merged into develop.

**Comment by gaffer01** [comment]
Merged into develop.
