### ISSUE TITLE
in*Range predicate with RBMBackedTimestampSet property

### ISSUE THREAD

**Issue by gregmolchany** [gchq/Gaffer#1748]
My schema has an element with a property "time" that is specified as a RBMBackedTImestampSet. I would like to perform a postAggregationFilterFunction that selects all elements with a "time" in a certain range. I'm using the REST v2 interface to gaffer and I've specified the selection as:

"postAggregationFilterFunctions": [
              {
                "predicate": {
                  "start": {
                    "java.time.Instant": 0
                  }, 
                  "end": {
                    "java.time.Instant": 1522122840
                  }, 
                  "class": "uk.gov.gchq.koryphe.impl.predicate.range.InRange"
                }, 
                "selection": [
                  "time"
                ]
              }

This results in:

<Response [400]>
org.apache.accumulo.core.client.impl.AccumuloServerException: Error on server xx.xx.xx.xx:yyyy

How do I go about doing this selection? 

Also allowing the inDateRange() or inTImeRange() predicates would be most helpful.

**Comment by p013570** [comment]
Hi @gregm-tnw,

The InRange predicate only works on Comparables. So unfortunately you can't apply the InRange predicate directly on RBMBackedTimestampSet. We/You would need to create a specific predicate that behaves like InTimeRange but checks if any of the timestamps within RBMBackedTimestampSet are within the provided range.

**Comment by gregm-tnw** [comment]
Thanks for the clarification, the Swagger ineterface reports that InRange was a valid predicate for RBMBackedTimestampSet which is what led to my confusion. As RBMBackedTimestampSet is part of the time library adding support for the time based predicates/transforms/functions would be good for consistency.

**Comment by gaffer01** [comment]
Just to note that:

- Yes, an in range predicate would be useful for the timestamp sets
- But these could have various meanings, e.g. at least one of the timestamps is in the range, or all of the timestamps are in the range. We'd need to allow the predicate to be configured with these different meanings.

**Comment by d47853** [comment]
Merged into develop
