### ISSUE TITLE
Allow users to configure which walks are returned in a GetWalks operation

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1754]
Currently GetWalks only returns full walks. In some cases users may also want to return partial walks.
For example if you do 4 hops you may want to return an walks that are length 3 or length 4.

In this case:
1 - 2 - 3 - 4
1 - 5 - 6
We should not return the walk 1 - 2 - 3 as we will return the length 4 walk instead.

To achieve this we should add a new field to the GetWalks operation. This field should allow users to configure the types of Walks that are returned. Perhaps this field could be an object that contains a transform Operation and a Predicate, similar to the Conditional object used in If and While. We would need to pass test Walk objects to the transform/predicate so that we can test whether or not we return it. 

By default we should continue to only return full walks.

**Comment by n3101** [comment]
@m29827 What is the status of this issue please?

**Comment by t92549** [comment]
I believe this issue can be closed due to #2372
