### ISSUE TITLE
Add Summary annotations to all Operations/Functions/Predicates/BinaryOperators

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1767]
This Koryphe issue with add a new Summary annotation: https://github.com/gchq/koryphe/issues/96
This should be added to all Operations/Functions/Predicates/BinaryOperators. It will be useful in the UI.

**Comment by m55624** [comment]
This has been completed, waiting for Koryphe version update.

**Comment by p013570** [comment]
Merged into develop.
