### ISSUE TITLE
Add summary field to OperationDetail

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1769]
Add a new 'summary' field to OperationDetail. This can be added using the new Summary annotation added in #1767.

**Comment by m55624** [comment]
This has been completed, waiting for Koryphe version update.

**Comment by p013570** [comment]
# Migration Steps
A new field 'summary' has been added to OperationDetail. If you consume the JSON results from the /graph/operations/{className} endpoint you may need to update your code to work with the extra field.

**Comment by p013570** [comment]
Merged into develop.
