### ISSUE TITLE
Multi serialiser 

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1771]
All vertex's (source, dest, vertex) within a schema need to use the same serialiser. 
This doesn't appear very flexible without either writing a custom serialiser or switching to generic string serialiser.

**Comment by gaffer01** [comment]
In an undirected edge between a string and an int, there's no guarantee that say the source will always be the string, and the destination will always be the int. They may be flipped around based on their order.

How will we know which serialiser to use for the source?

**Comment by GCHQDeveloper404** [comment]
The byte[] has the first byte as the key to which serialiser to use.

**Comment by GCHQDeveloper404** [comment]
https://github.com/gchq/Gaffer/blob/gh-1771-multiSerialiser/core/serialisation/src/main/java/uk/gov/gchq/gaffer/serialisation/implementation/MultiSerialiser.java

javadoc I hope explains enough.

**Comment by p013570** [comment]
Merged into develop.
