### ISSUE TITLE
Add a version property to the REST service

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1780]
It would be useful if users could find out what version a Gaffer REST server was running. We could add this as a system property that is exposed via the /properties endpoint. This could also be shown in the footer in the swagger UI.

**Comment by m55624** [comment]
After discussion, we are going to expose the Koryphe and Gaffer versions through the /properties endpoint.  The Gaffer version will be visible in the footer in the Swagger UI but the Koryphe version will only be available through the /properties endpoint.  This will allow users to see what methods are/aren't available to them through their versions.

**Comment by p013570** [comment]
Merged into develop.
