### ISSUE TITLE
Directed field should be an enum

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1795]
The directed field for an edge group in the schema is currently specified using a type, e.g. type="aBoolean", class="Boolean", validation="isTrue". There are a couple of problems with this: it's unnecessarily complicated; if no validation is specified it doesn't let us determine if the edges in that group are always directed, always undirected, or both.

We could deprecate specifying this by a type, and instead use an enum: all edges in this group are directed, all edges in this group are undirected, edges in this group may be directed or undirected.

**Comment by n3101** [comment]
Ok when asked @gaffer01 said "I think given how long it's been, it's probably not worth worrying about. The original motivation I think was that it seemed unnecessarily complicated to have to specify a type. The idea of the 3 way enum was that you might want to say that a graph only has directed edges, or only has undirected edges, or has a mixture of directed and undirected edges. The "not all edges are directed" does cover options 2 and 3 but the idea was that having 3 options lets the user specify what they intend more accurately, and conceivably in future we could use that more detailed knowledge to optimise the storage."

When asked @d21211122 said: "I guess I'm not seeing a big enough benefit to justify the risk, but I'm open to being swayed if anyone feels strongly enough about it?" 

No advocates, so we'll drop this one.
