### ISSUE TITLE
Deprecate the seedMatching option on Operations

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1798]
The seed matching option allows users to define whether they want Edges/Entities that are 'equal to' or 'related to' their seeds. 

For Entity Seeds, the matching types determines whether to return just the Entities at the given vertices or also return any Edges that are linked to a vertex.

For Edge Seeds, the matching types determines whether to return just the Edges that have the same src/dest/direction as the Edge seed or also return the Entities either end of the edge seeds.

So effectively the matching type allows you to limit whether Entities and/or Edges are returned. This can and probably should just be done using the View. We should deprecate this flag and remove it in version 2.0 as it will simplify for user queries and also the logic for any new store implementations.

**Comment by m55624** [comment]
Migration Notes

The default for seedMatching is RELATED so if that is currently used nothing will need to change.  There is one limitation however, if you have a seedMatching = EQUAL and specify both Edges and Entities that will have to now be done under 2 Operations in a chain as there can only be one View applied globally to all input.

As seedMatching is now deprecated to write an equivalent Operation for Edges it should now be written as below:

OLD:
```
{
   "class": "uk.gov.gchq.gaffer.operation.impl.get.GetElements",
    "seedMatching": "EQUAL",
      "input": [
      {
         "class": "uk.gov.gchq.gaffer.operation.data.EdgeSeed",
         "source": “source1“,
         "destination": “dest1“,
         "directed": "true"
      }
   ]
}
```

NEW:
```
{
   "class": "uk.gov.gchq.gaffer.operation.impl.get.GetElements”,
      "input": [
      {
         "class": "uk.gov.gchq.gaffer.operation.data.EdgeSeed",
         "source": “source1“,
         "destination": “dest1”,
         "directed": "true"
      }
   ],
   "view" : {
    "edges": {
      “group1“:{}
    }
  }
}
```

For entities it should now be written:

OLD:
```
{
   "class": "uk.gov.gchq.gaffer.operation.impl.get.GetElements",
    "seedMatching": "EQUAL",
      "input": [
      {
         "class": "uk.gov.gchq.gaffer.operation.data.EntitySeed",
         "vertex": “vertex1”
      }
   ]
}
```

NEW:
```
{
  "class" : "uk.gov.gchq.gaffer.operation.impl.get.GetElements",
  "input" : [ {
    "class" : "uk.gov.gchq.gaffer.operation.data.EntitySeed",
    "vertex" : “vertex1”
  } ],
  "view" : {
    "entities": {
      “group1“: {}
    }
  }
}
```

**Comment by p013570** [comment]
Merged into develop.
