### ISSUE TITLE
Cannot easily create HyperLogLogPlus sketches in JSON

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#18]
The JSON deserialiser for the HyperLogLogPlus sketch doesn't handle null or empty objects and simply throws an IllegalArgumentException. We should update this to create an empty HyperLogLogPlus sketch to allow objects to be created in JSON.

Currently to create a HyperLogLogPlus object in JSON you have to specify the bytes. We should also update the serialisation and deserialisation methods to allow you to set all parameters in the HyperLogLogPlus object in JSON.

**Comment by p013570** [comment]
I'm going to close this as it is unlikely we will ever change the serialisation. Instead of trying to create a HyperLogLogPlus object in json you should consider writing the logic in Java and using an ElementGenerator or ObjectGenerator operation.

**Comment by p013570** [comment]
It is actually quite simple to allow new HyperLogLogPlus objects to be created from son, by adding optional 'p', 'sp' and 'offers' fields. For example you could create a new HyperLogLogPlus object by doing:
```json
{
  "p": 30, 
  "sp": 30, 
  "offers": ["value1", "value2", "value3"]
}
```

**Comment by gaffer01** [comment]
Merged into develop.
