### ISSUE TITLE
Create ability to include all groups for Entities/Edges in a View

### ISSUE THREAD

**Issue by m55624** [gchq/Gaffer#1800]
Currently if you have a view, for example:
``"view" : {
    "edges": {
      "group1": {},
      "group2": {}
    }
}``

you must specify all groups you want to return within the view.  The feature of allowing all groups to be included should be added, something like:

``"view" : {
    "edges": {
      "allGroups": "true"
    }
}``

This will become very useful when seedMatching has been deprecated (https://github.com/gchq/Gaffer/issues/1798) for seedMatching EQUALS.

**Comment by p013570** [comment]
Merged into develop.
