### ISSUE TITLE
Possible bug in AccumuloKeyRangePartitioner

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1803]
The `getSplits` method in `AccumuloKeyRangePartitioner` gets the splits from Accumulo and then stores them in an array of Strings. The line

    splits.parallelStream().map(Text::toString).collect(Collectors.toList()).toArray(arr)

uses `parallelStream` which means that possibly the results won't be in the same order as the input. It's essential that they are sorted as `Arrays.binarySearch` is called on the result which requires that the array is sorted.

Related to this, the line

    final Collection<Text> splits = connector.tableOperations().listSplits(table);

shows that the result of `listSplits` is a `Collection`. In practice this is probably always returned sorted, but the signature (and Javadoc) does not guarantee that. It may be safer to explicitly sort the `splits`.

**Comment by p013570** [comment]
Merged into develop.
