### ISSUE TITLE
Tidy up module names

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#182]
There are now a lot of top level modules. It would be clearer to move some of these into parent modules such as:
- core
- rest-api
- store-implementation
  - accumulo-store
  - array-list-store
- integration-test
- library
  - function-library
  - operation-library
  - serialiser-library
- example
  - example-graph
  - example-rest

this should be done after gh-172.

**Comment by p013570** [comment]
This should also fix gh-172.

**Comment by p013570** [comment]
Merged into develop.

**Comment by ak8532110** [comment]
in merge, some files from "example" (now "example-graph") and gaffer-integration-tests (now "integration-test") did not get moved. Issue reopened to resolve this.

**Comment by t616178** [comment]
Merged into develop

**Comment by p013570** [comment]
# Migration steps

The example module has been renamed to example-graph
