### ISSUE TITLE
The equals methods in TypeSubTypeValue and TypeValue classes should treat empty and null strings the same

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1821]
The serialisers for TypeSubTypeValue and TypeValue treat empty strings as null values. This isn't ideal, but we are stuck with this for now as we don't want to introduce a breaking change.

This means if you query for TypeSubTypeValue("", "", X), then you will get back TypeSubTypeValue(null, null, X). In order to make this easier to process we should update the equals and hash code methods so they treat empty strings as nulls.

Due to this current bug, using TypeSubTypeValue("", "", X) as a seed in a GetWalks operation will fail.

**Comment by m55624** [comment]
Merged into Develop.
