### ISSUE TITLE
Unable to federate over 2 graphs that have different visibility properties

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1834]
If you create 2 graphs in the FederatedStore with different visibility property names ("visibility1" and "visibility2") then you cannot run a single operation over both graphs at the same time.

This is because, in order to federated over the 2 graphs at the same time, we need to be able to merge the schemas together. But, because the visibilityProperty value is different the schemas cannot be merged together.

A workaround is to run 2 separate queries and merge the results, GetElements on graph1 and then GetElements on graph2. This way the queries are done separately and the schemas don't need to be merged together. It isn't very pretty but currently it is the only way of doing it. For example:

```
GetElements(options:{graphId: graph1})
ExportToSet
GetElements(options:{graphId: graph2})
ExportToSet
DiscardOutput
GetSetExport
```

**Comment by n3101** [comment]
It is possible that the forthcoming merging of the FedStore rewrite will fix this. As part of the alpha3 work, test this bug again after the merge has been done. 

If still there schedule it for alpha5 (post maestro merge).

**Comment by t92549** [comment]
It was found that this does now work with federated stores, and a series of tests have been written to demonstrate doing this and better explain the side effects

**Comment by n3101** [comment]
@t92549 "and better explain the side effects"

Please contribute something to new docs for this as well.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2818

To be added in docs: https://github.com/gchq/gaffer-doc/issues/319
