### ISSUE TITLE
Create new ForEach Operation

### ISSUE THREAD

**Issue by d21211122** [gchq/Gaffer#1845]
It would be useful if there was an operation that could execute a nested operation for each item in an iterable input, this would enable us to execute complex chains such as enrichment of inputs based on the result of a different query.

So given input [1, 2, 3, 4, 5], ForEach(GetElements) would query a graph for seed [1], then [2], etc. until all inputs have been processed.

Most operations accept iterable inputs, so this would likely be dependent on the creation of an operation that can wrap an object in a singleton list. See #1846 .

**Comment by p013570** [comment]
Merged into develop
