### ISSUE TITLE
Create SingletonList Operation

### ISSUE THREAD

**Issue by d21211122** [gchq/Gaffer#1846]
Sometimes it is useful to be able to chain operations that produce a single output with operations that expect an iterable input (Selecting the first element from an ordered list, and then using it to seed a subsequent query, for example). Creating a 'SingletonList' operation that wraps an input object in a list and presents it to the next operation would enable this.

**Comment by m55624** [comment]
Can the current ToList operation not just be used for this?

**Comment by p013570** [comment]
Merged into develop.

**Comment by m55624** [comment]
Reopened for missing handler

**Comment by p013570** [comment]
Merged fixes into develop.
