### ISSUE TITLE
Create Join Operation

### ISSUE THREAD

**Issue by d21211122** [gchq/Gaffer#1847]
Being able to join iterables together as part of an OperationChain would enable interesting use cases, such as forming connections between entities that both have an edge to a common vertex. A Join operation, with the standard operation input as the left hand side, and a nested Operation that resolves the right (this could be another GetElements operation or a GetExport, for example) would allow us to achieve this.
The Operation would need to know how to join the left and right, so we could specify a 'leftKey' and 'rightKey' Function that would enable us to group the 2 sides, along with a 2 input 'joinFunction' that will merge the inputs from the left and right sides.

**Comment by m55624** [comment]
Some thought has been put into this about what will be returned when.  Using examples with a simple POJO, it is possible to see what is expected.

INPUTS:
Left: ```[new TestPojo(1, 3), new TestPojo(2, 4), new TestPojo(2, 4), new TestPojo(3, 5), new TestPojo(4, 6)]```
Right: ```[new TestPojo(2, 4), new TestPojo(4, 6), new TestPojo(4, 11), new TestPojo(6, 8), new TestPojo(8, 10)]```

JOINS:
InnerJoinFromLeft matching only on field 1:```[{TestPojo(2, 4)=[TestPojo(2, 4)]}, {TestPojo(2, 4)=[TestPojo(2, 4)]},{TestPojo(4, 6)=[TestPojo(4, 6),TestPojo(4, 11)]}]```
InnerJoinFromRight matching only on field 1:```[{TestPojo(2, 4)=[TestPojo(2, 4),TestPojo(2, 4)]},{TestPojo(4, 6)=[TestPojo(4, 6)]},{TestPojo(4, 11)=[TestPojo(4, 6)]}]```
FullOuterJoin matching fully:```[{TestPojo(1, 3)=[]},{TestPojo(3, 5)=[]},{TestPojo(6, 8)=[]},{TestPojo(8, 10)=[]},{TestPojo(4, 11)=[]}}]```
LeftOuterJoin matching fully:```[{TestPojo(1, 3)=[]},{TestPojo(3, 5)=[]}]```
RightOuterJoin matching fully:```[{TestPojo(4, 11)=[]},{TestPojo(6, 8)=[]},{TestPojo(8, 10)=[]}]```
LeftInnerJoin matching fully:```[{TestPojo(1, 3)=[]},{TestPojo(2, 4)=[TestPojo(2, 4)]},{TestPojo(2, 4)=[TestPojo(2, 4)]},{TestPojo(3, 5)=[]},{TestPojo(4, 6)=[TestPojo(4, 6)]}]```
RightInnerJoin matching fully:```[{TestPojo(2, 4)=[TestPojo(2, 4),TestPojo(2, 4)]},{TestPojo(4, 6)=[TestPojo(4, 6)]},{TestPojo(4, 11)=[]},{TestPojo(6, 8)=[]},{TestPojo(8, 10)=[]}]```

**Comment by gaffer01** [comment]
Should this be about joining iterables (which are possibly unlimited) or about lists? If it's about joining iterables then you need standard streaming functionality such as windowing functions to deal with the possibly unlimited stream of data. I assume that's not going to be implemented. If we're going to read all the data in before outputting any results then I'd prefer to make that clear from the signature of the operation and force the user to turn the inputs into fully in-memory data sets before trying to join them.

**Comment by d47853** [comment]
Merged into develop
