### ISSUE TITLE
Build fails if code is in a directory whose name has a space in it

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1855]
To reproduce:

- mkdir "/tmp/a b" && cd "/tmp/a b"
- git clone https://github.com/gchq/Gaffer
- cd Gaffer
- mvn clean test

This produces the error `java.io.FileNotFoundException:/tmp/a%20b/Gaffer/core/serialisation/target/testclasses/multiSerialiser.json (No such file or directory)` at `uk.gov.gchq.gaffer.serialisation.implementation.MultiSerialiserTest.shouldMatchHistoricalSerialisation(MultiSerialiserTest.java:74)`.

**Comment by p013570** [comment]
Merged into develop.
