### ISSUE TITLE
Create a Reduce operation

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1859]
The Reduce operation should reduce an iterable into a single value. For example to be able to sum together an iterable of integers. We should be able to use our existing library of BinaryOperators (aggregate functions) with the Reduce opreration.

e.g.

```java
public class Reduce<T> implements InputOutput<Iterable<T>, T>, MultiInput<T> {
    private BinaryOperation<T> aggregateFunction;
}
```

**Comment by lucean** [comment]
I'll pick this up if that's ok?

**Comment by p013570** [comment]
@lucean - sorry just seen your message. Yes, feel free to pick anything up that isn't assigned to someone - just add a comment to say you are working on it.

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
Merged into develop
