### ISSUE TITLE
Create SetVariable, GetVariable and GetVariables Operations

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1860]
These operations would behave similarly to how you might use ExportToSet("A") and GetSetExport("A").

The operations should use a new 'variables' Map field within the Context object.

The SetVariable operation should take an input and a variable name and set the input on the variables map in the Context. It should not have an output.

The GetVariable operation should take a variable name and fetch it from the variables map in the Context. It should not take an input.

The GetVariables operation should allow a user to provide a list of variable names and a map of variable name to value is returned.

**Comment by m55624** [comment]
Merged into Develop.
