### ISSUE TITLE
Create CSV Element Generator Functions

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1867]
Create a CsvElementGenerator that takes a CSV and generate Edges and Entities to allow CSVs to be easily ingested into Gaffer.

This could also be exposed as an Operation so it could be used within the Federated Store.

**Comment by p013570** [comment]
I've just had a look at the state of the branch gh-1867-csv-element-generator-2b. I've tidied up a few bits and it looks like the work is almost complete. I think it might just need some tests writing for it.

**Comment by p013570** [comment]
After further discussion it would actually be better to split this generator up into 4 parts.
CSV -> Tuples
Tuples -> Tuples   (manipulate the fields)
Tuples -> Elements
Elements -> Elements + Cardinality Entities

These could all be functions and used in a Map operation.

**Comment by p013570** [comment]
This is now on branch gh-1867-csv-element-generator-2c.

**Comment by n3101** [comment]
@GCHQDeveloper404 has identified that private copies of unmerged functions in this issue are in use. We need to decide whether these functions belong in Gaffer or Koryphe and merge them as appropriate.

**Comment by n3101** [comment]
@GCHQDev404 Ok, @d21211122 says these functions appear to belong in Gaffer rather than Koryphe, so we'll merge them here. Does this just need a PR, or is there more work needed?

**Comment by t92549** [comment]
Title changed to reflect the fact that the `gh-1867-csv-element-generator-2c` branch only contains the Functions needed for the `CsvElementGenerator`, but the generator itself and operation live on a different branch
