### ISSUE TITLE
Can we simplify the View and Schema builders?

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#188]

**Comment by t616178** [comment]
Would a change from this:

<pre><code>
Schema.Builder()
                .type(TestTypes.ID_STRING, new TypeDefinition.Builder()
                        .clazz(String.class)
                        .build())
                .build();
</pre></code>

to

<pre><code>
Schema.Builder()
                .type(TestTypes.ID_STRING)
                        .clazz(String.class)
                        .build()
                .build();
</pre></code>

be seen as an improvement?

I have a pattern which can be used to hide the explicit creation of the Builders for components in the parent Builder, but this might come with difficulties when trying to indent the relevant pieces of the chained method calls.

**Comment by p013570** [comment]
Automatic indenting in an IDE would cause problems with this as it would end up looking like:

```java
Schema.Builder()
      .type(TestTypes.ID_STRING)
      .clazz(String.class)
      .build()
      .build();
```

and I think that is actually more confusing.

**Comment by p013570** [comment]
Closing as I don't think there is currently a way we can simplify them with the current model.
