### ISSUE TITLE
Refactor Accumulo Store code and package structure

### ISSUE THREAD

**Issue by a09631** [gchq/Gaffer#190]
Refactor some of the Accumulo Store code, and update the package structure to be more descriptive.

**Comment by p013570** [comment]
@a09631 as this is nearly a year old it would be good to progress this issue. We don't really want to start refactoring too much of the accumulo store as we will end up breaking some of the complex key package logic. Perhaps we could break this issue into smaller issues that target specific bits of the code.

**Comment by GCHQDeveloper404** [comment]
Removing myself from the assignee, this is an ongoing ticket which I have done some work with. 
To echo @p013570 " Perhaps we could break this issue into smaller issues that target specific bits of the code."

**Comment by t616178** [comment]
Closing for now as the Accumulo store has been tidied up enough. If there are any further issues with the Accumulo store these should be raised under a new ticket.
