### ISSUE TITLE
Optimise QueryGenerator in Parquet store

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1906]
The `QueryGenerator` class in the Parquet store can be optimised so that if a directed edge is specified as a seed then the reverse edge directory is not searched in.

Also the predicate for an edge seed causes unnecessary logic, e.g. if edge seed is 1-100, if 1 in partition 1 and 100 in partition 100 then predicate is 1 or 100 for partition 1, and similarly for partition 100 (see comments at the end of `testQueryGeneratorForGetElementsWithEdgeSeeds` in `QueryGeneratorTest`).

**Comment by n3101** [comment]
We are not supporting parquet in v2.0, so this will not be done.
