### ISSUE TITLE
Optimise SortFullGroup in ParquetStore by using repartitionByRange

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1916]
Spark 2.3 introduced a `repartitionByRange` option on dataframes. This could be used to improve the efficiency of `SortFullGroup` in the Parquet store (possibly avoiding the need to use RDDs, which could significantly improve the efficiency).

This requires #1902 to be merged first.

**Comment by n3101** [comment]
We are not supporting parquet in v2.0, so this will not be done.
