### ISSUE TITLE
ImportRDDOfElements on Parquet store fails when used on a HDFS cluster

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#1921]
The `ImportRDDOfElements` operation on the Parquet store passes all the unit tests which run on a local file system but fails when run on HDFS running on a cluster. The line

    fs.rename(new Path(tempDir + "/AddElementsFromRDDTemp/sorted_aggregated_new/"), new Path(newDataDir));

in `AddElementsFromRDD` fails to move the directory as intended (the sorted_aggregated_new directory is moved into the new directory). This means that the group directories cannot be found when the partition is calculated.

**Comment by d47853** [comment]
Merged into develop
