### ISSUE TITLE
Creation of Gaffer Docker files

### ISSUE THREAD

**Issue by ng12developer** [gchq/Gaffer#193]
A Docker version of Gaffer.

**Comment by p013570** [comment]
Nearly done - just need to update the docker documentation and create some basic scripts to make building and running the containers easier.

**Comment by p013570** [comment]
Some of the docker files still need improving but that will be done separately. Also we need to create a docker image for the rest api - this will be done in issue gh-261

**Comment by p013570** [comment]
Merged into master in gaffer-docker repository.
