### ISSUE TITLE
ProxyStore with no coreOpHandlers

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1939]
An AbstractStore should be the parent of Store but no coreOpHandlers.
All concrete stores extend Store with coreOpHandlers.
ProxyStore extends AbstractStore with no coreOpHandlers.

------------------
### Update

Abstract store has been removed in favour of a constructor options for adding coreOpHandlers. 
This will be false for ProxyStore, It was voted undesirable changing the names of the class store needed to extend or changing the names for the class operations would need to interact with.

**Comment by GCHQDeveloper404** [comment]
An AbstractStore should be the parent of Store but have not handlers.
All concrete stores extend Store with core handlers.
ProxyStore extends AbstractStore with not handlers.

**Comment by m55624** [comment]
A better way to do this would just add an extra initialise method to the Store to take a boolean to add the core opHandlers.  By default we leave this to true, but then within the ProxyStore you just call initialise with false and the store will not add any core handlers.  This will be a lot smaller and easier change.

**Comment by GCHQDev404** [comment]
awaiting gh-1980

**Comment by d47853** [comment]
Merged into develop
