### ISSUE TITLE
RDF model support ?

### ISSUE THREAD

**Issue by maximveksler** [gchq/Gaffer#1944]
Does Gaffer plans to support the RDF eco system? 

Mainly 

- SPARQL 
- SHACL / OWL
- https://www.w3.org/TR/ldp/ ?

**Comment by m316257** [comment]
Thanks for the question. 

Gaffer is really designed for very large property graphs where the properties need to be summarised. 

A while ago we did experiment with RDF, SPARQL, OWL and Gaffer and concluded that it is possible. 

However, we don't have any plans in the near term to add or support this functionality ourselves. 

But of course we would be interested if you were thinking of experimenting with this and we are always open to contributions.

**Comment by maximveksler** [comment]
@m316257 thanks.

I know there is of an open source 3rd party that seem to have integrated support https://github.com/cybermaggedon/gaffer-tools#redland-rdf-and-sparql

I wonder if there are known production deployments of the integration that are known to GCHQ / community ?

**Comment by gaffer01** [comment]
We don't have any information about that code.

**Comment by m316257** [comment]
@maximveksler Sorry - we aren't aware of any production deployments of Gaffer/RDF/Sparql integrations.

**Comment by m55624** [comment]
I am going to close this discussion.
