### ISSUE TITLE
Swagger UI doesn't work when REST API is served from /

### ISSUE THREAD

**Issue by ctas582** [gchq/Gaffer#1945]
I'm running the REST API on Tomcat and it's configured to be served from the root i.e. there's no path prefix. I've set the `gaffer.rest-api.basePath` system property to `""`, however the following code forces the URLs that Swagger uses to be prefixed with `//v2/` which causes 404 errors.

https://github.com/gchq/Gaffer/blob/b892624ccf99d501f381d6df5c4efc415902b7f1/rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/application/ApplicationConfigV2.java#L52-L55

Maybe add a length check too? i.e. `basePath.length() > 0 && !basePath.startsWith("/")`

**Comment by d47853** [comment]
Merged into develop
