### ISSUE TITLE
Merging ProxyStore into FederatedStore

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#1991]
The Federated Store opChainHandler delegates operations changes to sub/remote graphs and aggregates the remote graphs output.
The Proxy Store opChainHandler delegates the operations to local handlers and remote graphs (see gh-1952).

By merging the opChainHandlers and stores, the ProxyStore become a FederatedStore with a single remote graph.

**Comment by d21211122** [comment]
Is this now superseded by #2088 ?

**Comment by GCHQDev404** [comment]
focus for maestro
