### ISSUE TITLE
Refactor ITs to reuse Graphs

### ISSUE THREAD

**Issue by m55624** [gchq/Gaffer#1994]
Currently this can't be done because we will need to clear the graph each time it is used for a new Test, or rewrite the test to all use the same data.

**Comment by m55624** [comment]
Related to #1836

**Comment by n3101** [comment]
Is this something that is either covered by, or made irrelevant by, the current IT rework? Or is this something else?

**Comment by d47853** [comment]
I don't think it's required for the linked issue so I'm happy to close it as something we wont do until a need arises for it.
