### ISSUE TITLE
Include io.github.classgraph in Accumulo iterator JAR

### ISSUE THREAD

**Issue by ctas582** [gchq/Gaffer#1995]
gchq/koryphe#124 switched a dependency from `io.github.lukehutch:fast-classpath-scanner` to `io.github.classgraph:classgraph` in Korphe v1.6.0-RC1.

This dependency needs including/replacing in the Accumulo iterator JAR to fix NoClassDefFound errors we are seeing in gchq/gaffer-tools#645

**Comment by d47853** [comment]
Merged into develop
