### ISSUE TITLE
Implement Equals method for all ToByteSerialisers

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2027]
Implement Equals method for all ToByteSerialisers.
```
@Override
    public boolean equals(final Object obj) {
        return this == obj || obj != null && this.getClass() == obj.getClass();
    }
```

gh-2030 This is required to remove the JSONserialiser from CustomMap.equals().

Get the test "shouldHaveValidEqualsMethodForToByteSerialiser()" to pass for all serialiser tests.
This will also require hashCode implementations to pass find bugs + check style.

Pull the existing branch.

**Comment by GCHQDev404** [comment]
> If somebody assigns this to me I'd love to tackle this bug.

ticket is yours.

**Comment by GCHQDev404** [comment]
@EmekeN The ticket is yours to complete. I can't assign the ticket to you via GitHub. We need to make changes to our GitHub settings.

**Comment by EmekeN** [comment]
I'm having issues testing w/ Maven but I'll still submit a PR

**Comment by c015dariu** [comment]
Is this issue still being worked on? If not, I can happily finish it off.

**Comment by m55624** [comment]
@EmekeN This has now been passed on as we would like this in the next release. @c015dariu.

**Comment by d47853** [comment]
Merged into develop
