### ISSUE TITLE
ProxyStore method signature change not backwards compatible

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#2037]
The method `getRemoteTraits()` previously `fetchTraits()` should be reverted to the old name in time for the next release.

**Comment by GCHQDev404** [comment]
`getRemoteSupportedOperations()` previously  `fetchOperations()`
`getRemoteSchema()` previously `fetchSchema()`

**Comment by sartkap** [comment]
I am interested in fixing this bug. Could you point out where the changes have to be made?

**Comment by d47853** [comment]
Sure, this is the file that needs reverting: https://github.com/gchq/Gaffer/blob/master/store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/ProxyStore.java

**Comment by d47853** [comment]
Merged into develop
