### ISSUE TITLE
ViewValidator with static methods

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2047]
ViewValidator probably could change to use static methods.

### Caution
There is FederatedViewValidator which changes/overrides the behaviour of how view validation is applied.

**Comment by d47853** [comment]
From a first glance I think we can label it as such for now. If a beginner is struggling, they can tell us and we can take it on ourselves.

**Comment by c015dariu** [comment]
Hey I've tried to take a stab at this issue myself but I'm getting nullpointers when running OperationChainValidatorTests, whenever it tries to run validateOperationChain using any(Set.class) it always puts in a null to the method, this only happens when it's made static and I can't seem to figure out why.

**Comment by GCHQ-83497** [comment]
@c015dariu It looks like OperationChainValidator uses a ViewValidator.  If we are making that static, I don't think we should be passing that through.

**Comment by c015dariu** [comment]
If you mean via the constructor I fully agree, I have tried removing all references to instanced View Validators and replaced with static calls (and also leaving them and testing that), however my concern is towards the test which utilises Mockito to test the method parameters. I believe Mockito has issues testing static methods as, despite having no change other than now being static (which I've tried calling via instance or via class), it causes mockito to change its behaviour and fail the test. I would replace that line with a test which similarly covers that behaviour but unfortunately I don't fully understand what it does yet.

Line in question:
`given(ViewValidator.validate(any(View.class), any(Schema.class), anySet())).willReturn(new ValidationResult());`

**Comment by GCHQ-83497** [comment]
Yeah I meant the constructor. In response to your concern, using given is attempting to mock the response of validate() so that it returns a new ValidationResult() every time it is called - we shouldn't be mocking statics.

**Comment by c015dariu** [comment]
My current PR is failing on a test that hid from me before committing which is being evasive but after alot of digging around I'm starting to see the issue with having FederatedViewValidator not able to override ViewValidator (thanks to being static), which means the correct ViewValidator is not being used for Federated requests. A quick fix would have been to check the instance of store or the operation chain when passing into OperationChainValidator to identify federated chains/store and then using the appropriate Validator however to access either of these classes requires dependency on Federated-Store which in turn causes a cyclic dependency loop.

I'm running into a brick wall with my understanding of the Gaffer code, is there a better way or place to make this check/fix?
