### ISSUE TITLE
Investigate multiple Store Properties classes

### ISSUE THREAD

**Issue by m55624** [gchq/Gaffer#2061]
There are so many different different Store Properties, ProxyProperties, MapStoreProperties etc.

These are getting confusing and make things like a Federated/Proxy store difficult to use.  They only really contain some specifics for the Stores and maybe some helper getter/setters for properties.

This should be investigated and made so there is just a single StoreProperties class that is used for all.  This may involve using a single util class for the helper getter/setters.

Based on implementation this could be a breaking change, so V2 milestone has been set.

**Comment by benj-fletch** [comment]
Hi, I'd like to work on this ticket if possible?

If that's ok, just to confirm, you are wanting each of the inheritors of StoreProperties to be removed in favour of a single class, to be replaced with:
- A utils class for the getters/setters 
- A generic collection of K:V pairs for specific store implementations
- Potentially a Store.validate() method to ensure required entries are present?

**Comment by m55624** [comment]
Hi @benj-fletch.  What we are looking to do it remove the Store specific StoreProperties class in favour of one single class, as you said.  StoreProperties should not really change.  A StorePropertiesUtil class should also be added to the store package, which will contain the Strings for properties out of the StoreProperties class and any 'top level' helper methods.  Each Store implementation will now have their own implementation of StorePropertiesUtil class, and then can just use a StoreProperties.

Package structure will look something like this:
STORE PACKAGE
StoreProperties.java (containing just map)
StorePropertiesUtil.java (containing 'top level' constants and their helpers)
OTHER STORE IMPLEMENTATION PACKAGES
OtherStorePropertiesUtil.java (extends StorePropertiesUtil and adds their own store specific constants and helpers)

**Comment by benj-fletch** [comment]
Thanks @m55624 I will have a go at doing that.
One question - is there a reason we use a delegate Properties object in StoreProperties instead of extending Properties directly?
If it's not a problem I'd like to change StoreProperties to extend Properties to take advantage of all the code already there (e.g load(), getProperty() and an already delegated Properties object)

**Comment by m55624** [comment]
Hi @benj-fletch, no I dont think there is any reason we don't extend that, sounds like a good idea.  Thanks!

**Comment by m55624** [comment]
Hi @benj-fletch, is this still being worked on? Looks like it is pretty much there, but if possible could you open a PR as soon as possible, it would be something we would really like to get in.  Thanks!

**Comment by benj-fletch** [comment]
Hi @m55624 - I have made the changes I think are needed but a bunch of the unit tests are failing and I haven't had time to get around and fix them all yet! I can raise a PR on what I have if that's useful though?

**Comment by m55624** [comment]
@benj-fletch, if you could that would be really useful, don't worry if you haven't got time to fix them, I will get round to doing them asap, just like to get your changes in! Cheers

**Comment by benj-fletch** [comment]
@m55624 I have created a PR [here.](https://github.com/gchq/Gaffer/pull/2135). I am happy to make changes that you observe!

**Comment by m55624** [comment]
As this is a breaking change to Gaffer, the code will be migrated to Maestro.

**Comment by m55624** [comment]
Done in Maestro, ticket ref https://github.com/gchq/Maestro/issues/14
