### ISSUE TITLE
Add Edge Validation warning for directed field

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#2066]
Validation should be added to directed fields in schemas. This will be done as part of work for version 2 as adding in validation would cause breaking changes.

**Comment by n288TJYRX** [comment]
What is this blocked by? Is it okay to go ahead and work on?

**Comment by n288TJYRX** [comment]
Theres a method validateDirection() in SchemaElementDefinitionValidator.java that is never used and is commented out. This is within the develop branch already, so it looks like its already been merged. Shall I uncomment it and create a unit test for it?

**Comment by m55624** [comment]
So I wrote this method and added it in, however the reason this ticket is blocked and it is commented out is that it is a breaking change, as for users who have schemas without direction validation currently, it would throw an exception and require direction.  We cannot make breaking changes on minor versions so it will have to wait until V2, however feel free to create a branch and re add this method back in, and add a unit test, and when we get to the point of V2 we can merge it back in.

**Comment by n288TJYRX** [comment]
Ready for pull request once we get to V2

**Comment by n3101** [comment]
A conversation elsewhere:
n3101: "- do you agree with @d47853's assertion:  "Validation should be added to directed fields in schemas. "
@d21211122:  "I don't know if I do agree with the assertion. I can see why it might be a good thing to do, but has anyone ever had a problem with it? If it's easy to merge and we can write a doc about it, then maybe it's not worth worrying about... we can just do it."
n3101: "I would have thought that it should be possible to make it conditional - add a toggle or something so users can turn this on if they want to; or have the software check for itself whether validation is present. or something ??"

**Comment by lb324567** [comment]
Needs investigation to see if the work has been done, if it needs to be merged in, and if the benefit is worth it.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2888
