### ISSUE TITLE
Add options to ParameterDetails

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#2072]
It can be useful to have a set of options to choose from when configuring a named operation. This would allow the UI to provide a drop down list to choose from.

**Comment by g609bmsma** [comment]
Hello, if possible I'd like to have a go at working on this issue, but I've got a couple of questions for some clarity on the issue. I can't find any class named NamedOperationParameter, so I assume it's adding some sort of options to the LinkedHashMap(?) parameters? Or is this related to the options in the same class? Or is it something else I'm missing entirely?

`public class NamedOperation<I_ITEM, O> implements
        InputOutput<Iterable<? extends I_ITEM>, O>,
        MultiInput<I_ITEM> {
    private Iterable<? extends I_ITEM> input;

    @Required
    private String operationName;
    private LinkedHashMap<String, Object> parameters;
    private Map<String, String> options;
`

**Comment by d47853** [comment]
Sorry, it should be ParameterDetail, not NamedOperationParameter

**Comment by g609bmsma** [comment]
I've added both getOptions and setOptions functions, along with all the relevant appends and builders. All tests in the folder seem to be passing at the moment, need to run through the whole project and see if any of the integration testing or other test issues arise.

**Comment by g609bmsma** [comment]
Run tests through the whole project, no errors, so seems happy. Shall I write a specific ParameterDetailTest where the options functions run as a unit test?

**Comment by g609bmsma** [comment]
Having had more of a look through testing for ParameterDetail, instead of writing a dedicated test, would it be better to expand shouldShallowCloneOperation() in AddNamedOperationTest.java, since it utilises ParameterDetail?

**Comment by GCHQDev404** [comment]
Adding options to the existing `shouldShallowCloneOperation()` will be useful. Please can you also modify`shouldJsonSerialiseAndDeserialise()` in that same test class as well to include your options change.

If you can sufficiently test your new code in `AddNamedOperationTest.java` without clogging it up. I think that will be fine, but having a new separate ParameterDetailTest wouldn't hurt.

**Comment by g609bmsma** [comment]
Ok thanks, managed to figure a separate ParameterDetailTest earlier, but I'll have another crack at adding options to `shouldJsonSerialiseAndDeserialise()` and `shouldJsonSerialiseAndDeserialise()` in `AddNamedOperationTest.java`

**Comment by g609bmsma** [comment]
In addition to `ParameterDetailTest.java` I've managed to get `shouldShallowCloneOperation()` working in `AddNamedOperationTest.java` as well. However, haven't been able to get `shouldJsonSerialiseAndDeserialise()` to work, as it seems adding the parameters in the same was as in `shouldShallowCloneOperation()` then causes an error when it comes to serialising it as JSON. Anyone got any tips? I've added the current (failing) version of the test below

`public void shouldJsonSerialiseAndDeserialise() {
        Map<String, ParameterDetail> parameters = new HashMap<>();
        parameters.put("testParameter", mock(ParameterDetail.class));
        parameters.put("optionTestParameter", mock(ParameterDetail.class));

        final AddNamedOperation obj = new AddNamedOperation.Builder()
                .operationChain(OPERATION_CHAIN)
                .description("Test Named Operation")
                .name("Test")
                .parameters(parameters)
                .overwrite()
                .readAccessRoles(USER)
                .writeAccessRoles(USER)
                .score(0)
                .build();

        // When
        final byte[] json = toJson(obj);
        final AddNamedOperation deserialisedObj = fromJson(json);

        // Then
        JsonAssert.assertEquals(String.format("{%n" +
                "  \"class\" : \"uk.gov.gchq.gaffer.named.operation.AddNamedOperation\",%n" +
                "  \"operationName\": \"Test\",%n" +
                "  \"description\": \"Test Named Operation\",%n" +
                "  \"readAccessRoles\": [\"User\"],%n" +
                "  \"writeAccessRoles\": [\"User\"],%n" +
                "  \"score\": 0,%n" +
                "  \"overwriteFlag\": true,%n" +
                "  \"operationChain\": {" +
                "  \"operations\": [{\"class\": \"uk.gov.gchq.gaffer.operation.impl.get.GetAdjacentIds\", \"input\": [{\"vertex\": \"seed\", \"class\": \"uk.gov.gchq.gaffer.operation.data.EntitySeed\"}]}]}" +
                "}"), new String(json));
        assertNotNull(deserialisedObj);
    }`

**Comment by g609bmsma** [comment]
Managed to get `shouldJsonSerialiseAndDeserialise()` to work with ParameterDetails Options

**Comment by m55624** [comment]
Merged into develop.
