### ISSUE TITLE
Remove print test from FederatedStoreTest

### ISSUE THREAD

**Issue by m55624** [gchq/Gaffer#2075]
A test was added in error in ticket gh-1771 and not picked up in the PR.

FederatedStoreTest.shouldUseMulti() needs removing.

**Comment by SupreethBaliga** [comment]
Hi. I would like to take this up. Can you give me info about the file and other related stuff? Thanks.

**Comment by GCHQ-9182621** [comment]
Hi
Sure, thanks. The file is mentioned above (FederatedStoreTest) and the method name is shouldUseMulti().
Let us know if you have any further questions.

**Comment by Sand038** [comment]
Is this issue fixed yet? Otherwise I would like to take this

**Comment by GCHQDev404** [comment]
@Sand038 sorry it has been assigned.

**Comment by d47853** [comment]
Merged into develop
