### ISSUE TITLE
Configurable Store with default Handlers

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2088]
supersedes gh-2028.

Store changes from a Interface to Class.
Store methods like getTraits GetSchema get outsourced to Handlers.
There is will be logic for handling operations or default operations for handling unknown operations.
In simplest form the default handler will throw an UnhandledOperation Exception.

ProxyStore becomes a configured implementation of Store with core behaviour of "forward everything to remote store" becomes a configured default handler.

FederatedStore default behaviour finds the first store to support the operation. Federated Operations require some form of merging responses and will require a handler to do so.

**Comment by gaffer01** [comment]
Added vote-required label to indicate this will need at least 2 committers to review.

**Comment by m55624** [comment]
Being completed in Maestro.

**Comment by GCHQDev404** [comment]
focus for Maestro
