### ISSUE TITLE
Deployment to remote maven repository

### ISSUE THREAD

**Issue by flitte** [gchq/Gaffer#209]
Hi all,

I'm experimenting with some interaction tools which sit on top of Gaffer and would find it useful if the Gaffer artifacts were hosted in a public repository somewhere for easier dependency resolution with Maven.

Is this planned any time soon?

**Comment by p013570** [comment]
Yes, this is something we want to do in the future, but at the moment we don't have a good estimate of when it will be set up.

**Comment by p013570** [comment]
Needs to be done after gh-434

**Comment by t616178** [comment]
This is covered by gh-545.
