### ISSUE TITLE
Operations within AddNamedOperation are not validated by OperationAuthoriser

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#2090]
AddNamedOperation does not implement Operations, so the OperationAuthoriser does not inspect the nested Operations. This allows someone to add an Operation they wouldn't normally be able to run into a NamedOperation and then run it via the NamedOperation.

This only becomes an issue if you choose to define the graph hooks in the order:
- OperationAuthoriser
- NamedOperationResolver

By default the NamedOperationResolver is added first like:
- NamedOperationResolver
- OperationAuthoriser
In this case the the operations within a NamedOperation are all validated correctly.

**Comment by p013570** [comment]
I have done some of the changes required on branch: gh-2090-add-named-op-authorisation.

However, this does not protect against the case where a user defines a parameter to be an entire operation. e.g:
[
GetElements,
"${OPERATION}"
]

In this case any operation could be added at runtime.

**Comment by d21211122** [comment]
We should open another issue to cover the parameter substitution bug. Updating AddNamedOperation to use the Operations interface should be sufficient for this one.

**Comment by n288TJYRX** [comment]
Think I can do this

**Comment by p013570** [comment]
Pretty much. It might just need some more unit testing to check it all works properly.

**Comment by n288TJYRX** [comment]
I created a few unit tests but got this error when I ran them

Error:java: Annotation processing is not supported for module cycles. Please ensure that all modules from cycle [store,operation,graph] are excluded from annotation processing

If I go to IntelliJ preferences -> Build, Execution, Deployment -> Compiler -> Annotation Processors -> Select all the maven folders and then uncheck "Enable Annotation Processing" the tests then pass. I'm assuming this is just related to my IntelliJ settings then?

**Comment by n288TJYRX** [comment]
There are already a couple of unit tests for checking authorisation of the operations in the operation chain. To test more combinations, I need to know what operations each authorisation level allows. Where can I find this info?

**Comment by d21211122** [comment]
The operation authorisations are determined at deployment time based on the system administrator's configuration. There isn't a fixed configuration that can be tested, so OperationAuthorisorTest specifies it's own authorisations for the tests (opAuthorisor.json from the resources directory). If you want to test other combinations, you could create different versions of this file for different tests.

**Comment by m55624** [comment]
Merged into develop.
