### ISSUE TITLE
NamedOperation parameter substitution allows execution of unauthorised Operations

### ISSUE THREAD

**Issue by d21211122** [gchq/Gaffer#2091]
See comment on #2090 - Whilst that issue fixes the addition of new named operations, there is a related issue where it is possible to substitute an operation using named operation parameters when executed the NamedOperation. Any operation that is substituted in this way is not subject to the authorisations check.

This could be resolved by having NamedOperation also implement the Operations interface (similar to the fix for #2090), and have the getOperations() method return any parameters that are instances of Operation. This way, the auth checking would be applied to any operations supplied by a user as a parameter.

**Comment by n288TJYRX** [comment]
I'll try this

**Comment by d21211122** [comment]
We may want to consider operation chain scoring as well - see NamedOperationScoreResolver. Currently this looks up the named operation in the cache and returns the score associated with it. This should be updated so that any Operation returned by getOperations() is also considered and added to the score.

**Comment by n288TJYRX** [comment]
How do operation scores work? From my understanding the score is the authorisation level required to run an operation. A user needs an authorisation level equal to or greater than that of the operation? So when you say "added to the score" I need to set the score to the highest of all the operations?

**Comment by m55624** [comment]
Merged into develop.
