### ISSUE TITLE
GetVariable and SetVariable operations don't work properly with FederatedStore

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#2100]
The GetVariable and SetVariable operations don't work properly with FederatedStore. This is due to the federated store performing a shallow clone on the user context before sending it to each of the federated graphs. The logic to do the shallow clone does not copy the variables across to the clone.

This is the logic that needs to be updated: https://github.com/gchq/Gaffer/blob/master/core/store/src/main/java/uk/gov/gchq/gaffer/store/Context.java#L62

As a workaround you could execute your operation wrapped inside a FederatedOperationChain.

**Comment by c015dariu** [comment]
Hi, looking into this issue, would this not be as simple as adjusting the constructor to copy over the variables along with the exporters?

I don't believe contexts are ever shallow cloned more than once (or however many sub-graphs in the federation) during their lifetime before they are thrown and new ones created for the next operation chain so I don't think there will be any size issues with this.

**Comment by m55624** [comment]
Hi @c015dariu, yeah this is just as simple as copying the variables over on a shallowClone. Thanks.

**Comment by c015dariu** [comment]
Oops just saw the comment, will work on it now. @m55624 also I can't seem to stop travis builds so it might be worth cancelling my ones.

**Comment by m55624** [comment]
Just FYI this milestone has been update to 1.9 due to an urgent bugfix release for 1.8.1 required and a workaround for this issue makes it less critical.

**Comment by d47853** [comment]
Merged into develop
