### ISSUE TITLE
Join operation does not allow merging of different groups

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#2101]
Currently, the Join operation (with an Element Matcher and Merger) behaves like a schema aggregator. It merges two elements of the same group using the schema and given group by properties. However a typical SQL Join would be able to join rows of different tables.

The best way to change this would be to change how the matcher works, and make the Merger optional. The matcher should take two functions to apply to each of the iterables on the left and output of the right, then compare the results to determine what is a match.

If the matcher returned a Map Tuple containing the key, the left side matches and right side matches, then we could perform a Map operation afterwards to select the relevant properties/elements and manipulate the output.

This could replace the Merger to reduce complexity of the Join operation.

Furthermore, to avoid a performance hit, any Joins which require iterating over both the left and right hand side (Full and Full Outer) will be removed.

**Comment by m55624** [comment]
Merged into develop.

**Comment by d47853** [comment]
## Migration Steps
In version 1.8.1 the Join operation (first released in 1.8.0) was changed. The new operation outputs tuples keyed with 'LEFT' and 'RIGHT'. You can run a map operation over the output to extract a given side and run functions over it. JoinFunctions which required iterating over both sides multiple times were removed for performance reasons.
