### ISSUE TITLE
ParquetStore tests aren't descriptive and contain incorrect logic

### ISSUE THREAD

**Issue by m55624** [gchq/Gaffer#2102]
Some test methods in AbstractOperationsTest class, such as "getElementsWithPostAggregationFilterTest" and "getElementsWithPostTransformFilterTest" have fairly misleading names, and the test logic is not clear, concise, nor does it often directly relate to the test name.

For example, the "getElementsWithPostAggregationFilterTest" could be named "shouldThrowUnsupportedTraitExceptionWithPostAggregationFiltering", which is more descriptive, and specific to the test logic.  This should then assert that the Exception thrown is actually relevant/as expected.  Currently the only assertion is that a StoreException is thrown, containing the phrase "Operation chain".  This will still pass even if other aspects, such as the view are incorrect/invalid.

**Comment by c015dariu** [comment]
I'll take a look and see if I can fix this.

**Comment by gaffer01** [comment]
Can you use this PR as the starting point for these fixes? https://github.com/gchq/Gaffer/pull/2059/files
That will help avoid unnecessary work updating that PR.

**Comment by m55624** [comment]
Merged into develop.
