### ISSUE TITLE
Remove unused properties from ParquetStoreProperties

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#2118]
The following properties in `ParquetStoreProperties` are no longer used and should be removed: `parquet.add_elements.aggregate`, `parquet.add_elements.sort_by_splits`, `parquet.add_elements.split_points.sample_rate`.

**Comment by g609bmsma** [comment]
I've created a branch and had a go at this and think I've got it working right (removed the properties, and then the functions and tests pertaining to them) - should i merge into develop, or wait until the specific develop-1.9.0 branch is created?

**Comment by m55624** [comment]
Merged into develop.
