### ISSUE TITLE
add createInputArray method to Join op

### ISSUE THREAD

**Issue by m55624** [gchq/Gaffer#2119]
When json serialising a Join op, the class in the json is duplicated.  This method needs adding to the Join class to remove this.  an overriding shouldJsonSerialiseAndDeserialise test should be added to JoinTest to confirm this.

```
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "class")
    @Override
    public Object[] createInputArray() {
        return MultiInput.super.createInputArray();
    }
```

**Comment by c015dariu** [comment]
Hi, just taken a look at the code and given a try of writing a test however I don't quite understand what you mean by the class being duplicated. Is this in regards to retaining all the variable values or that the point of the class is the same before/after serialisation?

**Comment by m55624** [comment]
So when the class is json serialised within the input, if you use an entity for example, the Entity class will show 2 times.

**Comment by d47853** [comment]
Merged into develop
