### ISSUE TITLE
OperationAuthoriser does not allow a list of roles to be assigned to an operation

### ISSUE THREAD

**Issue by n3101** [gchq/Gaffer#2130]
I wish the OperationAuthoriser to restrict permission to run an operation to users who are either members of ROLE1 or ROLE2, but not ROLE3. However, if I specify an auth e.g.:
"uk.gov.qchq.gaffer.this.that.theother.myop": ["ROLE1", "ROLE2"] then the Authoriser only allows execution to users who are members of ROLE1 AND ROLE2

**Comment by m55624** [comment]
To be done in Maestro.

**Comment by m55624** [comment]
Done in Maestro, ticket ref https://github.com/gchq/Maestro/issues/16
