### ISSUE TITLE
SchemaElementDefinition is not thread-safe

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#2159]
`SchemaElementDefinition` is not thread-safe. The method `getIngestAggregator` can cause this exception if it is called by two methods at the same time:

    Caused by: java.lang.UnsupportedOperationException: null
	at java.util.Collections$UnmodifiableCollection.add(Collections.java:1055)
	at uk.gov.gchq.gaffer.store.schema.SchemaElementDefinition.addTypeAggregateFunction(SchemaElementDefinition.java:463)
	at uk.gov.gchq.gaffer.store.schema.SchemaElementDefinition.getIngestAggregator(SchemaElementDefinition.java:238)

This seems to the reason the CI tests for the Parquet store fail randomly (see https://github.com/gchq/Gaffer/pull/2147).

The methods `getFullAggregator` and `getQueryAggregator` have the same problem.

This is marked as a bug because the Javadoc does not say that these methods are not thread-safe.

Possible solutions:

- Mark these methods as `synchronized`. This is a simple fix (it solved the problem with the occasional failures in the CI for the Parquet store). This may reduce the performance of this method. We could look for all uses of these methods and ensure that the caller caches the result for re-use.
- Add a comment to the Javadoc for `SchemaElementDefinition` to say that they are not thread-safe, and change the code in the Parquet store that uses them to avoid the synchronisation problem. Downside - in future code we may get errors due to them not being thread-safe.
- Calculate the ingest and full aggregators when the `SchemaElementDefinition` class is created and then just return them. This isn't possible for the query aggregator though as that depends on parameters passed into the method.

**Comment by d47853** [comment]
Merged into develop
