### ISSUE TITLE
GetDataFrameOfElements should handle java.util.Date and java.sql.Timestamp without the user having to specify a coverter

### ISSUE THREAD

**Issue by Raini-zhe** [gchq/Gaffer#2173]
GetDataFrameOfElements can't get the attribute column value with java.util.Date/java.sql.Timestamp to DF column

This is my related configuration：

schema = ...edge("EDGE", new SchemaEdgeDefinition.Builder()
                        .source("Person")
                        .destination("Person")
                        .directed("true")
                        .property("date", "dateTypeName")
                        .property("je", "jeTypeName")
                        .aggregate(false)
                        .build())
                    .type("EDGE", new TypeDefinition.Builder()
                            .clazz(String.class)
                            .build())
                    .type("dateTypeName", new TypeDefinition.Builder()
                            **.clazz(Timestamp.class) // java.util.Date.calss**
                            .build())
                    .type("jeTypeName", new TypeDefinition.Builder()
                            .clazz(Float.class)
                            .build())

Load Data:
          new Edge.Builder()
                        .group(EDGE)
                        .source(cxkh)
                        .dest(dscxkh)
                        .directed(true)
                        **.property("date", date)**
                        .property("je", je)
                        .build()

GetDataFrameOfElements dfOperation = new GetDataFrameOfElements.Builder()
                .view(new View.Builder().edge("EDGE").build()).build();
        Dataset<Row> dataFrame = graph.execute(dfOperation, user);
        dataFrame.show();

**result:**
+------+---+---+--------+-------------+-------------+
| group|src|dst|directed|matchedVertex|  je|
+------+---+---+--------+-------------+-------------+
|EDGE|116|117|    true|         null|9000.0|
|EDGE|116|117|    true|         null|9000.0|
|EDGE|116|117|    true|         null|9000.0|
+------+---+---+--------+-------------+-------------+

**Why not "date" column ？？**

**Comment by gaffer01** [comment]
Thanks for raising the issue.

Some property types can be used within a Dataframe without conversion (e.g. String, Integer, Long, etc) (these ones are identified in the `needsConversion` method at the end of the class `SchemaToStructTypeConverter` https://github.com/gchq/Gaffer/blob/develop/library/spark/spark-library/src/main/java/uk/gov/gchq/gaffer/spark/operation/dataframe/converter/schema/SchemaToStructTypeConverter.java). Some other property types need converting before they can be added to a `Dataframe` - we do this automatically for some properties. If your property is not one of those standard ones then you can write a converter for it (i.e. an implementation of the `Converter` interface in the `uk.gov.gchq.gaffer.spark.operation.dataframe.converter.property` package).

`java.util.Date` and `java.sql.Timestamp` are standard enough that we should handle them automatically (either without converting them if a Dataframe can handle them or by providing a default converter if they need converting).

Are you able to fix this and create a pull request? If not, we can fix it but it will be a few weeks. In the mean time you can write your own converter for those types and pass it into the `GetDataFrameOfElements` operation.

**Comment by Raini-zhe** [comment]
Thank you! I have written my own converter and tested it through.

**Comment by gaffer01** [comment]
Great. I'll update the title of this issue to say we need to handle those 2 properties buy default.
