### ISSUE TITLE
Can you provide some references for receiving different data sources using Flink?

### ISSUE THREAD

**Issue by Raini-zhe** [gchq/Gaffer#2176]

**Comment by gaffer01** [comment]
See the README [here](https://github.com/gchq/Gaffer/tree/develop/library/flink-library) for how to tell the store to use Flink operations and see the unit tests [here](https://github.com/gchq/Gaffer/tree/develop/library/flink-library/src/test/java/uk/gov/gchq/gaffer/flink/integration/operation/handler) for some examples of how to use Flink to add data from files, sockets or Kafka.

But thanks for pointing out that the documentation for this needs improving.
