### ISSUE TITLE
crash: adding None as root child

### ISSUE THREAD

**Issue by masterkeech** [gchq/Gaffer#2177]
The following code snippet will cause Gaffer to crash, this was tested on Centos 7.5 on Gaffer 0.53.4.0

```root.addChild(None)```

**Comment by d47853** [comment]
I think this issue belongs with https://github.com/GafferHQ/gaffer as that version number isn't one of ours.

**Comment by masterkeech** [comment]
oh my, completely wrong gaffer project

apologies, moving it now
