### ISSUE TITLE
Upgrade Accumulo version to 2.x.x

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#2201]
Upgrade version of Accumulo so that we can use the Accumulo Docker container as the baseline for Gaffer containerisation.

There is an accumulo-docker project that works for Accumulo 2.0.0+ which is supported apache accumulo but is not released to Dockerhub
There is a branch of accumulo-docker which supports accumulo 1.9.3+

Upgrading to 1.9.3 is fairly simple but 2.0.0 would need more work as MockAccumulo  is removed in this version. We would need to replace all the MockAccumuloStores from Gaffer should we choose to change this. As this would be a breaking change, it would have to be done in Gaffer 2.x.x

Helpful information available here: https://accumulo.apache.org/docs/2.x/administration/upgrading#upgrading-from-189-to-20

Linked to #2200

**Comment by cybermaggedon** [comment]
I would be willing to work on this, would need some guidance with the code structure. I'm familiar with Accumulo deply, and have Accumulo 2 working in containers which I can push somewhere.

**Comment by d47853** [comment]
Excellent! We recently updated all of our [Docker codebase](https://github.com/gchq/gaffer-docker). We also have an Accumulo (albeit 1.9.3) image that is pushed to docker hub. So we'll update those images when we roll out a version of Gaffer which supports Accumulo 2.x.

**Comment by n3101** [comment]
Accumulo 2.0.0 has critical bugs; 2.0.1 is not a Long Term Maintenance version; there are no other Accumulo 2 versions today. We need to do a Gaffer 2 release this year to support federation. To simplify this process, Accumulo 2 will be left out of the Gaffer 2.0.0 release. We will come back to this later.

**Comment by n3101** [comment]
Ah, no it seems we have to include Accumulo 2 in the Gaffer 2.0.0 release

**Comment by n3101** [comment]
The requirement now is for Gaffer to work with either an Accumulo 1 or an Accumulo 2 backing store. Also, for federation,  a query must be able to federate across a [Gaffer 2.0 + Accumulo 1 instance] and a [Gaffer2.0 + Accumulo 2 instance].

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2679
