### ISSUE TITLE
JSONSerialiser unable handle some primitive data types and throws Unrecognized token error.

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2205]
JSONSerialisation is unable to serialise some primitive types and causes errors.

This can occurring between proxied stores. A store may return a Long value and the receiving store is unable to deserialise correctly.

To replicate the bug.
Examine `IfIT.java` and tests `ShouldReturnOriginalInputWhenConditionIsFalseAndNoOtherwise` and `ShouldReturnOriginalInputWhenConditionIsTrueAndNoThen`. examine lines containing `//This test input has been changed to an integer to avoid triggering a bug JSONSerialisation.`

Change for both test:
`ifOperation.setInput(404);` to `ifOperation.setInput(INPUT_CAMEL_CASE);`
`new IsA("java.lang.String")));` to `new IsA("java.lang.Integer")));`
`assertEquals(404, output);` to `assertEquals(INPUT_CAMEL_CASE, output);`
` assertTrue(output instanceof Integer);` to  `assertTrue(output instanceof String);`

and error will occur when you run the `ProxyStoreITs` (make it easier on yourself add `singleTest(IfIT.class);` to this class temporarily do no push this change.)

This errors with `OperationException: Unrecognized token 'AbCd': was expecting ('true', 'false' or 'null')`

...fix!

**Comment by n3101** [comment]
@GCHQDev404 @d21211122 What should be done about this?
