### ISSUE TITLE
Federation view bug

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2207]
When the Federated graph contains two graphs, one containing a schema with only edges the other with only entities and the federated graph is acting as a Entity graph (graphId=Entitygraph) and GetAllElements operation is run with a view of Edge. Instead of throwing an error informing Edge does not exist in EntityGraph the GetAllElements operations is able to run and (correctly) returns empty list.

Change this to match how the mirror version (EdgeGraph with view of Entity) errors.

**Comment by d47853** [comment]
Merged into develop
