### ISSUE TITLE
Improve error message for unsupported operations in the federated store

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#2209]
At present, when handling an unsupported operation, the federated store returns an internal server error with status code 500. There is no descriptive error message. To correct this, the following code could be removed from the FederatedStore class:
```java
    @Override
    protected Object doUnhandledOperation(final Operation operation,
                                          final Context context) {
        throw new UnsupportedOperationException();
    }
```
A test would need to be added to confirm the new behaviour.

**Comment by saksham93** [comment]
I wish to work on this issue.
@d47853 - Should we remove this code or add a meaningful message in the exception? Please suggest.

**Comment by d47853** [comment]
I think as long as the standard error message is informative, you can remove the method.

**Comment by saksham93** [comment]
@d47853 - I agree with you. It is already implemented correctly in super class i.e. Store.java. I have raised the PR for the same.
Thank you.

**Comment by d47853** [comment]
Thanks for your contribution @saksham93 - it looks great. I've added a suggestion to the PR which adds a unit test to confirm the new behaviour. You should be able to commit the suggestion by navigating the the pull request and clicking "commit suggestion" on the comment. Once that's done, we can merge it in 👍

**Comment by d47853** [comment]
Merged into develop
