### ISSUE TITLE
Bug: No Message for java.lang.NullPointerException when not implementing transforms for all groups in query

### ISSUE THREAD

**Issue by c95560** [gchq/Gaffer#2216]
If you perform a transform as part of a view or operation, then you will encounter a java.lang.NullPointerException error if there is a partial mapping from the groups of incoming elements to transformFunctions. The globalElements, globalEntities, globalEdges properties are not affected by this issue.

If the user does not know what element groups are going to present at query runtime before a transform, then they are forced to specify a tranformFunction for all groups in the schema.

See lack of null checks around line 59: https://github.com/gchq/Gaffer/blob/06ea720b482f8be0d4a5cf4def59a95906615cee/core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/util/TransformStreamSupplier.java

The following JSON will reproduce the error for road-traffic-demo:
https://github.com/gchq/Gaffer/blob/06ea720b482f8be0d4a5cf4def59a95906615cee/example/road-traffic/scripts/start.sh

`
{
	"class": "OperationChain",
	"operations": [{
			"class": "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements"
		},
		{
			"class": "Transform",
			"entities": {
				"Cardinality": {
					"functions": [{
						"selection": [
							"count"
						],
						"function": {
							"class": "ToString"
						},
						"projection": [
							"countStringB"
						]
					}]
				}
			}
		},
		{
			"class": "Filter",
			"entities": {
				"Cardinality": {
					"predicates": [{
						"selection": [
							"count"
						],
						"predictate": {
							"class": "IsMoreThan",
							"orEqualTo": false,
							"value": {
								"Long": 580
							}
						}
					}]
				}
			}
		}
	]
}
`

**Comment by d47853** [comment]
Merged into develop
