### ISSUE TITLE
Create Map filter functions

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#228]
Currently we have functions such as FreqMapIsMoreThan filter. 

It would be much neater to have a general MapFilter, which could be initialised with a IsMoreThan filter.

**Comment by p013570** [comment]
## Migration Steps
FreqMapIsMoreThan has been replaced with MapFilter and the standard IsMoreThan filter.

Instead of doing:
```java
new FreqMapIsMoreThan("key1", 2, true)
```
or 
```json
{
  "class" : "gaffer.function.simple.filter.FreqMapIsMoreThan",
  "key" : "key1",
  "frequency" : 2,
  "orEqualTo" : true
}
```


you now have to do:
```java
new MapFilter("key1", new IsMoreThan(2, true))
```
or
```json
{
  "class" : "gaffer.function.MapFilter",
  "function" : {
    "class" : "gaffer.function.simple.filter.IsMoreThan",
    "orEqualTo" : true,
    "value" : 2
  },
  "key" : "key1"
}
```

**Comment by a09631** [comment]
Pull request updated and merged in to develop branch.
