### ISSUE TITLE
RemoveGraph Federated-store operation doesn't function as part of an operation chain

### ISSUE THREAD

**Issue by r32575** [gchq/Gaffer#2291]
The [RemoveGraph](https://github.com/gchq/Gaffer/blob/develop/store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/RemoveGraph.java) operation for the federated-store at present only supports entering the required graphId. However, if you want to include it in an operation chain getting the graph ID through some other method then removing the graph dynamically you are at present unable to with RemoveGraph as it you cannot enter values dynamically like other [GetElements](https://github.com/gchq/Gaffer/blob/develop/core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/get/GetElements.java) operations that use the input instead.

**Comment by n3101** [comment]
@d47853 Is this a bug or just absence of a feature? I'm not clear whether it's desirable or not.

**Comment by d47853** [comment]
It's an absence of a feature. It's desirable to have it be chainable.

**Comment by n3101** [comment]
@d21211122 said: "I think caution is maybe best. The main usage of RemoveGraph is when you create temporary graphs as part of a chain and then tidy them up later, in which case you'd know the name of the graph and can simply include it in the operation. Passing graph names into RemoveGraph does carry risk, especially if you have lots of write accesses.

I can see an argument for making it parameterised, though, whether that's via a named op  or some other way"

**Comment by n3101** [comment]
Even the original poster @r32575  has voted (offline) to kill this issue.
