### ISSUE TITLE
FederatedStore FederatedAccess: Read Write Predicates should be AccessPredicate objects, not Strings.

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2319]
FederatedStore-FederatedAccess: Why are Read Write Predicates Strings and not AccessPredicate objects?

This requires deserialisation on every usage of FederatedAccess on graphs, This seems wasteful.

**Comment by d47853** [comment]
The Read/Write Access predicates are stored as strings because the parent object be serialisable (so that they may be stored in a Disk Cache). It's the same story for Named Operations / Named Views

**Comment by GCHQDev404** [comment]
I'm not understanding, I might be missing something fundamental here is the JSON serialiser not being used in this example?

**Comment by d47853** [comment]
To answer your first question, no. For the JCS cache, they currently they use Java serialisation. Maybe that's something we could (and probably should) change.

**Comment by d47853** [comment]
And for the FederatedAccessDetail question, maybe but the FederatedAccess object is already fulfilling that role

**Comment by GCHQDev404** [comment]
As I understand it. We are in agreement that `FederatedStoreCache` can be modified to handle the manipulation of unserialisable `AccessPredicate` into cached strings and then retrieved back into `AccessPredicate` objects. 

This will clean up the code and be "logically" a more performant `FederatedAccess` object (real world difference will likely be minimal).

It is likely that `NamedOperations` and `NamedViews` should follow the same changes. This is likely should be achieved by a default caching mechanism (similar to `FederatedStoreCache`) which serialises as default using `JSONserialiser` or `uk.gov.gchq.gaffer.serialisation.implementation.*`. A lot of effort has been made across gaffer development to use these serialisers, only to find issues with the JavaSerialiser via `JCSCache`.

**Comment by n3101** [comment]
After discussion, this item won't be handled as part of the alpha-3 fedstore merging, but will be reviewed as part of alpha-5 and a decision taken then as to whether to handle it there or after the later NamedOperation changes

**Comment by n3101** [comment]
We may not in the end include any NamedOperation changes in 2.0. The question here is whether this item is worth doing and, if it is, whether it has to be included in the 2.0 release or can be be left to the post-2.0 backlog

**Comment by GCHQDev404** [comment]
Due to test FederatedStoreCacheBackwardCompatibilityTest requiring backwards compatibility of the Cache I can't do smarter changes with the cache as required.

**Comment by GCHQDev404** [comment]
Have since decided the only break and migration required is the cache gets deleted and Graphs are re-added.
the underlying data is of graphs will still persist.

**Comment by GCHQDev404** [comment]
repost: Requiring Further Discussion.
It is likely that NamedOperations and NamedViews should follow the same changes. This likely should be achieved by a default caching mechanism (similar to FederatedStoreCache) which serialises as default using JSONserialiser or uk.gov.gchq.gaffer.serialisation.implementation.*. A lot of effort has been made across gaffer development to use these serialisers, only to find issues with the JavaSerialiser via JCSCache.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2862
