### ISSUE TITLE
FederatedStore-FederatedAccess: GraphAuths is now dead code which was not correctly removed.

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2320]
FederatedStore-FederatedAccess: GraphAuths is now dead code which was not correctly removed.

This should have been removed when the code was updated to use Read and Write predicates.

**Comment by d47853** [comment]
The graph auths was kept so that if the Graphs were serialised to a disk cache they could be correctly restored, making use of the graph auths in the predicate.

**Comment by d47853** [comment]
They also provide convenient configuration for users who want to use the implicit "if you have one of these auths then go ahead" logic

**Comment by GCHQDev404** [comment]
The following code is dead and not used, unless you can show me where or how it is used.

`private Set<String> graphAuths;` //This field is not used. there isn't even a get and it doesn't serialise to json anymore.
`protected boolean isValidToExecute(final User user) {`
`private boolean isUserHasASharedAuth(final User user) {`
`protected boolean isAddingUser(final User user) {`
`private boolean isAuthsNullOrEmpty() {`

**Comment by d47853** [comment]
So I can still add a graph with the graphAuths set. This will be converted to a FederatedReadAccessPredicate which will behave in the same way as before.

As for those other methods, I'm happy for them to go because as you say, they aren't used.

**Comment by GCHQDev404** [comment]
The class field `graphAuths` isn't used.

**Comment by GCHQDev404** [comment]
As I understand it we are in agreement that all of the code listed above is dead. 
With the concern that the field `private Set<String> graphAuths` is likely used and written to disk by the Java Serialiser via `JCSCache`.

@d47853 would like to check and review the effect of removing this field. The outcome may be we keep the unused field to preserve the used caches out in the "wild" until v2.

**Comment by m29827** [comment]
Made changes to remove the redundant code. The graphAuths property has been retained as per @d47853's comment to ensure backwards compatibility with Federated Graphs serialised prior to Gaffer 1.13.
