### ISSUE TITLE
FederatedStore-FederatedAccess: Inappropriate usage of GraphAuths arguments

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2321]
FederatedStore-FederatedAccess: Inappropriate usage of GraphAuths Arguments

During a AddGraph Operation a User can set `graphAuths` and `readAccessPredicates`. 
The following code appears to junk the `graphAuths` if `readAccessPredicate` was set. 

```this.readAccessPredicate = new String(JSONSerialiser.serialise(readAccessPredicate != null ? readAccessPredicate : new FederatedGraphReadAccessPredicate(addingUserId, graphAuths, isPublic)));```

This will be confusing usage for setting authorisations. It is likely that the `graphAuths` should be merged into the `readAccessPredicate`.

**Comment by d47853** [comment]
So the reason it was kept is because if you had Graphs serialised with a set of graph auths, you'd want those graph auths used in the predicate. However if the user is writing a specific predicate for the Federated store then yes those auths are ignored. I think the usage is okay but could use some documentation.

**Comment by GCHQDev404** [comment]
I'm probably missing something fundamental here, but this doesn't make sense to me.

If I am able to create a FederatedAccess object and I am able to set `graphAuths="auth1"` and I am also able to set Read/Write Predicates to `creatingUser= "me",  graphAuths="auth2", isPublic=false`

I should receive an exception notifying me that I can't set Auths & Predicates at the same time, because one will be thrown out. correct and retry. I don't think a line of documentation is correct or robust enough.

Either
- GraphAuths is Removed entirely (which will make simple graphs very verbose to create)
- Exception thrown for setting confusing parameters for a FederatedAccess object.
- GraphAuths merged into the given predicate, maybe.

**Comment by d47853** [comment]
Yeah that's fair. I agree throwing an exception if both are set is nicer.

**Comment by m29827** [comment]
Made these changes together with those for #2320. I've applied @GCHQDev404's suggestion to prevent users from mixing "old" auth configuration with the "new" AccessPredicate mechanism to Federated Access, Named Views and Named Operations which all behave similarly.
