### ISSUE TITLE
FederatedStore Rest .WAR

### ISSUE THREAD

**Issue by b956022** [gchq/Gaffer#2324]
Theres no WAR file created for a 'Federated Store' that I can see.

This issue is part of a task for gaffer-docker. To build a federated rest to run as a docker container. To get a docker container running we first need to do this piece of work to create a federated-rest.war file.

**Comment by d47853** [comment]
Going forward we don't want to add REST API's to support a given store, we would rather use a [Spring boot REST API](#2302) and add store dependencies dynamically at runtime. Until that is done you could just extend the core-rest project by unpacking the WAR and adding whatever dependencies you need. You can do it using a pom.xml file like the one detailed [here](https://gchq.github.io/gaffer-doc/components/rest-api.html#how-to-modify-the-rest-api-for-your-project)
