### ISSUE TITLE
Change AssumeTrue typo to AssertTrue

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2364]
Why has AssumeTrue been used in OperationTest?
It is the last line in a test, there is then no further test to abort/skip if found false.
When found false the test does not fail, it just aborts.

If this is incorrect then the use of assumeTrue need to be reviewed in `OperationTest`, `JSONSerialisationTest` `HazelcastCacheServiceTest`

**Comment by GCHQDev404** [comment]
Lines 91 and 105

**Comment by d47853** [comment]
I haven't checked all of them but the one in OperationTest looks like a typo. It should be `assertTrue`
