### ISSUE TITLE
Hadoop, Hbase, Spark, Kafka, Zookeeper Compatibility

### ISSUE THREAD

**Issue by rwer81** [gchq/Gaffer#2368]
Hello Team,
Is there any document for Hadoop, Hbase, Spark, Kafka, Zookeeper compatibility for Gaffer versions? Or which versions of the tools are supported by Gaffer?
Thank you.

**Comment by d47853** [comment]
No document as such - though there probably should be! The versions we support currently are:
Hadoop 2.6.5
Accumulo 1.9.3 (though it's been proved to work on 1.8.1)
Spark 2.3.2
Kafka 0.10.0.0
Hbase 1.3
Zookeeper 3.4.14

This isn't an exhaustive list but just what I pulled out of the pom.xml files.
Do you have an interest in Hbase? We put up an issue shortly before Christmas #2367. If you want to use Hbase and Gaffer, we'd love to know.
