### ISSUE TITLE
ChainedIterable Duplicated Classes.

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2369]
ChainedIterable appears to have Duplicate classes.
`uk.gov.gchq.koryphe.util.IterableUtil.ChainedIterable` & `uk.gov.gchq.gaffer.commonutil.iterable.ChainedIterable`
Combine different constructors into the same class and remove the duplicate.
Migrate into Gaffer and delete Koryphe class.

! Highlight: take the better code from Korphye and overwrite into Gaffer. !

**Comment by hj325488** [comment]
There are quite a few duplicated classes between Gaffer common-util and Koryphe core - maybe it's worth migrating all of these from Gaffer into Koryphe, especially since Gaffer common-util already has a dependency on Koryphe core?

**Comment by GCHQDev404** [comment]
The Closable needs to pulled to Gaffer and deleted from Koryphe.

see: https://github.com/gchq/koryphe/issues/222

**Comment by n3101** [comment]
@d21211122 confirms that this issue requires the dupe to be removed from Koryphe. 

There are other cases where ops duplicated between gaffer and koryphe should be removed from gaffer. They will be handled separately.

**Comment by GCHQDev404** [comment]
! Highlight: take the better code from Korphye and overwrite into Gaffer. !

**Comment by GCHQDev404** [comment]
@see gh-2553

**Comment by t92549** [comment]
Koryphe 2.2.0 made the duplicate classes public in koryphe: https://github.com/gchq/koryphe/issues/266#issuecomment-1119615541

Therefore, when https://github.com/gchq/Gaffer/pull/2644 is merged, the duplicate classes can be removed from Gaffer and replaced with references to the new koryphe ones, removing the duplication issues.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2645
