### ISSUE TITLE
JcsCacheService AgeOff unit test failure

### ISSUE THREAD

**Issue by m29827** [gchq/Gaffer#2370]
The JCS Cache Service unit test to check AgeOff fail with the following output:
```
Error:  Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.139 s <<< FAILURE! - in uk.gov.gchq.gaffer.cache.impl.JcsCacheServiceTest
Error:  uk.gov.gchq.gaffer.cache.impl.JcsCacheServiceTest.shouldAgeOffValues  Time elapsed: 3.01 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <null> but was: <1>
	at uk.gov.gchq.gaffer.cache.impl.JcsCacheServiceTest.shouldAgeOffValues(JcsCacheServiceTest.java:219)
Error:  Failures: 
Error:    JcsCacheServiceTest.shouldAgeOffValues:219 expected: <null> but was: <1>
```
The tests configure the ageOff cache with an element MaxLife of 2 seconds and therefore elements should not be retrievable after that period.

**Comment by m29827** [comment]
Once created and initialised the `uk.gov.gchq.gaffer.cache.impl.JcsCacheService` is not reconfigurable. Subsequent calls to `jcsCacheService.initialise(properties)` have no effect and just return the original instance with its original configuration.

**Comment by d47853** [comment]
Merged into develop
