### ISSUE TITLE
Update copyright to 2022

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#2382]

**Comment by n3101** [comment]
@javadev001001, @hj325488 has offered an alternative solution:
  > Is the correct format for the copyright strings: "Copyright - Crown Copyright"?

     If so, I've written a small helper script that creates this information from the Git history. 
     If this ticket isn't being worked on by anyone else at the moment, I could pick it up and 
    finish it off.

**Comment by n3101** [comment]
(Team discussion: ) This item can be done automatically with suitable hooks in updates. Come back to this after v2.0

**Comment by n3101** [comment]
@GCHQDeveloper314 Does the merging of #2588 mean that this issue can be closed?

**Comment by GCHQDeveloper314** [comment]
Yes the merging of that means this issue can now be closed. There's no need for it or similar issues in future as copyright dates are now checked automatically as part of the CI. Through this, if a change in a PR causes a date to be incorrect, this will be flagged and will need to be corrected before the PR can be merged - preventing dates from getting wrong again.

**Comment by n3101** [comment]
Satisfied by #2588
