### ISSUE TITLE
Fix scripts in demos

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#2400]
Demo scripts in develop-v2 are out of date with the changes to the codebase. Update these so they work as before.

**Comment by javadev001001** [comment]
Branch pushed 6th Apr, updated to use spring-boot maven plugin

**Comment by n3101** [comment]
Include this in a later alpha that reworks the demos.

**Comment by n3101** [comment]
This was addressed in unlinked  PR #2406 . However that has been closed as OBE. The develop-v2  branch is now obsolete, but the underlying problem here has been addressed by #2608 and this issue can now be closed.
