### ISSUE TITLE
GetElementsBetweenSets can't be used in NamedOperation

### ISSUE THREAD

**Issue by j8934893** [gchq/Gaffer#2404]
The GetElementsBetweenSets operation requires both an input and input_b.

However, if this operation is nested within an operation chain and defined as a named operation there is no way to pass in input_b. 

This addition would be required for future inclusions of operations such as: GetShortestPaths, GetWalksBetween etc. that would require multiple inputs.

The option to provide an input map with multiple input sets/collections might cover this.

Possibly something that would need to wait for v2.

**Comment by t92549** [comment]
There is currently one Operation in all of Gaffer that uses `InputB`: `GetElementsBetweenSets`. Therefore, I propose a solution where instead of a huge refactor to NamedOperations, we remove `InputB` and make a small change to `GetElementsBetweenSets` instead. The change could be that it has a single iterable Input, where the first item is what used to be `input` and the second item is what used to be `inputB`

**Comment by t92549** [comment]
After some investigation, it has been determined that the underlying Accumulo code is tightly coupled to the `GetElementsBetweenSets` operation. If a large refactor was done to remove this tight coupling, then changing the input types for `GetElementsBetweenSets` would be trivial. However, this would be a lot of work just to change one Operation.

Instead, I propose in the meantime another operation should be made which has the same behaviour but accepts a single Pair of iterables: `GetElementsBetweenSetsPairs`. This Operation would be the recommended Operation and work in OperationChains and NamedOperations.
`GetElementsBetweenSets` should be deprecated, but will be used in the underlying code for now until said refactor is done to the AccumuloStore.

**Comment by t92549** [comment]
We should also document that this is the correct approach going forward: Do not use inputB, instead use a pair of inputs.

**Comment by t92549** [comment]
Closes https://github.com/gchq/Gaffer/pull/2931
