### ISSUE TITLE
Possible timeout bug in federated queries

### ISSUE THREAD

**Issue by n3101** [gchq/Gaffer#2427]
Possible bug that needs investigation:

"I think there is a time out between the federator and its graphs. I get the same error if I use the jobs or the operations interface. I run a query that works and then change to a higher volume seed and it falls over.  I'm pretty convinced that it's a time out between the federator and the graph, and then I'm not convinced that is the expected behaviour of the async query."

**Comment by GCHQDev404** [comment]
Are you using ProxyStores with your FederatedStore?
Please examine your `connectTimeout` `readTimeout` values when adding ProxyStores.

**Comment by n3101** [comment]
This was resolved by changing config
