### ISSUE TITLE
Please get Federation to allow for subtly different schemas

### ISSUE THREAD

**Issue by n3101** [gchq/Gaffer#2429]
Can we have  increased flexibility with which subtly differing graph schemas are treated by the federated store?
Consider a graph – G1 – with a nice simple schema comprising a single edge – E1 – itself with 2 properties – P1 and P2. If someone else wants to create a graph – G2 – and amongst other things wants to store data semantically equivalent to E1, but with a bonus property P3 then we've got a problem. They can define G2 with E1, and properties P1, P2, P3 but then they won't be able to neatly federate queries with G1. That defeats the purpose. Instead they can lobby the owners of G1 to add P3 to their schema, even though they don't want to populate it themselves. Or they choose different language and are forced to define an edge E2 with properties P1, P2, P3. Then the poor end consumer of the graphs has to remember that E1 and E2 are semantically equivalent, and attempts to join them up are pushed to them. 
That all seems a bit sad to me, and it would be lovely to see FederatedStore allowing querying of two graphs with subtly different schemas.

**Comment by t92549** [comment]
This issue affects federated stores that have proxies with overlapping schemas. When you perform an operation such as GetAllElements in such a situation, the federated store checks the schemas of all the proxies individually before performing the operation on all the proxies. On a GetSchema operation, however, the federated store attempts to merge the schemas and return a single merged schema. Currently, this returns an error if one of the schemas is a subset of another, as it is seen as invalid. I will submit a PR that allows merging schemas that are subsets of one another.
