### ISSUE TITLE
Merging Schemas Mutates TypeDefinitions

### ISSUE THREAD

**Issue by sw96411** [gchq/Gaffer#2432]
Raising this issue on behalf of a colleague without a Github account...

There is a bug with the merge method in the Schema class where, when merged in a particular order, the TypeDefinition objects in the original schemas can be mutated. This appears to be due to the use of the putAll method which adds the original schema’s TypeDefinition objects to the current schema, thus when subsequent schemas are merged it alters the original schema’s types.

This is then cached in memory, resulting in strange behaviour.  

This is bad because if you have - for instance - a federated store that has multiple graphs deployed in different environments, changes to schema types when merging these graphs causes  graphs that should merge to not consistently merge as expected across these different environments which is in turn making it difficult to reproduce federation issues across these environments. 

This may also be affecting the way "mergeable" graphs" interact with non-mergeable graphs in the federated store, causing some strange, but non-consistently strange behaviour.

All of the above is compounded by the fact that the exact behaviour this issue causes depends on the order Gaffer chooses to merge the schemas in, which is undefined (IIRC, only the "first" schema gets mutated, having parts of subsequent schemas grafted to it), which means failing behaviour isn't always consistent in the wild

This behaviour was spotted after running a GetSchema operation on a FederatedStore.

The attached file demonstrates a pair of Unit Tests which should pass, but this issue causes to fail
[SchemaTest_Merge.patch.txt](https://github.com/gchq/Gaffer/files/6554998/SchemaTest_Merge.patch.txt)

**Comment by GCHQDev404** [comment]
It passes for me.
Do I need to Spam the tests until it fails? 
"exact behaviour this issue causes depends on the order Gaffer chooses to merge the schemas in, which is undefined"

**Comment by GCHQDev404** [comment]
Looped it 200 times its did fail.

**Comment by sw96411** [comment]
Glad you got it to fail.  From what I hear, we've been seeing it fail much more consistently, but that may be down to environmental factors.  If you reach out to me directly outside of this mechanism, I can put you in contact with the dev that encountered this issue in production fairly consistently
