### ISSUE TITLE
TypeValueToTupleTest doesn't appear to run correctly

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2443]
ref: gh-2211
branch `gh-2211-funcitons`

substitute the following method into `TypeValueToTupleTest` and `ReduceRelatedElementsTest`
```
    @Override
    protected Class[] getExpectedSignatureOutputClasses() {
        throw new RuntimeException();
    }
```

Only `ReduceRelatedElementsTest` fails.
I can't see why.

**Comment by m29827** [comment]
Hi @GCHQDev404 `TypeValueToTupleTest` contains a method with an identical signature to the actual `shouldGenerateExpectedOutputSignature` test in `uk.gov.gchq.koryphe.function.FunctionTest`. Therefore the test which you expect to fail is overridden and never gets executed, to fix remove the method `TypeValueToTupleTest.shouldGenerateExpectedOutputSignature`.

**Comment by n3101** [comment]
@p3430233 , m29827 appears to have diagnosed this bug that is blocking something you were working on a while back. Please will you see if you can apply his suggestion to make this test work and thereby unblock yourself?

**Comment by GCHQDev404** [comment]
@m29827
OOOOH this is JUnit 5 bug/not bug when the @Test annotations are not inherited!!
