### ISSUE TITLE
Code tidying - can branch gh-278 be deleted

### ISSUE THREAD

**Issue by n3101** [gchq/Gaffer#2454]
Issue gh-278 was closed in Dec 2016 and the work exported to gaffer-experimental. Can this dead branch be zapped?

**Comment by t92549** [comment]
It seems that the branch has some functionality but is very outdated and would need a bit of work before it is usable with current Gaffer and Elasticsearch versions. It also hasn't been moved over to gaffer-experimental yet so perhaps the branch shouldn't be deleted until it lives somewhere else/someone picks up the work if there is demand for it. It seems though that a lot of experimental store types live in Gaffer, like parquet, not gaffer-experimental but I am not sure where the best place for it to live would be.

**Comment by n3101** [comment]
@t92549 Well if this one can be moved to experimental that is fine. Parquet is another matter.

**Comment by t92549** [comment]
Cool, was just checking where the "correct" place for experimental store types is and it makes sense that it is gaffer-experimental

**Comment by t92549** [comment]
Closed as WIP was moved to https://github.com/gchq/gaffer-experimental/commit/dea50cd70523a92b7545e0af72782f2cada5d390 and branch deleted.
