### ISSUE TITLE
Can branch gh-1754-make-Getwalks-configurable be deleted?

### ISSUE THREAD

**Issue by n3101** [gchq/Gaffer#2461]
Issue https://github.com/gchq/Gaffer/issues/1754 was closed earlier this year as having been overtaken by https://github.com/gchq/Gaffer/pull/2372. Can the associated branch gh-1754-make-Getwalks-configurable be zapped?

**Comment by t92549** [comment]
Branch has been deleted as it was indeed superseded by #2372
