### ISSUE TITLE
Drop "simple" from "simple-*-library"

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#248]
The word "simple" in "simple-function-library", "simple-operation-library" and "simple-serialisation-library" is unnecessary. These libraries should contain functions / operations / serialisers that are likely to be useful to Gaffer users. Over time they may contain more complex functionality than now, and so "simple" will be misleading. Propose simply removing the word "simple" from each of these.

**Comment by p013570** [comment]
Merged into develop.
