### ISSUE TITLE
Upgrade spring-rest tests to JUnit 5 

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2497]
Currently, the spring-rest api is on spring-boot 1 so must use JUnit 4. However, when we upgrade to spring-boot 2 as part of Gaffer 2 (#2496), we can upgrade the tests in that module to use JUnit 5.

**Comment by GCHQDeveloper314** [comment]
The work to upgrade Spring is contained in the PR #2598, however that doesn't include upgrading the tests, they are still JUnit 4. This issue will need to be worked on separately once that PR is merged.

**Comment by t92549** [comment]
Resolved by https://github.com/gchq/Gaffer/pull/2626
