### ISSUE TITLE
Add CsvElementGenerator generator and AddElementsFromCsv operations

### ISSUE THREAD

**Issue by p3430233** [gchq/Gaffer#2549]
An implementation already exists on gh-1867-csv-element-generator-2

**Comment by t92549** [comment]
We cleaned up the implementation that lived on `1867-csv-element-generator-2` but after looking at it further, it seems that it is superseded by https://github.com/gchq/Gaffer/issues/1867 and is not required for https://github.com/gchq/Gaffer/issues/2558 so we are going to delete the branch, close this ticket and improve on it in #2558
