### ISSUE TITLE
Add Closeable classes from Koryphe

### ISSUE THREAD

**Issue by r32575** [gchq/Gaffer#2553]
Add the `Closeable` classes from `Koryphe` that are marked as deprecated for deletion. See [https://github.com/gchq/koryphe/issues/222](url) for details.

**Comment by n3101** [comment]
@r32575 Is this task in fact the same as #2369? Or are there differences?

**Comment by GCHQDev404** [comment]
ClosableIterable type classes where deleted, as wrappers provided to help.

**Comment by GCHQDev404** [comment]
> ClosableIterable type classes where deleted, as wrappers provided to help.

@see gh-2369

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2583
For summary, see https://github.com/gchq/Gaffer/pull/2583#discussion_r850527014
