### ISSUE TITLE
add ImportCsv operation and generator

### ISSUE THREAD

**Issue by p3430233** [gchq/Gaffer#2558]
Create operations that build upon those added in gh-2549 that work to/with a standardised file format

**Comment by t92549** [comment]
For the standard format, something like this would be nice and compatible: https://docs.aws.amazon.com/neptune/latest/userguide/bulk-load-tutorial-format-opencypher.html

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2647
