### ISSUE TITLE
Implement serialisers and aggregators for more sketches from the stream-lib library

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#256]
Gaffer provides a serialiser and an aggregator for the HyperLogLogPlus sketch from the stream-lib library. That library contains other useful sketches such as Count Min Sketch. Serialisers and aggregators should be provided for those. Specifically, they should be written for: CountMinSketch, QDigest, TDigest.

**Comment by p013570** [comment]
@gaffer01 - is this still something you think we should do? Or has this been superseded by all the other sketches we have added?
