### ISSUE TITLE
Improve process for updating copyright headers

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#2588]
At the moment there are no automatic checks to ensure that copyright dates are updated when a file is modified. Instead there's a reliance on checking this as part of code review. This approach has resulted in copyright dates becoming wrong. Issues (such as #2382) are then opened to correct this. This manual approach requires more work than if the headers were updated in the first place.

There have been some previous efforts to fix this; in the form of scripts which need to be run manually. This is not ideal as requires a separate step (which will get forgotten) and it doesn't integrate with existing code checks (checkstyle).

The [Spotless general-purpose formatting plugin](https://github.com/diffplug/spotless/tree/main/plugin-maven) offers [a feature](https://github.com/diffplug/spotless/tree/main/plugin-maven#license-header) for adding and updating licence/copyright headers. This is a maven plugin and so can be run as part of checks. If it finds a problem it will print out a diff suggesting how this can be fixed, with an option to apply this automatically. **Integrating these checks into the project will automate header management and prevent any time needing to be spent on manual fixes.**

_As an aside, it might seem like we can use git history to find when a file was last updated and use this to periodically check the headers are correct. This is an oversimplification which doesn't take into account renaming/moving of files, files for a feature which was written in December but merged in January, old files imported from other sources, etc._

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2633
