### ISSUE TITLE
Tests involving Strings fail when run on Windows

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#2591]
When running Gaffer tests on Windows 10, tests which involve reading `String` data from disk and comparing it to those not from disk fail.
This is an example from the `serialisation` tests - [code here](https://github.com/gchq/Gaffer/blob/eec0c3f1e9851e1310b7345b1fe97d812c497608/core/serialisation/src/test/java/uk/gov/gchq/gaffer/serialisation/implementation/MultiSerialiserTest.java#L68):
```
[ERROR] Failures:
[ERROR]   MultiSerialiserTest.shouldMatchHistoricalFileSerialisation:80 expected: <{
  "serialisers" : [ {
    "key" : 0,
    "serialiser" : {
      "class" : "uk.gov.gchq.gaffer.serialisation.implementation.StringSerialiser"
    },
    "valueClass" : "java.lang.String"
  }, {
    "key" : 1,
    "serialiser" : {
      "class" : "uk.gov.gchq.gaffer.serialisation.implementation.raw.CompactRawLongSerialiser"
    },
    "valueClass" : "java.lang.Long"
  }, {
    "key" : 2,
    "serialiser" : {
      "class" : "uk.gov.gchq.gaffer.serialisation.implementation.raw.CompactRawIntegerSerialiser"
    },
    "valueClass" : "java.lang.Integer"
  } ]
}> but was: <{
  "serialisers" : [ {
    "key" : 0,
    "serialiser" : {
      "class" : "uk.gov.gchq.gaffer.serialisation.implementation.StringSerialiser"
    },
    "valueClass" : "java.lang.String"
  }, {
    "key" : 1,
    "serialiser" : {
      "class" : "uk.gov.gchq.gaffer.serialisation.implementation.raw.CompactRawLongSerialiser"
    },
    "valueClass" : "java.lang.Long"
  }, {
    "key" : 2,
    "serialiser" : {
      "class" : "uk.gov.gchq.gaffer.serialisation.implementation.raw.CompactRawIntegerSerialiser"
    },
    "valueClass" : "java.lang.Integer"
  } ]
}>
```
In the terminal, the two JSON strings are visibly the same. The reason for the failure will be the encoding used for the file on disk, or more likely the line endings. This problem can hopefully be corrected by ensuring that UTF-8 is always used (not some other system default) and that Unix line endings are always used and not the system default (only Windows doesn't use Unix line endings).

**Comment by GCHQDeveloper314** [comment]
The problem above has been fixed. The following other problems still need to be fixed:

Hardcoded UNIX newlines:
https://github.com/gchq/Gaffer/blob/9986d3b0dc54e95fcaf24128758da4d23c793954/core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/join/match/KeyFunctionMatchTest.java#L70-L78

Regex (which appears to be redundant) which rejects Strings containing Windows/DOS paths:
https://github.com/gchq/Gaffer/blob/9986d3b0dc54e95fcaf24128758da4d23c793954/core/store/src/main/java/uk/gov/gchq/gaffer/store/library/FileGraphLibrary.java#L42

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2709 and https://github.com/gchq/Gaffer/pull/2714
