### ISSUE TITLE
Should strict JSONSerialiser be false by default?

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2596]
Currently `STRICT_JSON_DEFAULT` is set to false: https://github.com/gchq/Gaffer/blob/f54e069c27a61587e54f6406697ad9a4a726d88b/core/serialisation/src/main/java/uk/gov/gchq/gaffer/jsonserialisation/JSONSerialiser.java#L85

This means that if the json file provided to create a Schema does not match a schema object, an empty Schema is created rather than an error.

Java example:
```java
Schema s = Schema.fromJson(new File("mySchema/").toPath())
```
mySchema/elements.json:
```json
{
    "beans": 6
}
```
Then the variable `s` is an empty schema:
```json
{
    "types": { }
}
```

This can be resolved per graph by changing the `gaffer.serialiser.json.strict` StoreProperty to true, or changing the default setting for all graphs, `STRICT_JSON_DEFAULT`, to true.

However, this may break some users' Schemas if they include additional metadata.

Do we want to keep this strict serialiser false by default?

**Comment by t92549** [comment]
After digging into this more, it turns out this property does already exist but is disabled by default:
https://github.com/gchq/Gaffer/blob/f54e069c27a61587e54f6406697ad9a4a726d88b/core/store/src/main/java/uk/gov/gchq/gaffer/store/StoreProperties.java#L76
https://github.com/gchq/Gaffer/blob/f54e069c27a61587e54f6406697ad9a4a726d88b/core/serialisation/src/main/java/uk/gov/gchq/gaffer/jsonserialisation/JSONSerialiser.java#L85

Should it be enabled by default?

**Comment by n3101** [comment]
@t92549 I don't think I care which is the default, provided that there is documentation which tells you what it is; and how to change it if you don't like it.  
Also, when the setting results in an error, do you get a meaningful error message?

**Comment by t92549** [comment]
I think this confusion could have been avoided in the first place if it was indeed documented better.

As for the exception:
```
...
Caused by: uk.gov.gchq.gaffer.exception.SerialisationException: Unrecognized field
"elements" (class uk.gov.gchq.gaffer.store.schema.Schema$Builder), not marked
as ignorable ...
```

It's quite verbose but it does describe the problem, here I had wrapped a valid schema with the field "elements".

**Comment by t92549** [comment]
Originally this ticket was to add a store property for strict json, however, after digging it already existed. The ticket was then changed to ask if the default should be true, as it would have not caused this issue.
However, I am closing this ticket as the default doesn't really matter, this confusion could have been avoided if the StoreProperties were documented better, tracked by https://github.com/gchq/gaffer-doc/issues/271.
