### ISSUE TITLE
Upgrade dependencies to newer versions

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#2598]
There are already specific issues for Accumulo, Hadoop and some others. This covers upgrading the remaining dependencies, which are mostly more minor, to either the newest available version or the newest that is compatible with the versions of Accumulo/Hadoop/Spark. Where major code changes are required we should create an issue specific to that dependency.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2608
