### ISSUE TITLE
Update Gaffer 2 README

### ISSUE THREAD

**Issue by n3101** [gchq/Gaffer#2600]
The Gaffer Readme used for alpha 1 still documents gaffer-tools artefacts we have removed in alpha1 - jar-shader, slider & schema-builder. (but not the analytic ui).

**Comment by t92549** [comment]
As well as removing these old tools references, the docs links should point to the "latest" docs so that when the v2 docs are released, they work automatically.

**Comment by t92549** [comment]
Fixed by #2607
