### ISSUE TITLE
Port new doc infrastructure from gaffer 2.0 alpha 1 into Gaffer 1.

### ISSUE THREAD

**Issue by n3101** [gchq/Gaffer#2601]
As part of Gaffer 2.0 work, a new doc structure & tech has been developed which will make it easier to document Gaffer better in future.
This is a non-breaking change, so port this into Gaffer 1 and release.

**Comment by t92549** [comment]
Closing as the Gaffer 1 README currently does point to the new v1docs, as added by https://github.com/gchq/Gaffer/issues/2565
