### ISSUE TITLE
Comparable property pairs are order dependant

### ISSUE THREAD

**Issue by c95560** [gchq/Gaffer#2610]
See:
https://github.com/gchq/Gaffer/blob/f54e069c27a61587e54f6406697ad9a4a726d88b/core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/OperationChainValidator.java#L137

isAssignableFrom cast check only occurs in one direction for comparable pair. 
i.e. first item in pair is checked if assignable from second

This means we have a comparison which throws an error depending on the order of properties in the pair. 
Should it not be order independent? Or is the order dependent logic intentional?

**Comment by GCHQDev404** [comment]
> isAssignableFrom cast check only occurs in one direction for comparable pair.

The "pair" object at this area of code IS NOT THE ELEMENTS BEING COMPARED.
see:
https://github.com/gchq/Gaffer/blob/f54e069c27a61587e54f6406697ad9a4a726d88b/core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/OperationChainValidator.java#L129

The method `getComparableGroupPropertyPairs` ^ returns a pair, this is a `(group, property)` object.
  
 `pair.first()` is the Schema element `group` of thing you want to compare.
 `pair.second()` is the Schema `property` within that group you want to compare.
  it seems Pair object was chosen in place of defining a POJO with field variables `group` and `property`
  
This pair isn't a "Pair of things to compare" it contains the LOCATION of the value within elements you want to compare.
example if the schema defined `{"group" = "road", "property" = "milesLong"}` for when you want to compare roads by length. In this example `pair.first()` will be "road" and `pair.second()` will be "milesLong".
Neither value in the pair object will be the milage of the road. 
 
 An example of this pairing being created is here:
https://github.com/gchq/Gaffer/blob/f54e069c27a61587e54f6406697ad9a4a726d88b/core/data/src/main/java/uk/gov/gchq/gaffer/data/element/comparison/ElementPropertyComparator.java#L120

if at 
https://github.com/gchq/Gaffer/blob/f54e069c27a61587e54f6406697ad9a4a726d88b/core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/OperationChainValidator.java#L137
 the `propertyClass` retrieved from the schema which belongs to the property value in `pair.second()` is NOT COMPARABLE. then you have written a schema and defined a property which is not a comparable object, so you cannot compare it.

which would have been specified in the error message
```java
validationResult.addError("Property " + pair.getSecond()
                                + " in group " + pair.getFirst()
                                + " has a java class of " + propertyClass.getName()
                                + " which does not extend Comparable.");
```



> the order of properties in the pair.

The pair is a `(group, property)` object as defined above.
"There can only be one" :- Connor MacLeod

**Comment by GCHQDev404** [comment]
I'm going to close this ticket.

but if I have miss understood you please re-open and provide more details.
include the error message and group schema.

**Comment by c95560** [comment]
Thanks for clarifying. May have been some confusion due the method types and signature for  getComparableGroupPropertyPairs(). 

Following through the logic you are right - I don't believe this is a bug, happy to have this closed. Can't recall if there was any further context, this issue was reported a while back but was never investigated.
