### ISSUE TITLE
Enable alternative authentication to Accumulo

### ISSUE THREAD

**Issue by n3101** [gchq/Gaffer#2614]
Gaffer authenticates to Accumulo using stored username & password. 
There is now a requirement to offer a choice of authentication either using Kerberos or the existing username/password. 

(https://github.com/gchq/Gaffer/issues/2348 previously enquired about setting up Gaffer to authenticate to Accumulo using Kerberos)

This needs to work with Accumulo 2. If possible also make it work for Accumulo 1.

**Comment by n3101** [comment]
Actually Kerberos may not be the preferred authentication mechanism. Wait for clarification.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2737
