### ISSUE TITLE
WAR packaging is not working correctly

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#2634]
Maven WAR packaging (with the [`maven-war-plugin`](https://maven.apache.org/plugins/maven-war-plugin/index.html)) is used for `basic-rest`, `core-rest`, `map-rest`, `accumulo-rest`, `road-traffic-rest`, `road-traffic-demo` and `federated-demo`. The dependency upgrade #2608 specified to use the latest version of this plugin instead of the default automatically selected by Maven which is very old.

The latest version of this plugin has a problem/bug. This causes the web.xml file to not be copied into the war in certain situations. A default file is used instead. This is a problem because this file is where classes to be used by the WAR are specified. For example to specify a class to load example data.

This problem was not noticed because the WAR files created are not tested as part of this repository. The problem was noticed when a test was failing while trying to upgrade `gaffer-tools`. A separate issue will be raised to look at improving testing to prevent this type of problem reoccurring.

Switching to using a previous version of the `maven-war-plugin` (3.2.3) fixes the problem above - this is still much newer than the version Maven uses by default.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2635
