### ISSUE TITLE
Extend NamedOperations to accept new types of parameter

### ISSUE THREAD

**Issue by n3101** [gchq/Gaffer#2639]
This was originally tacked onto another issue, but should be handled separately: 

"I think it is worth thinking about how parameters that are not int, str, or bool are actually passed. It feels weird (to me) that you cannot pass a Long parameter into a named operation."

Identify whether there are any other input types that NamedOps should accept and add them.

**Comment by t92549** [comment]
You can have Long parameters, as well as doubles, floats and other Java types. There is even an example using a Long in the [documentation](https://gchq.github.io/gaffer-doc/v1docs/getting-started/operations/namedoperation.html) and in the tests:
https://github.com/gchq/Gaffer/blob/3ed00784f19e6b11daba65007ad94d9328c70f24/core/graph/src/test/java/uk/gov/gchq/gaffer/graph/hook/NamedOperationResolverTest.java#L188

**Comment by t92549** [comment]
@n3101 I can see the json and python examples in the doc:
```json
"param1" : {
    "description" : "Limit param",
    "defaultValue" : 1,
    "valueClass" : "java.lang.Long",
    "required" : false
}
```

**Comment by n3101** [comment]
@t92549 Well I see this java example:

Map<String, Object> paramMap = Maps.newHashMap();
paramMap.put("param1", 2L);

final NamedOperation<EntityId, CloseableIterable<EntityId>> operation =
        new NamedOperation.Builder<EntityId, CloseableIterable<EntityId>>()
                .name("2-hop-with-limit")
                .input(new EntitySeed(1))
                .parameters(paramMap)
                .build();
    
if I toggle to see  the corresponding full json I get:            
                
{
  "class" : "uk.gov.gchq.gaffer.named.operation.NamedOperation",
  "input" : [ {
    "class" : "uk.gov.gchq.gaffer.operation.data.EntitySeed",
    "class" : "uk.gov.gchq.gaffer.operation.data.EntitySeed",
    "vertex" : 1
  } ],
  "operationName" : "2-hop-with-limit",
  "parameters" : {
    "param1" : 2
  }
}

**Comment by t92549** [comment]
Those examples are equivalent, they just look a bit different due to the differences in Java and json.
Although there is a strange bug where `"class" : "uk.gov.gchq.gaffer.operation.data.EntitySeed",` is shown twice in the json

**Comment by n3101** [comment]
@t92549 Ok, I think this is a doc issue. I see that it is already covered by https://github.com/gchq/gaffer-doc/issues/156 (point 4)
