### ISSUE TITLE
Retrieval of domain objects through REST API

### ISSUE THREAD

**Issue by flitte** [gchq/Gaffer#265]
Currently, the default return types of most of the operations which can be carried out against a graph are something along the lines of Iterable<? extends Element>.

I have a use case where I want to be able to consume domain objects (i.e. those which I have written object generators for) directly from the REST API - is this something that could be supported?

Currently I am having to use the doOperation endpoint exclusively and add the domain object generation as a step at the end of an operation chain. Ideally, I'd like to make no assumptions about the data model (or the available generator classes) in the applications which I am writing to consume the graph.

**Comment by p013570** [comment]
Hi @flitte,

Interesting question. As you mentioned this can be done via an operation chain, similar to:

Java
```java
final OperationChain<Iterable<SimpleEdgeDataObject>> opChain = new OperationChain.Builder()
        .first(new GetRelatedElements.Builder()
                .addSeed(new EntitySeed("vertex1"))
                .build())
        .then(new GenerateObjects.Builder<Element, CustomGenerator>()
                .generator(new CustomGenerator())
                .build())
        .build();
```

JSON
```json
{
  "operations": [
    {
      "class": "gaffer.operation.impl.get.GetRelatedElements",
      "seeds": [
        {
          "gaffer.operation.data.EntitySeed": {
            "vertex": "vertex1"
          }
        }
      ]
    },
    {
      "class": "gaffer.operation.impl.generate.GenerateObjects",
      "elementGenerator": {
        "class": "package.name.CustomGenerator"
      }
    }
  ]
}
```

We have thought about creating a generator registry to avoid having to supply the CustomGenerator to the GenerateObjects operation and then Gaffer would automatically use the correct generator for you. However, selecting the correct generator to use isn’t always possible if there are multiple generators dealing with different domain objects - users would need to specify the type of domain object they wished to be returned.

As it stands, you could write an ElementGenerator implementation that could deal with all elements and correctly hand the elements off to the correct ElementGenerator automatically. This could be based on the element group (see [gaffer.example.films.generator.DataGenerator](https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/blob/master/example/src/main/java/gaffer/example/films/generator/DataGenerator.java), or a particular property value (such as 'domainClass').
