### ISSUE TITLE
Add unit tests for integration test suite

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#2654]
Currently the [integration-test](https://github.com/gchq/Gaffer/tree/v2-alpha/integration-test) module is untested. It defines test classes which are used/extended by various Gaffer stores, but these tests are not tested themselves (unit or integration).
Usually tests don't have tests. But in this case integration-test is used as a utility class for other parts of Gaffer and is not simply a traditional test.

Adding some unit tests to integration-test will help to prevent problems caused by other changes from going undetected. Due to how the tests classes are written, there's a potential for tests to become broken without this being detected. This is because if the tests do not run or are skipped then it will appear from the CI that there's no problem.

**Comment by n3101** [comment]
@GCHQDeveloper314 How big a piece of work is this?

**Comment by GCHQDeveloper314** [comment]
This is small piece of work. I would anticipate only a couple of new files containing some basic Unit tests.

**Comment by lb324567** [comment]
Fixed by #2732
