### ISSUE TITLE
Warn when an Accumulo store is initialised against an existing non-Gaffer table

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#267]
If a user manually creates an Accumulo table (without adding Gaffer's iterators), and then creates a graph using store properties containing that table name, then the Accumulo initialise method will correctly notice that the table exists and not reinitialise it. This means that as far as Gaffer is concerned the table was created correctly, but actually it is just an empty table with no iterators.

This has caused confusion with some users as they manually create the table, then create the graph, then add data and notice that no aggregation is happening, which is then reported as a bug or a misconfiguration.

It's not clear what they best way to deal with this is. Options:
- If the table is already present the `ensureTableExists` method in `TableUtils` should log this, and say something like "Table X already exists. For correct operation it must have been created using Gaffer code."
- When creating a graph using a store that already exists, is there any way to check that this store is a Gaffer store, rather than just an empty Accumulo table?

**Comment by p013570** [comment]
So we could check the table is configured in the same way Gaffer configures a table. When gaffer creates an Accumulo table it always removes the Accumulo Versioning iterator and adds a bloom filter property. It then adds a validator iterator and an aggregator iterator (if the schema has aggregators).

**Comment by p013570** [comment]
It is surprisingly common for users to think they need to manually create a table in Accumulo before creating an AccumuloStore. If they do this then the table will not have the correct Bloom filters and iterators set, and this will cause poor performance and errors.

We should investigate setting a configuration property on a table when Gaffer creates it. Whenever a new store is created against that table, then the property could be checked, and if it is not present then the creation of the store should fail (if there are scenarios where experienced users may need to manually create a table and add iterators, then there could be an option on the store properties to ignore this warning, and carry on, but the default should be to fail).

**Comment by p013570** [comment]
# Migration Steps

In the common-util test module we have renamed JsonUtil to JsonAssertUtil.

**Comment by t616178** [comment]
Merged into develop.
