### ISSUE TITLE
Question: Why does DisabledByDefault marker only hides graphs when graphIds are null in graphStorage.get(null) 

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2681]
Question: Why does DisabledByDefault marker only hides graphs when graphIds are null in graphStorage.get(null) 

ref: FederatedGraphStorageTest.shouldNotGetDisabledGraphForAuthUserWhenNoIdsProvided()
ref: FederatedGraphStorageTest.shouldGetDisabledGraphWhenGetAll()

ToBe explored, currently don't understand the value or use of it. Can it be removed.

ref: FederatedStore.getDefaultGraphs() is default graphs preserved if it usage is understood.
ref: FederatedGraphStoreage.getStream

**Comment by GCHQDeveloper314** [comment]
Since this was raised various changes have been made to the referenced class. The code no longer contains references to `DisabledByDefault`.

@GCHQDev404 - Is it your understanding that this marker was removed?

**Comment by GCHQDeveloper314** [comment]
No longer required as the code relating to `DisabledByDefault` has been removed.
