### ISSUE TITLE
Question: Why does simple variable change cause test to fail for cache Backwards compatibility test.

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2682]
Question: Why does simple variable change cause test to fail for cache Backwards compatibility test.

ref: FederatedStoreCacheBackwardCompatibilityTest 
field variables MAP_ID_1 and ADDING_USHE_ID

**Comment by GCHQDeveloper314** [comment]
In #2895 changes were made to this class. There's now a need to check that this issue is still present.

**Comment by GCHQDev404** [comment]
The value is set by the value in the cache data files. the test must match those values. 

The cache backwards compatibility tests should be deleted. due to cache is not a precious immutable object.

**Comment by GCHQDev404** [comment]
The value is set by the value in the cache data files. the test must match those values.

The cache backwards compatibility tests should be deleted. due to cache is not a precious immutable object.
