### ISSUE TITLE
Add CI workflow for legacy Accumulo 1 tests

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#2693]
Accumulo 2 became the default version of Accumulo in Gaffer in #2679. Accumulo 1 support was retained with a `legacy` profile.

Currently the CI runs tests for all Maven modules for the default configuration (Accumulo 2). No tests are run with the Accumulo 1 legacy profile. This creates a risk where a PR containing changes which were only compatible with Accumulo 2 might be merged; given that that CI would not detect any problems.

To prevent this from happening, a new GitHub Actions workflow should be added to separately run tests with the Accumulo 1 legacy profile activated. This workflow doesn’t need to run all tests, only tests which involve Accumulo libraries.

**Comment by t92549** [comment]
It would also be nice to test everything against both Java 11 and Java 8.

**Comment by lb324567** [comment]
This would be a new action that would only run the Accumulo store tests, on all PRs **but** only if changes have been made to the Accumulo store.

**Comment by r32575** [comment]
As the `Guava` and `Hadoop` versions differ for `Accumulo` v1 and v2 it may be best to just run all the tests

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2894
