### ISSUE TITLE
Same groups for Entities and Edges

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#270]
Currently, the same groups are not allowed to be used in Entities and Edges - if they are a message of "Groups must not be shared between Entity definitions and Edge definitions" is produced and then a `SchemaException` is thrown.

A very common use-case is to have a graph with say Edges with a group of "red", edges with a group of "blue", and then to have Entities with the same groups which contain the corresponding properties. E.g. the red edges have a count statistic, and each end of the edge has a red Entity associated with it which also contains a count (which is the count aggregated from all the red edges that that vertex is involved in). Similarly the blue edges might have a frequency map property, and there would also be blue vertices with that property that aggregate over associated edges.

It seems wrong to force the user to have a group of "EntityRed" for the Entities and "EdgeRed" for the Edges.

Is there a good reason for this restriction?

**Comment by james010101101** [comment]
One Reason for the restriction is the avoidance of unnecessary parsing to find out if a given element is an Edge or Entity, for example in the accumulostore,  when aggregating properties the aggregation iterator takes the unique group name from the Column Family and knows for this key and Value Iterable how to deserialise the value into gaffer properties.
If group names were not unique it would also need to inspect the rowID to determine if the aggregator had the edge or entity to determine which property set the value should be deserialised too. The amount of work to inspect the rowID  would depends on the rowID structure (key-package) and may not be that much extra work, but it does add this extra processing.

**Comment by gaffer01** [comment]
Probably the right thing to do is to decide whether a schema should allow the same group name for entities and edges, independent of any particular store. I tend to think it should.

A layer of indirection could be introduced to solve some of the problems you describe, e.g. an entity group of "red" could be internally mapped to a group of "entity_red", and an edge group of "red" could be mapped to "edge_red". A map from these forms to the appropriate serialisers, aggregators, could be derived from the schema and could then be used for all the necessary look-ups. When recreating elements from the key-values, the "entity_" or "edge_" could just be dropped.

**Comment by p013570** [comment]
After some discussion we think that we will leave the restriction on unique groups for the time being. 

gh-219 will allow users to create a propertyGroup and reuse that propertyGroup across multiple element groups. Using the "red" example above, it would be up the user to create a propertyGroup called "red" then create an entity group called "entity_red" and an edge group called "edge_red" that both includes the properties from "red".
