### ISSUE TITLE
Create a ExportToLocalFile Operation 

### ISSUE THREAD

**Issue by p3430233** [gchq/Gaffer#2707]
Create a ToFile operation that writes an Iterable of strings to a CSV file

**Comment by n3101** [comment]
@p3430233  - in what file format? Just Linux?

**Comment by t92549** [comment]
As a useful follow on from https://github.com/gchq/Gaffer/issues/2675, an [ExportTo](https://github.com/gchq/Gaffer/blob/580cf2bb045a8a8fee5803597310243b0cd08b50/core/operation/src/main/java/uk/gov/gchq/gaffer/operation/export/ExportTo.java) Operation should be created called ExportToLocalFile. This will take an iterable of Strings (like created by ToCsv) and save it to a local file. This is a useful operation for local data science work with Gaffer.

**Comment by t92549** [comment]
We should ensure this works "lazily", i.e. it will iterate through results and write them as they come in (perhaps in bulk), so files larger than available memory can be written.
Tests for this should be made.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2729
