### ISSUE TITLE
Move integration tests from test to main

### ISSUE THREAD

**Issue by r32575** [gchq/Gaffer#2708]
At present the integration tests are part of `integration-test/src/test`. With the raising of issue #2654 unit tests are required to test integration test extensions. However, at present this would mean that the unit tests would be bundled up with the integration tests which is undesirable. Therefore, we should move the integration tests to main and alter dependencies.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2715
