### ISSUE TITLE
Improve code analysis CI in Gaffer

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2722]
https://github.com/gchq/Gaffer/issues/39 added [FindBugs](https://gleclaire.github.io/findbugs-maven-plugin/) to Gaffer. FindBugs is no longer maintained and has been replaced by [SpotBugs](https://spotbugs.github.io/spotbugs-maven-plugin/).

This could be upgraded, or a more modern tool could be used to replace this entirely.
For example: 
- [CodeQL](https://codeql.github.com/)
- [semgrep](https://semgrep.dev/)
- [Codacy](https://github.com/marketplace/codacy)
- [sonarqube](https://www.sonarqube.org/)

Some of these would also replace the need for other plugins such as checkstyle and code coverage as they handle those too.

**Comment by lb324567** [comment]
Some work has been done on this ticket to identify the best tools going forward, but further work on this ticket is currently on hold.

**Comment by lb324567** [comment]
SonarQube is the likely solution to this, but will need checking when this ticket is progressed. For more information see internal tool- number 301

**Comment by GCHQDeveloper314** [comment]
#2871 introduces the PMD plugin which performs further static analysis and code quality checks. It also enables GitHub's CodeQL security scanning. This issue can probably be closed once this has been merged.

To an extent these extra checks replace the checkstyle plugin, although they don't replace the code style checks. These could be replaced by the Spotless plugin formatting checks mentioned above, but this would also require major refactors to get the codebase to comply and so it's probably easier to leave this for now.

**Comment by GCHQDeveloper314** [comment]
Closed by #2871
