### ISSUE TITLE
Relocations missing/incorrect in shaded JARs

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#2748]
When releasing Gaffer 2.0.0-alpha-0.3 in gaffer-docker, there was a problem with the `operation-runner` not finding certain classes and using the wrong version of Jackson. Fixing this requires changes to Gaffer.
The missing classes are caused by the relocation for `org.apache.commons:commons-lang3` ([introduced in alpha 2](https://github.com/gchq/Gaffer/blame/c13799142dd2c5900bbbf4ccf83752efa842d8a4/store-implementation/accumulo-store/pom.xml#L215)) actually covering all of `org.apache.commons` (instead of just `lang3`) and the wrong Jackson version is caused by this relocation being applied only to the iterators JAR and not to the libraries (`time`,`bitmap`,`sketches`) which also use Jackson. For Jackson this caused a version clash with classes from the iterators JAR using a different version (which had been relocated and supplied in the shaded JAR) to the libraries JAR (which had not been relocated and so used the version supplied by Accumulo). For reference, the Jackson relocation is required because Accumulo 2 supplies a different version of Jackson to Gaffer. Accumulo 1 didn't use Jackson so this problem did not occur prior to Accumulo 2 support being added.

Normally when relocating a class in a shaded JAR, the relocated classes would be included inside that shaded JAR. This increases the size of the JAR significantly. In the past it was decided the [shaded JARs for these libraries would only be used in combination with the iterators JAR](https://github.com/gchq/Gaffer/issues/1402#issuecomment-359412402). This allows the relocated classes to be supplied by that JAR and not included in each of the libraries JARs.

In addition to `time`,`bitmap` & `sketches`, there are other shaded JARs, some of which might need similar changes to the above to work correctly with Accumulo 2.

**Comment by t92549** [comment]
Fixed by https://github.com/gchq/Gaffer/pull/2746
