### ISSUE TITLE
Run E2E tests before release

### ISSUE THREAD

**Issue by lb324567** [gchq/Gaffer#2754]
Within gaffer-docker there are some E2E tests, although they are labelled as IT tests. Ideally we should run these before we do a release, to try to ensure that we haven't broken anything in the release. 
We should either move the tests over into this branch, or find a way to run the tests from another branch on this branch.

**Comment by GCHQDeveloper314** [comment]
#2801 is a near duplicate of this. Only difference being that it is not specific to release, but would run for all PRs. It would therefore also run for release. Closing this as a duplicate.
