### ISSUE TITLE
Integration tests:  Re-add  singleTest option

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2758]
Undoing the  deletion of code from gh-2498 will allow one IT test to run; which is useful when working on failing tests, instead of having to run the entire lot which takes +15mins.

Class: AbstractStoreITs

``` java
    public void singleTest(final Class<? extends AbstractStoreIT> testClass) {
        singleTest(testClass, null);
    }

    public void singleTest(final Class<? extends AbstractStoreIT> testClass, final String testMethod) {
        this.singleTestClass = testClass;
        this.singleTestMethod = testMethod;
    }
```

**Comment by n3101** [comment]
@GCHQDev404 What is this for? Priority?

**Comment by GCHQDev404** [comment]
Allows one IT test to run, when working on failing tests, instead of the entire lot which takes +15mins.
Priority medium-low.

**Comment by GCHQDev404** [comment]
Add this to the ITs test and change it to the IT you want ".*SpecificThingIT"
`@IncludeClassNamePatterns(".*IT")`
