### ISSUE TITLE
Enable Graph deletion by age

### ISSUE THREAD

**Issue by n3101** [gchq/Gaffer#2759]
Make it possible to delete a graph older than a specified creation date. Gaffer graphs do not natively store information about their creation date. 

Some users are hacking this by adding a bogus element that stores the creation date. 

For AccumuloStores, table information may provide this information, but a solution based on this will not necessarily work for other stores. 

For federatedstore, @GCHQDev404 said: 'The solution is likely the "Graph of Graphs" to be included in FederatedStore. This is on my list of things todo. this does not exist currently yet.'

A property added to all graph types might be preferable.

**Comment by t92549** [comment]
Possibly same as https://github.com/gchq/Gaffer/issues/2839

**Comment by n3101** [comment]
@t92549  I agree we don't need both issues, but please note this issue is not exactly the same as #2839. The latter is specifically aimed at subgraphs of FederatedStore, but this one also relates to a standalone graph. Please ensure that 2839 covers that as well. Also I suppose - if a standalone graph is later added to a federation, ensure the federation can access the new subgraph's age.
