### ISSUE TITLE
FederatedStore: default Merge Mapping

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2761]
continuation of  #2357

Add a default mappings of what merge function to be used for each operation.

This is should include a mapping for getElements which re-applys views. this defeats an issue with:
```
graphA with entityA count 6
graphB with entityA count 11
graphC with entityB count 7
graphD with entityC count 4

getAllElements with view count less than 10

result should be empty
```

**Comment by GCHQDev404** [comment]
Blocked by failing test.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2797
