### ISSUE TITLE
FederatedStore: Review and test "isDisabledByDefault"

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2764]
**UPDATE: We have now decided that isDisabledByDefault will be removed from Gaffer. As such this ticket is now to delete isDisabledByDefault;**

Class: FederatedStoreDefaultGraphsTest
Add tests and examine the interaction between `isDisabledByDefault` and `StoreConfiguredGraphIds` List
Add tests and examine the interaction between `isDisabledByDefault` and `getGraphs` with Admin privilege.

---

Class: FederatedGraphStorage
Method: GetStream
Line: ~331 `.filter(entry -> !entry.getKey().isDisabledByDefault())`
Review the requirement, usage and test coverage of isDisabledByDefault.

----

Class: FederatedStore
Method: GetDefaultGraphs
line: ~ 549 `if (isNull(adminConfiguredDefaultGraphIdsCSV) || isAdminRequestingOverridingDefaultGraphs) {`
Review the interaction, usage and test coverage with `isDisabledByDefault`. is disabled logic preserved or is it required. 

---

Class: FederatedGraphStorageTest
Method: shouldGetDisabledGraphWhenGetAll
line: ~217
disabledByDefault access is used, but `getAll()` has auths parameter so when and why is it disabled?

---
Class: FederatedGraphStorageTest
Method: shouldNotGetDisabledGraphForAuthUserWhenNoIdsProvided
line: ~287
examine the use of `null` why is it only missing when `get(null)`

**Comment by GCHQDev404** [comment]
I suspect that isDisabledByDefault is not required and can be deleted from Gaffer. due to `FederatedStore.storeConfiguredGraphsIds`.

**Comment by lb324567** [comment]
Completed by #2834
