### ISSUE TITLE
FederatedStore: Determine whether FederatedOperation should implement GenericInput<INPUT> 

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2765]
The `GenericInput` abstract class is used by other Gaffer Operations that could have an input of unknown types:
https://github.com/gchq/Gaffer/blob/72240c4ee982203fa6ea36be5152f98b50fca9fb/core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/If.java#L71

Determine whether the new FederatedOperation class should extend this also.
If "yes": would this be a breaking change that needs to be addressed in Gaffer 2.0? If not, then put an issue on the post-2.0. backlog.

https://github.com/gchq/Gaffer/blob/bf75e8da67310a514f6408a2c910366d949811a7/store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperation.java#L64

Likely test condition:  

- Write a `FederatedOperation` with a payload of `If` and another with `While` (which are both GenericInputs)
- Supply the FederatedOperation with an input.
- JSONSerialise the objects and see if you can trigger exceptions described in `GenericInput`

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2826
