### ISSUE TITLE
FederatedStore: Review and test "userRequestingDefaultGraphsOverride"

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2766]
Class: FederatedOperation
Field: userRequestingDefaultGraphsOverride
Line: ~75
Examine the usage and need of this field but Primarily document and confirm if the following is true or false.
That the usage/need of this field is to override the usage of defaultGraphs (superseded by `FederatedStore.ConfiguredGraphIds`) and instead return all graphs without having to manually list all the graphIds.

...Because the user can "long hand" list all the graphId, is this field and logic unnecessary for amount logic required to support it.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2833
