### ISSUE TITLE
FederatedStoreCacheBackwardCompatibilityTest is unclear

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2768]
Class: FederatedStoreCacheBackwardCompatibilityTest
Field: `MAP_ID_1`
Field: `ADDING_USER_ID`
line: ~43
Why does changing either of these field values cause the test to fail?

**Comment by GCHQDev404** [comment]
Reference to https://github.com/gchq/Gaffer/pull/2769 changes

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2780
