### ISSUE TITLE
Enable the TinkerPop implementation to connect to a Gaffer rest api

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#277]

**Comment by okram** [comment]
I would recommend binding it via the Java API. That is, implement the following interfaces in TinkerPop:

Graph: https://github.com/apache/tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java
Vertex: https://github.com/apache/tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Vertex.java
VertexProperty: https://github.com/apache/tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/VertexProperty.java
Edge: https://github.com/apache/tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Edge.java
Property: https://github.com/apache/tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Property.java

That is about 90% of the effort required. After that, to make things solid:

1. Connect it to the `StructureStandardSuite` and `ProcessStandardSuite`. You can see how this is done via TinkerGraph: https://github.com/apache/tinkerpop/blob/master/tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphStructureStandardTest.java and https://github.com/apache/tinkerpop/blob/master/tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/process/TinkerGraphProcessStandardTest.java

2. Add a `TraversalStrategy` to use index lookups. I assume you have fast lookups for stuff like "get me all vertices with name 'marko'." If so, then you will need something like `TinkerGraphStepStrategy` (https://github.com/apache/tinkerpop/blob/master/tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/strategy/optimization/TinkerGraphStepStrategy.java) where your `GafferGraphStep` implementation will use the `HasContainers` accordingly to do index lookups -- e.g. `g.V().has('name','marko')`.

That is really all there is to it. I suspect a solid 1 week effort and you will then be able to use Gremlin to query your graph.

http://tinkerpop.apache.org/gremlin.html

Hope that helps.

**Comment by p013570** [comment]
Thanks again for your help. As you saw we have a very basic implementation over in the [Gaffer Tools Repository](https://github.com/gchq/gaffer-tools). 

The current implementation was written just to investigate if and how it might be done and is still very much a prototype. Unfortunately we just haven't had chance to tidy it up and implement the extra bits. As you mentioned, we do really need to make use of TraversalStrategies to optimise it for Gaffer.

I'll close this issue and reopen a similar one in the gaffer tools repo with your ideas.
