### ISSUE TITLE
Make OperationDetails endpoint result sorted

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2775]
Currently, the operation details endpoint returns an unsorted Set: https://github.com/gchq/Gaffer/blob/2bb2ee977049d39381ea314691161d9c08615bfa/rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/AbstractOperationService.java#L63
This means each rest-api will return the results in a different order and this causes inconsistent results. This is especially problematic for the fishbowl generated python code.
I suggest that this be a sortable Set returned, perhaps a TreeSet, and the Set is sorted alphabetically on Operation name.

**Comment by t92549** [comment]
This would probably require changes to koryphe's `ReflectionUtil.getSubTypes`

**Comment by GCHQDeveloper314** [comment]
It was also suggested that the new endpoint to fetch all operations (#2836, now merged) should be sorted. However, the PR for this was merged without sorting included, as the need for sorting is yet to be agreed under this issue.

I don't believe that sorting the results returned by these endpoints will deliver any benefit to Gaffer. The results will vary depending on what operations are included on the classpath. Custom operations could appear anywhere in list if sorted by name. This would presumably cause the same problem with fishbowl generated code.

I think the results from Gaffer REST should be sorted as part of the fishbowl Python code. This could then involve additional handling for custom operations, e.g. those with a non-gaffer package name always placed at the end of the sorted list to improve consistency of the generated code.

I suggest this issue be closed and replaced with an issue to add sorting to fishbowl in the Gafferpy repo.

**Comment by t92549** [comment]
I agree with @GCHQDeveloper314, it doesn't make too much sense to sort these and clients can handle the response how they wish
