### ISSUE TITLE
Add GitHub issue templates

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2776]
Adding some templates for bugs and new features will help new issues be focused and detailed

**Comment by n3101** [comment]
@t92549 Just noticed that this alpha4 issue has been closed as completed by a PR that merged to Develop. ??

**Comment by GCHQDeveloper314** [comment]
The templates needed to be added to the develop branch because that branch is what GitHub uses for this. They will be moved into the v2-alpha branch along before 2.0.0 is released. @t92549 has been working on this.

**Comment by t92549** [comment]
This should have been tagged as 1.23.0 but will be in v2-alpha soon so shouldn't matter too much

**Comment by n3101** [comment]
@t92549 As you've got it covered - that's fine
