### ISSUE TITLE
FederatedStore DiscardOutput should not be wrapped 

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2819]
**Describe the bug**
In `FederatedStore.addAdditionalOperationHandlers` there is forEach to have `!Output` operations handled by `FederatedNoOutputHandler`. It is very likely `DiscardOutput` should be added to the filter. 

**Expected behavior**
`DiscardOutput` happens locally on the FederatedStore otherwise it can be sent to sub-graphs inside a `FederatedOperation`.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2820
