### ISSUE TITLE
FederatedStore auto no output handler

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2821]
**Describe the bug**
similar to #2819 following operations are auto handled by NoOutputHandler which means you can't preform these locally on a FederatedStore. The foreach loop needs to be removed, these can still be sent to subgraphs within a FederatedOperation.

- DeleteNamedOperation
- DeleteNamedView
- CancelScheduledJob
- SetVariable
- ImportCsv
- DeleteNamedOperation
- DeleteNamedView

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2822
