### ISSUE TITLE
Provide an alternative implementation of hyperLogLogPlus not reliant on the Clearspring library

### ISSUE THREAD

**Issue by n3101** [gchq/Gaffer#2825]
**Describe the new feature you'd like**
Provide an alternative implementation of HyperLogLogPlus.

**Why do you want this feature?**
HyperLogLogPlus uses the Clearspring library which was archived in 2019. We are not even using the most recent version.
Provide a supported implementation of HyperLogLogPlus.

**Describe alternatives you've considered**
The Datasketches library provides an alternative implementation. We already use Datasketches in other places. 

**Additional context**
Existing HyperLogLogPlus data may not be readable by Datasketches - in which case it may be necessary to retain Clearspring for this data. If so, at least up-version Clearspring as far as possible, but deprecate its use for new applications. 

Check to see whether we use Clearspring in any other places that need similar treatment

**Comment by t92549** [comment]
We already have the support Datasketches' [`HllSketch`](https://github.com/gchq/Gaffer/blob/a91ce4cd1e04dd0a2dfdf9633b513768fccd3507/library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/binaryoperator/HllSketchAggregator.java#L31) in Gaffer and this is the recommended sketch to use.

**Comment by n3101** [comment]
@t92549 Well if there is already an alternative technology available then why did the recentish work by @r32575 use the Clearspring library? Please can we have suitable issues to:

-  deprecate ClearSpring (if that hasn't already been done)
- ensure recent features covered by replacement tech
-  manage any migration necessary from Clearspring 
-  eventually remove ClearSpring
