### ISSUE TITLE
Create /graph/operations/all endpoint

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2836]
**Describe the new feature you'd like**
A `/graph/operations/all` endpoint should be added to return all operations on the classpath.

**Why do you want this feature?**
The `/graph/operations/details/all` was added to return the details of all operations on the classpath, but sometimes users don't want details, just the name of the operations.

**Additional context**
It would be nice if the endpoint returned them sorted alphabetically (see https://github.com/gchq/Gaffer/issues/2775).
For implementation, see the `/graph/operations/details/all` endpoint.

**Comment by ibrijesh** [comment]
HI , Ian interested in contribution, I have already build the project using  mvn clean install -Pquick command , I wanted to know how to run these api end point.

**Comment by GCHQDeveloper314** [comment]
Note that as with #2690 this is only for spring-rest.
