### ISSUE TITLE
Create endpoint to get Gaffer version

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2837]
**Describe the new feature you'd like**
An endpoint added to the rest api to get the api's Gaffer version

**Why do you want this feature?**
Swagger does give this information but with the upgrade to swagger version, how to get it is inconsistent. It is important to know what Gaffer version an api is running and therefore it would be better if this was provided by the api.

**Additional context**
This should probably be added to both the spring-rest and core-rest

**Comment by GCHQDev404** [comment]
Its unfortunate but upon inspection of the PR the ticket is not correct.
The version should be accessed via Operation. So it is then supported in a Federated System with multiple stores/graphs.
