### ISSUE TITLE
Create endpoint to get store type

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2838]
**Describe the new feature you'd like**
An endpoint that would tell you what type of store you are querying.

**Why do you want this feature?**
Currently it is not possible to know if the graph you are querying is backed by a FederatedStore, an AccumuloStore, a ProxyStore or a MapStore. You can still ask what operations are available, but sometimes it is useful to know the store type.

**Additional context**
The entire store properties cannot be returned as they can contain information that should not be seen by users.

**Comment by GCHQDeveloper314** [comment]
What if we want to know what type of graph is the final backing graph? For example in the setup below this would return ProxyStore but I'm not sure how useful that is.

```mermaid
graph LR;
    User-->NearProxyStore;
    NearProxyStore-->FederatedStore;
    FederatedStore-->FarProxyStore;
    FarProxyStore-->AccumuloStore;
```

I think if we wanted to know the kind of remote store, then a new Operation would be required. This could be a follow up issue, not something to be done under this issue.
