### ISSUE TITLE
Implement gaffer accumulo exporter to export to a different table

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#284]
Implement an exporter to allow elements to exported to a different accumulo table.

**Comment by flitte** [comment]
Since you have opened issues for supporting alternative Store types - is the intention that this could also be used to transfer data between stores?

**Comment by p013570** [comment]
This exporter was intended to just export elements to a different accumulo table on the same instance of accumulo. Therefore, it would be able to use the same accumulo login details and gaffer schema. 

Exporting elements to a different Gaffer store is a bit more complicated and we will tackle that in a separate issue - we have just created issue gh-287 to do it.

**Comment by p013570** [comment]
This will be done as part of gh-287.

**Comment by p013570** [comment]
Merged into develop as part of #287.
