### ISSUE TITLE
Upgrade Spotbugs configuration

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#2841]
**Describe the new feature you'd like**
Spotbugs is currently used but the configuration has not been changed from when Findbugs was being used. It should be updated and improved - as mentioned in #2722 . The POM configuration could also allow for the complimentary PMD plugin to be used.

**Why do you want this feature?**
To improve static analysis for the project.

**Comment by GCHQDeveloper314** [comment]
The complimentary PMD plugin has been tested as part of this issue but it requires many minor changes to bring the codebase up to standard. To keep this issue manageable, any PMD plugin should be done under a separate issue and is now out of scope for this issue.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2842
