### ISSUE TITLE
Cache Exceptions usage and review

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2865]
**Describe the bug**
Following #2319 The caches now share a parent class `Cache`. However this combined the need for certain Exceptions to be thrown and required by some test. These Exceptions need to be reviewed. One example is a test to for when a Key is not found in the Cache an Exception is thrown. Keys not being found in a cache is not "exceptional behaviour".

**Comment by GCHQDev404** [comment]
Awaiting all cache PR to be approved

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2925
