### ISSUE TITLE
FederatedStore add port option to RealFederatedStore

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2866]
**Describe the new feature you'd like**
Add port number option to the real federatedstore example.

**Why do you want this feature?**
This will allow having multiple rest running locally.

**Comment by GCHQDev404** [comment]
### Migration Required

DEFAULT_GAFFER_CONTEXT_ROOT = "/rest"

If you want the old style of context add `"gaffer.context-root": "/rest/v2"` to you proxy properties

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2867
