### ISSUE TITLE
Refactor CSV Import/Export to use generators over formats, including bespoke OpenCypher formats

### ISSUE THREAD

**Issue by t11947** [gchq/Gaffer#2873]
- [x] Delete unused ToOpenCypherCsv
- [x] Review test names, refactor where needed
- [ ] General cleanup of metadata (File attributes, licensing, javadoc etc) + naming
- [ ] Remove csvFormats, refactor OpenCypher formats into supplied generators
- [ ] Investigate removing CsvToElements and using a more generic GenerateElements

These changes will streamline the CSV import/export feature set and should allow for easier maintainence in the future. Removal of some of the more bespoke elements will lower the technical overhead for future maintainers.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2943
