### ISSUE TITLE
FederatedStore FederatedOperationHandler loosing inputs of operations

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2875]
**Describe the bug**
The FederationOperationHandler is loosing inputs of operations. This stops things likes AddElements from remotely working.

**To Reproduce**
1. Set up a Rest Service FederatedStore with a MapStore
2. Set up a second Rest Service FederatedStore with a proxy to the first.
3. Add elements from the second FederatedStore

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2876
