### ISSUE TITLE
Improve Javadoc for getSchema and remove deprecation

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#2882]
**Describe the new feature you'd like**
Improved Javadoc for all schema related methods (at least in `Graph` and `Store`). Removal of deprecated annotation which was previously added as the `getSchema` method cannot be removed and so should not be marked as deprecated - see comment in #2791.

**Why do you want this feature?**
The `getSchema` and `getOriginalSchema` methods have different purposes. The Javadoc for these and methods which call them could be made clearer.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2883
