### ISSUE TITLE
Integration Tests schema has a groupby value that does not exist in the properties

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2885]
**Describe the bug**
The Integration Tests schema has an oddity where an Entity has groupby value that does not exist in the Entity definition.

Does or will this cause issues or unwanted behaviour in the IT test?

```json
"BasicEntity" : {
      "vertex" : "id.string",
      "properties" : {
        "count" : "prop.count",
        "setProperty" : "prop.set.string"
      },
      "groupBy" : [ "intProperty" ]
}
```

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2899
