### ISSUE TITLE
FederatedStore Double Cache Persistence bug

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2887]
**Describe the bug**
If a Rest Service FederatedStore is started and a sub-FederatedStore is added. The sub store could be added with no persistent cache. This would cause the sub-FederatedStore to become unusable. due to being fetched from cache-built-used each time and retains no information.

If a Rest Service FederatedStore is started with No persistent cache, a sub-FederatedStore could be created with A persistent cache.

**Comment by GCHQDev404** [comment]
This may have all been fixed by the implementation of https://github.com/gchq/Gaffer/issues/2890

**Comment by GCHQDev404** [comment]
This has been fixed.

1. The Cache is no longer splatted by an AddGraph.
2. The inner federated store which built from cache repeatedly, has its info persisting in cache, because the Outter FederatedStore is keeping the light on for the Cache Service in JVM.

This was revealed by the Federation Recursion test after #2890

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2904
