### ISSUE TITLE
Cache Service Static Instance Bug

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2890]
**Describe the bug**
Cache service is Static, which means that any attempt to use a new cache can wipe/swap the cache.
This is horrendous for FederatedStore which uses the cache to store graphs. This is an Ancient bug but since the internal GraphStorage java object has been removed since #2595 this bug has appeared during docker containers testing.

Truth Table of error and behaviour below.

**To Reproduce**
  | AddGraph with no Cache | AddGraph with HashMap Cache | AddGraph with JCS Cache
-- | -- | -- | --
FederatedStore is currently using HashMap Cache | Graph is added to HashMap Cache | The Cache service continues to be HashMap Cache, the cache is initialised, FederatredStore only contains this new graph. | The Cache service is switched to JCS Cache, the cache is initialised, JCS cache is loaded from disc, FederatredStore contains this new graph and anything pre-existing in the cache.
FederatedStore is currently using JCS Cache | Graph is added to JCS Cache | The Cache service is switched to HashMap Cache, the cache is initialised, FederatredStore only contains this new graph. | The Cache service continues to be JCS Cache, the cache is initialised, JCS cache is loaded from disc, FederatredStore contains this new graph and anything pre-existing in the cache.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2893
