### ISSUE TITLE
Reintroduce Backwards compatibility cache tests.

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2895]
**Describe the new feature you'd like**
Backwards compatibility tests for version 1.12 was deleted  because the backwards compatibility is not required due to this being a v2 upgrade. 

A new compatibility tests for v2 should be added just before release final release.

examine branch https://github.com/gchq/Gaffer/tree/gh-2895-reintroduce-backwards-compatibility-cache-tests
and make a persistent cache to pass those test.

**Comment by GCHQDev404** [comment]
Awaiting all cache PR to be approved

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2937
