### ISSUE TITLE
AccumuloStore.Initialise does not set OriginalSchema

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2900]
**Describe the bug**
AccumuloStore.Initialise does not set OriginalSchema. It only set when GraphBuilder is used.

This is blocking #2580 

examine: 
https://github.com/gchq/Gaffer/blob/ca465ec9243c7ed981528379e351bddeae8d5c83/store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/AccumuloStoreTest.java#L116

**To Reproduce**
1.  in [#2580 branch](https://github.com/gchq/Gaffer/tree/gh-2580-dynamic-schema-removal), run `testAbleToInsertAndRetrieveEntityQueryingEqualAndRelatedGaffer1`
2. place a break point in GetSchemaHandler.

**Additional Info**
Unless OperationChainValidator.getSchema should get compact schema always?  in [#2580 branch](https://github.com/gchq/Gaffer/tree/gh-2580-dynamic-schema-removal)

**Comment by GCHQDeveloper314** [comment]
This is not a bug. The `AccumuloStore.initialise` method overrides the parent method from `Store`. While the `Store` class does contain the field `originalSchema`, it is used only for a getter/setter. The `originalSchema` field is actually used and configured in the `Graph` class.

If a new store is created directly and not via creating a new graph, then `originalSchema` will not be set. That can cause issues in some cases. Ideally when testing new graphs should be created and not stores.

This issue itself (and the problem in #2580) is unrelated and has been fixed as part of 2901. Regarding the "additional info" question about if `OperationChainValidator.getSchema` should always get compact schema, the answer is yes. That method calls `getSchema` in store which does always get the "compact schema" - aka the schema actually used by the store (`schema` field in `Store`) - not the copy of the user supplied schema "originalSchema".
