### ISSUE TITLE
Fix FederatedStore cache collision

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2903]
**Describe the bug**
When using the same cache implementation in a FederatedStore, the caches will collide.

**To Reproduce**
1. Create a FederatedStore
2. Add GraphA with a cache
3. Add GraphB with a cache (same cache implementation)
4. Add a NamedOperation to GraphA (NamedOperations are stored in the cache)
5. List NamedOperations in GraphB - it will be visibile even though it should not be

**Suggested solution**
All graphs require suffix usage, similar to FederatedGraphStroage Cache.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2907
