### ISSUE TITLE
Remove redundant constants class

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#2914]
The class `CommonConstants.java` has two static fields. One is unused and the other (`UTF-8`) is used in various places in Gaffer but can be replaced with an equivalent Java builtin.

Remove this class and replace references to its field with the equivalent Java builtin.

**Comment by ibrijesh** [comment]
I am interested in contributing, Could you please assign me this task?

I would like to clarify the following changes that need to be made:

1.Remove the file named **CommonConstants.java**.
2.Replace the line import **uk.gov.gchq.gaffer.commonutil.CommonConstants;** with  **import java.nio.charset.StandardCharsets;**.
3.Replace all instances of **CommonConstants.UTF_8** with **StandardCharsets.UTF_8**.

**Comment by GCHQDeveloper314** [comment]
Yes that is correct. You may also need to ensure the import order is correct after replacing the old import, as we have checkstyle rules for enforcing a clean order. You can run the checkstyle checks without needing to do a full build and test of the codebase by using `mvn checkstyle:check`.

**Comment by ibrijesh** [comment]
When i am runniing this command **mvn checkstyle:check** I am getting below error

![Screenshot from 2023-03-07 14-36-30](https://user-images.githubusercontent.com/41025295/223375408-e048f580-b328-45cf-abb6-f14820f555a8.png)

**Comment by GCHQDeveloper314** [comment]
It looks like you will need to run `mvn clean install -Pquick` first, in order to build the project dependencies.

**Comment by GCHQDeveloper314** [comment]
Java 8 is required for Gaffer 1.22 versions. If you need to use Java 11 then checkout the `v2-alpha` branch and use that instead of the default `develop` branch. The `v2-alpha` branch is where we are doing development for Gaffer 2.0 and it supports Java 11.

**Comment by ibrijesh** [comment]
I have succefully build project dependencies **mvn clean install -Pquick**  but changes in code failing **mvn checkstyle:check** . What rules i have to follow  while making changes ?

**Comment by GCHQDeveloper314** [comment]
When running the checks a list of checkstyle rule failures will be shown for each module which is failing. These are not summarised at the end, so you'll need to scroll up in order to see them. It may be easier to run the checks on the individual modules you've modified by using the `-pl :module-name` flag (e.g. `-pl :store`). You could also open a draft PR which will show us any checkstyle issues as part of our GitHub actions checks.
