### ISSUE TITLE
Improve StoreProperties comments

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2947]
`* This is used.... ` seems to be leftover by mistake, there should be actual explanation here:
https://github.com/gchq/Gaffer/blob/7a2e2bad7aa9b09f787fbdc9bd8c2b93c2e133da/core/store/src/main/java/uk/gov/gchq/gaffer/store/StoreProperties.java#L77-L88

**Comment by GCHQDeveloper314** [comment]
This file also needs fixing:

https://github.com/gchq/Gaffer/blob/b8fd95d82f270d5f5332f347e4b1d6d05108d43e/store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreProperties.java#L31-L38
