### ISSUE TITLE
Performance testing of tinkerpop

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2993]
We should test the performance of querying Gaffer with gremlin and compare it to equivalent OperationChains. This should be done for a variety of query types, schemas, and graph sizes. We should then share the tests and results. This would help us inform users (via documentation) on the best use cases for gremlin vs. OperationChains.
I am not sure whether these performance tests should live in core Gaffer or elsewhere.

**Comment by GCHQDeveloper314** [comment]
See also #3027
