### ISSUE TITLE
The federated merge function 'ApplyViewToElementsFunction' does not serialise

### ISSUE THREAD

**Issue by tb06904** [gchq/Gaffer#3025]
**Describe the bug**
When running a `GetAllElements` or `GetElements` operation on a federated store using the REST API a server 500 error occurs. As these now use the `ApplyViewToElementsFunction` by default it appears to be the issue as a google guava type cannot be serialised.

**To Reproduce**
Run a `GetAllElements` operation on a federated graph via the REST API.

**Expected behavior**
The operation returns a federated list of elements

**Stack trace and errors**
Error output:
```json
{
    "statusCode": 500,
    "status": "Internal Server Error",
    "simpleMessage": "uk.gov.gchq.gaffer.exception.SerialisationException: (was java.lang.UnsupportedOperationException) (through reference chain: uk.gov.gchq.gaffer.federatedstore.operation.FederatedOperation[\"mergeFunction\"]->uk.gov.gchq.gaffer.federatedstore.util.ApplyViewToElementsFunction[\"requiredContextValues\"]->com.google.common.collect.RegularImmutableSet[3])"
}
```

**Additional context**
Likely due to missing Jackson module to help serialise the guava types. Adding the [Jackson datatype for guava](https://github.com/FasterXML/jackson-datatypes-collections/tree/master/guava) should hopefully fix it.

May also need to add the tag to the relevant method:
```java
@JsonDeserialize(as = ImmutableSet.class)
```

**Comment by GCHQDeveloper314** [comment]
I'd suggest investigating if we need to use this Guava type or if a regular Java 8 type would work instead. It if it did and that fixed this error then it would be a preferred solution.

Most of the uses of Guava in Gaffer are not needed and seem to be an artifact of pre-Java 8 design. Once Gaffer moves to supporting only Java 11, Guava could probably be removed entirely. As such, we should avoid introducing code reliant on Giava if this can easily be avoided.

**Comment by tb06904** [comment]
> I'd suggest investigating if we need to use this Guava type or if a regular Java 8 type would work instead. It if it did and that fixed this error then it would be a preferred solution.
> 
> Most of the uses of Guava in Gaffer are not needed and seem to be an artifact of pre-Java 8 design. Once Gaffer moves to supporting only Java 11, Guava could probably be removed entirely. As such, we should avoid introducing code reliant on Guava if this can easily be avoided.

Good point if we were using Java 9+ then this could be fixed by using a `Set.of()` which would produce the required immutable set as is I think Java 8 can use `Collections.unmodifiableSet()` instead so might be a better fix.
