### ISSUE TITLE
Change configuredMergeFunctions to storeConfiguredMergeFunctions

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#3038]
There is a typo where the json `storeConfiguredMergeFunctions` properties are incorrectly `configuredMergeFunctions`:
https://github.com/gchq/Gaffer/blob/b15958424d26a5fbd4b6dada7fd6694c09f8a30d/store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/FederatedStoreUtil.java#L400

**Comment by GCHQDeveloper314** [comment]
We probably should have kept the typo but as deprecated. This is now a breaking change between 2.0.0 and 2.1.0

**Comment by t92549** [comment]
> We probably should have kept the typo but as deprecated. This is now a breaking change between 2.0.0 and 2.1.0

There are already breaking changes so I think we should try and put them all in 2.1.0 if possible
