### ISSUE TITLE
MergeSchema is ignoring SchemaExceptions

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#3045]
**Describe the bug**
When the `MergeSchema` class applies the `Schema.BaseBuilder.merge` function, it catches `SchemaException`s. This is because it will retry while ignoring vertex serialisers if the error is to do with vertex serialisers:
https://github.com/gchq/Gaffer/blob/e90fba0cb33ca23ab60cd1e2c175dfd29801fde1/store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/MergeSchema.java#L56-L65
However, if the `SchemaException` is unrelated to vertex serialisers, I would expect the exception to still be thrown:
```java
if (e.getMessage().contains(Schema.UNABLE_TO_MERGE_SCHEMAS_CONFLICT_WITH_VERTEX_SERIALISER_OPTIONS_ARE)) {
    // handle the vertex serialiser issue...
} else {
    // throw other types of SchemaException
    throw e
}
```
This is not the case.

**Additional context**
If you simply add this else block in, tests will start to fail. These tests are [FederatedStoreVisibilityTest](https://github.com/gchq/Gaffer/blob/e90fba0cb33ca23ab60cd1e2c175dfd29801fde1/store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreVisibilityTest.java) (issue: https://github.com/gchq/Gaffer/issues/1834) and [FederatedStoreSchemaOverlapTest](https://github.com/gchq/Gaffer/blob/e90fba0cb33ca23ab60cd1e2c175dfd29801fde1/store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaOverlapTest.java) (issue: https://github.com/gchq/Gaffer/issues/2767). These tests were added as part of Gaffer 2 development to codify the new FederatedStore behaviour, however, we did not realise this behaviour was happening as a result of a bug.

**Suggested fix**
`MergeSchema` should be fixed and extended to manage all types of SchemaException.
When a SchemaException happens due to conflicting visibility property names, this can probably be intentionally ignored with a warning message.
When a SchemaException happens due to conflicting types for the same property in the same group across two subgraphs, things are more complicated. Perhaps, if the type definitions are the same the error can be ignored, and if not they can be de-duplicated. 
This will likely need work on `Schema.BaseBuilder.validateSharedGroupsAreCompatible`

**Comment by GCHQDeveloper314** [comment]
If the concatenate merge function is used for a schema instead, then I assume this bug will not seen?
