### ISSUE TITLE
FederatedOperation field payload exposed to modifications.

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#3085]
**Describe the bug**
FederatedOperation now exposes internal field `payload` which can now be externally modified via `getOperations()` unlike the `getPayload()` operation

**Expected behaviour**
payload should not be able to be externally modified.

**Additional context**
since https://github.com/gchq/Gaffer/pull/3077 
see https://github.com/gchq/Gaffer/blob/4a437044f333c0b2af4dd6e69a31acfa651d0650/store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperation.java#L166-L168

**Comment by t92549** [comment]
Good catch, I missed this! Can probably be done as part of https://github.com/gchq/Gaffer/issues/3078
