### ISSUE TITLE
GafferPopGraph execute method doesn't catch certain exceptions

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#3125]
**Describe the bug**
When executing an Operation which is not supported, a `java.lang.UnsupportedOperationException` is thrown. This class is unrelated to the `uk.gov.gchq.gaffer.operation.OperationException` class which is caught by the `GafferPopGraph` catch clause.

These are the relevant lines:

https://github.com/gchq/Gaffer/blob/7b5e9ffa95602fb0ab4ae7b04610fd2e4c093d6f/library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java#L518-L523

This means that `UnsupportedOperationException` is not caught and handled as intended. The handling code could also be improved (e.g. log the error instead of just throwing).

**To Reproduce**
Steps to reproduce the behaviour:
1. Add breakpoint in the above catch.
2. Execute an Operation which is not supported by the configured store.
3. Catch is not invoked as it should be.

**Expected behaviour**
All kinds of Exceptions encountered when executing Operation(s) should be handled.

**Additional context**
The snippet above is not tested. Tests should be added for this to ensure correct behaviour.

**Comment by t92549** [comment]
Generally, the testing of `Store.doUnhandledOperation` isn't great
