### ISSUE TITLE
Update the GafferPop/Tinkerpop README to reflect current implmentation

### ISSUE THREAD

**Issue by tb06904** [gchq/Gaffer#3136]
Update the tinkepop readme.md with up to date information on the implementation.

It currently contains some possibly miss leading claims about features, continuing on from the work to integrate the test suite there should be a better idea of what is currently functional so the readme needs to reflect this.

**Comment by t92549** [comment]
This looks like it will also close https://github.com/gchq/Gaffer/issues/2992
