### ISSUE TITLE
Refactor NamedOperationCacheIT

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#3171]
**Describe the new feature you'd like**
Refactor of `NamedOperationCacheIT.java` to use JUnit correctly.

**Why do you want this feature?**
This class has a single `@Test` method which then proceeds to run multiple tests by manually calling methods. Instead, these should all be annotated as individual tests for JUnit to run itself. There are also some methods annotated as before and after which are simply run manually.

Use of `com.google.common.collect.Lists` should also be removed as it is unnecessary.

**Comment by nine03** [comment]
Hi, i want to work on this issue.
Could you assign this issue?

**Comment by GCHQDeveloper314** [comment]
We usually assign the issue after a PR has been opened against it. We always ensure the contributor is assigned to the issue before it is closed - this ensures the contribution is recorded in our release notes.

**Comment by nine03** [comment]
@GCHQDeveloper314 

com.google.common.collect.Lists
requirement says I should delete this. 
There are many places that use Lists.
Are you suggesting that I import and use org.assertj.core.util?

**Comment by GCHQDeveloper314** [comment]
That is an option, although `Arrays.asList()` is preferable to using AssertJ as it has been used elsewhere in the codebase.

**Comment by nine03** [comment]
I have resolved this issue and have created a pull request.
Could you kindly review and address it when you have the chance?
