### ISSUE TITLE
Bulk import to Accumulo store

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#328]
To bulk import data to a new table in Accumulo, the following steps are necessary:
- Estimate split points from a sample of the data you want to ingest.
- Create table.
- Set the split points on the table.
- Convert the data to rfiles of Accumulo keys and values.
- Hand those files to Accumulo.

To help bulk import data to a new graph backed by an Accumulo store, the following operations are provided:
- `SampleDataForSplitPoints` - this creates a file of split points.
- `SplitTable` - this splits a table but does not create the table.
- `AddElementsFromHdfs` - this creates the table if it does not exist, but does not add split points. It hands the data over to Accumulo.

To use these operations to bulk import to a new graph, it is necessary to run `SampleDataForSplitPoints`, then run `SplitTable`, then run `AddElementsFromHdfs`. This is overly complex, and not documented properly.

It should be possible to run one operation, which bulk imports data to a new graph - this operation should run all the above steps. Chaining the `SampleDataForSplitPoints`, `SplitTable` and `AddElementsFromHdfs` operations together should work. It would be useful to create one operation which runs all of these.

**Comment by p013570** [comment]
Although it makes it simpler for a user having just 1 operation to do all the above steps, if we did this for lots of different cases then we could end up with a huge number of operations which would be confusing. Perhaps we just need to improve the documentation and create an example operation chain in the examples section of the wiki.

**Comment by p013570** [comment]
Perhaps this is something that could be achieved via a named operation - gh-668.

**Comment by p013570** [comment]
OK, perhaps we could just update the AddElementsFromHdfs operation to delegate to SampleDataForSplitPoints and SplitTable operations first if the table has no split points already defined.

**Comment by p013570** [comment]
# Migration Steps

The following operations have been renamed:
- uk.gov.gchq.gaffer.accumulostore.operation.hdfs.operation.SampleDataForSplitPoints -> uk.gov.gchq.gaffer.hdfs.operation.SampleDataForSplitPoints
- uk.gov.gchq.gaffer.accumulostore.operation.hdfs.operation.SplitTable -> uk.gov.gchq.gaffer.operation.impl.SplitStore


These magic AddElementsFromHdfs operation options have been replaced with fields on the operation:
- accumulostore.operation.hdfs.use_accumulo_partitioner -> partitioner (if you wish to disable using a partitioner, you can set the partitioner class to uk.gov.gchq.gaffer.hdfs.operation.partitioner.NoPartitioner)
- accumulostore.operation.hdfs.use_provided_splits_file -> useProvidedSplits
- accumulostore.operation.hdfs.splits.file_path -> splitsFilePath
- accumulostore.operation.bulk_import.min_reducers -> minReduceTasks
- accumulostore.operation.bulk_import.max_reducers -> maxReduceTasks


If your Accumulo table has less than 2 splits (and more than 1 tablet sever) then when you do an AddElementsFromHdfs it will first sample the data and generate splits, set the splits on your table and then do the add from hdfs. It does this by delegating to the SampleDataForSplitPoints and SplitStore operations.

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
AddElementsFromHdfs example
-----------------------------------------------
See javadoc - [uk.gov.gchq.gaffer.hdfs.operation.AddElementsFromHdfs](http://gchq.github.io/Gaffer/uk/gov/gchq/gaffer/hdfs/operation/AddElementsFromHdfs.html).

This operation must be run as a Hadoop Job. So you will need to package up a shaded jar containing a main method that creates an instance of Graph and executes the operation. It can then be run with: 

```bash
hadoop jar custom-shaded-jar.jar
```

When running an AddElementsFromHdfs on Accumulo, if you do not specify useProvidedSplits and the Accumulo table does not have a full set of split points then this operation will first sample the input data, generate split points and set them on the Accumulo table. It does this by delegating to SampleDataForSplitPoints and class uk.gov.gchq.gaffer.operation.impl.SplitStore.

### Required fields
The following fields are required: 
- failurePath
- mapperGeneratorClassName
- inputPaths
- outputPath
- jobInitialiser


#### Add elements from hdfs

As Java:


```java
final AddElementsFromHdfs operation = new AddElementsFromHdfs.Builder()
        .addInputPath("/path/to/input/fileOrFolder")
        .outputPath("/path/to/output/folder")
        .failurePath("/path/to/failure/folder")
        .splitsFilePath("/path/to/splits/file")
        .workingPath("/tmp/workingDir")
        .useProvidedSplits(false)
        .mapperGenerator(TextMapperGeneratorImpl.class)
        .jobInitialiser(new TextJobInitialiser())
        .minReducers(10)
        .maxReducers(100)
        .build();
```

-----------------------------------------------

#### Add elements from hdfs main method

Example content for a main method that takes 5 arguments and runs an AddElementsFromHdfs

As Java:


```java
if (5 != args.length) {
    System.err.println("Usage: hadoop jar custom-hdfs-import-<version>-shaded.jar <inputPath> <outputPath> <failurePath> <schemaPath> <storePropertiesPath>");
    System.exit(1);
}

final String inputPath = args[0];
final String outputPath = args[1];
final String failurePath = args[2];
final String schemaPath = args[3];
final String storePropertiesPath = args[4];

final Graph graph = new Graph.Builder()
        .storeProperties(storePropertiesPath)
        .addSchemas(Paths.get(schemaPath))
        .build();

final AddElementsFromHdfs operation = new AddElementsFromHdfs.Builder()
        .addInputPath(inputPath)
        .outputPath(outputPath)
        .failurePath(failurePath)
        .splitsFilePath("/tmp/splits")
        .workingPath("/tmp/workingDir")
        .useProvidedSplits(false)
        .mapperGenerator(TextMapperGeneratorImpl.class)
        .jobInitialiser(new TextJobInitialiser())
        .minReducers(10)
        .maxReducers(100)
        .build();

graph.execute(operation, new User());
```

-----------------------------------------------
