### ISSUE TITLE
Range scans and comparators

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#346]
When given a pair of `EntitySeeds`, the `GetElementsInRanges` operation returns all elements containing a vertex that is between the first and second `EntitySeed`. In the `AccumuloStore` this requires the vertex serialisation to preserve the ordering of the vertices. However the store does not know if this is the case. And the vertices might not even be comparable.

In more detail, the issues are:
- It is possible to apply the `GetElementsInRanges` operation to data with vertices which are not comparable. In this case the operation is meaningless and should not be allowed.
- If the vertices are comparable then the store does not know if the serialisation preserves the ordering. For example, if the vertex is an integer then a fixed length serialisation might preserve the ordering, but a variable length one would not. The store is therefore unable to decide if it can safely apply the operation.
- Some vertex types are naturally comparable in more than one way. For example, a type-value pair could be comparable in two different ways - considering type first then value, or value first then type. In the first case, typeA|value1 < typeB|avalue2; in the second the opposite is true, i.e. typeB|avalue2 < typeA|value1. Different serialisers can be chosen to preserve the first ordering or the second ordering. In this case the store needs to know which comparator the user wants to use for the range scan, and it needs to know whether the serialisation respects this.

This situation will lead to user error as they execute a range scan without understanding the subtleties.

Note that arguing that the ordering should purely be based on the serialised value of the vertices ignores stores that do not need to serialise data and which can do range scans based on the actual ordering of the objects.

A possible solution is:
- If the vertex is not Comparable then refuse to run the operation.
- If the vertex is Comparable then `GetElementsInRanges` assumes that this is in respect of the ordering specified by the compare method on the vertex (unless an option says otherwise - see next item). If this is running on a store that serialises the vertices, it asks the vertex serialiser whether it preserves the ordering. If it does it runs the operation; if not then it refuses to run the operation.
- If `GetElementsInRanges` is called with an option which says a specific Comparator is intended to be used then the vertex serialiser is asked whether it preserves the ordering specified by that Comparator. It it does, it runs the operation; if it doesn't it refuses.

Note that this is linked to #268 - the default serialiser for a vertex that is an int should probably be one that respects the natural ordering of ints; the default serialiser for an int that is just a property should be `CompactRawIntSerialiser`.

**Comment by p013570** [comment]
For stores that use the vertex serialiser, there is a method on Serialisation called preservesObjectOrdering that can be used to check if the vertices can be used in range scans. If this method returns false then the range scan operation should not be allowed.

For store that don't use the vertex serialiser then we would have to check each seed in the operation is comparable. However, at the moment the range scan operations are specific to the Accumulo store so we could delay doing this part of work for now.

**Comment by p013570** [comment]
There is a validateOperationChain method in the Store class. Perhaps this could be overridden in AccumuloStore and the extra range operation validation could be applied..

**Comment by p013570** [comment]
Merged into develop.
