### ISSUE TITLE
FreqMap for longs

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#388]
The `FreqMap` class currently maps strings to integers. It would be useful to be able to store longs in a frequency map. Serialising a long does not take any more space than serialising an int when the long is smaller than `Integer.MAX_VALUE`, so `FreqMap` could be changed to only deal with longs without any extra serialisation cost. Alternatively, a `LongFreqMap` class could be written. So the options are:

- Create a new `LongFreqMap` class.
- Change `FreqMap` so that it is a map from String to long.

As there is no serialisation overhead in using a long, I suggest option 2, but opinions are welcome.

This relates to #389.

**Comment by p013570** [comment]
## Migration Steps
The FreqMap class now is a map of Strings to Longs and is not compatible with the old FreqMap (now called IntegerFreqMap) which was a map of Strings to Integers.

If you are currently using the FreqMap (Integer values) then you will need to switch to using IntegerFreqMap, IntegerFreqMapSerialiser and IntegerFreqMapAggregator classes. These classes have all been marked as deprecated and when possible you should switch to using the new FreqMap that handles Long values and the FreqMapSerialiser serialises the values much more efficiently.

**Comment by p013570** [comment]
Merged into develop.
