### ISSUE TITLE
Serialisation of FreqMap

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#389]
The serialisation of `FreqMap` currently works by converting the key-value pairs to strings and then joining them together with a delimiter. It should be possible to do this more efficiently, without the overhead of converting the integers to and from strings. If `FreqMapSerialiser` is changed, this would be a breaking change. Alternatively, a new separate serialiser could be written.

**Comment by p013570** [comment]
Merged into develop as part of issue gh-388.
