### ISSUE TITLE
Investigate GraphQL interface based on Gaffer Schema

### ISSUE THREAD

**Issue by GCHQ-11** [gchq/Gaffer#393]
It may be possible to generate a GraphQL schema using graphql-java based on the Gaffer Schema.

This would give us a much simpler remote interface option for developers, although it is unlikely to have the same functionality as the full Gaffer REST API. I think it should be possible to at least traverse from vertexes to Entities/Edges and read properties.

**Comment by p013570** [comment]
This has been added to the gaffer-tools repository.
