### ISSUE TITLE
Enhance operation to create Spark Dataframe to allow multiple groups

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#408]
The current `GetDataFrameOfElements` operation can only deal with one group. This is because the Dataframe needs to have a known schema. However, it should be possible to extend this to deal with multiple groups: if two groups have the same property then the associated column can just have the property name; if a property P is only present in group G then the column name can be G_P to tell the user which group it came from. If there are multiple groups then a group column should be added.

**Comment by p013570** [comment]
Merged into develop
