### ISSUE TITLE
Create precompiled Gaffer demo

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#411]
This should use an in memory accumulo store.

The download should contain all the files required to start up a Gaffer rest api and ui.

**Comment by m316257** [comment]
I'm writing a schema and generators so that this comes with some pre-loaded data

**Comment by p013570** [comment]
This has been moved to the gaffer-tools repository - [gh-1](https://github.com/gchq/gaffer-tools/issues/1).
