### ISSUE TITLE
Spark operation handlers for Accumulo store don't implement all options

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#418]
The following options on `GetRDDOfElements`, `GetRDDOfAllElements`, `GetJavaRDDOfElements` and `GetDataFrameOfElements` are either not implemented or cause exceptions or don't make sense: `deduplicate`, `limitResults`, `populateProperties`. For the latter operation, `addSeed` is offered but doesn't make sense.

Both the `deduplicate` and `limitResults` options on get operations assume that the result is a `CloseableIterable` - this is not true in the general case. Some operations will either not offer these options, or will implement them in their own way.

These issues have become more visible due to the recent changes to the builders which cause all methods to be exposed, but the issues were there before that.

Marking this as a bug because if the options are offered they should work.

**Comment by p013570** [comment]
I've added an issue gh-502 that moves these options onto GetElements or a new operation GetIterable. So this issue may be automatically resolved with gh-502.

**Comment by p013570** [comment]
If the spark operations require any of these options then they need to be added specifically to the spark operations.

**Comment by t616178** [comment]
This issue will be fixed by gh-502.
