### ISSUE TITLE
GetAllElements builder offers invalid method

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#419]
The `Builder` for `GetAllElements` offers an `addSeed` method but this is not valid for this operation. As the only reason for the existence of the builder is to make it easy to create a valid instance of the operation, it should not offer this method.

Also:
-  `GetAllElements` is a `GetElements<ElementSeed>` - shouldn't it be a `GetElements<Void>`?
- The `setIncludeIncomingOutGoing` method currently says that it is only possible to set this to outgoing edges only. This doesn't make sense - there is no concept of outgoing for `GetAllElements`. It would be better if this method threw an `IllegalArgumentException` (even if under the hood it uses that option to avoid returning the same edge twice).

**Comment by t616178** [comment]
GetElements requires a generic type which extends ElementSeed, so it's not possible to create an object like GetElements<Void>.

If the main issue is that some operations specify invalid methods, it might be necessary to refactor the operation classes to move some of the methods into interfaces, e.g.

<pre><code>
GetElements extends AbstractGetIterableElementsOperation<ElementSeed, Element>
GetEntities extends GetElements implements WithSeed<ElementSeed> etc
</code></pre>

The alternative is to document which methods are supported for each operation and to throw exceptions if an unsupported one is used.

Is there any preference on this?

**Comment by gaffer01** [comment]
Similarly, `GetAdjacentEntitySeeds` has some options that don't make sense, such as `populateProperties` and `includeEntities`.

**Comment by p013570** [comment]
These options do really increase the complexity of implementing a new Store. Perhaps we could remove some options or make some of them optional.

**Comment by p013570** [comment]
## Migration Steps
The following options have been removed:
- populateProperties (this never used to do anything)
- includeEntities (the view should be used to control if entities are required)
- includeEdges (the view should be used to control if edges are required)
- limit (users will now have to use the Limit operation)
- deduplicate (users will now have to use the Deduplicate operation)

A 'directedType' option has been added to replace includeEdges, this allows only directed or undirected edges to be filtered.

The hierarchy of some of the operations has also changed to try and avoid operations having illegal options.

**Comment by t616178** [comment]
Merged into develop-0.7.0
