### ISSUE TITLE
Spark Dataframe operation should allow configurable conversion of properties to a Spark DataType

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#422]
In the handler for the `GetDataFrameOfElements` operation, it should be possible to configure how a Spark `DataType` is generated from a property (for example if the properties contain custom objects that Gaffer is not aware of then the user should be able to specify how a Spark `DataType` is generated from it).

The conversions that are automatically dealt with should be extended to include `FreqMap` and `HyperLogLogPlus`.

**Comment by t616178** [comment]
Merged into develop
