### ISSUE TITLE
AddElementsFromHDFS operation should provide a counter for elements that failed validation

### ISSUE THREAD

**Issue by james010101101** [gchq/Gaffer#439]
At current there is no way to tell how many Elements failed validation when going an AddElementsFromHDFS operation this would be a useful for users to have.

**Comment by p013570** [comment]
In addition to just logging this warning in AbstractAddElementsFromHdfsMapper.java
```java
LOGGER.warn("Element " + element + " did not validate.");
```

we should update a counter e.g.
```java
context.getCounter("Add Elements From HDFS", "invalid element count").increment(1L);
```

**Comment by p013570** [comment]
Merged into develop.
