### ISSUE TITLE
Add total count utility method to FreqMap

### ISSUE THREAD

**Issue by m316257** [gchq/Gaffer#443]
I've come across a couple of cases where i'm getting the total count from a FreqMap so might be worth adding a utility method to do it

**Comment by d21211122** [comment]
Sounds to me like a transform is a better way to achieve this - calculate the total count at query time from the values in a map. If the total count is always needed and performance is critical, then just have  a second property to keep track of the total.

**Comment by m316257** [comment]
Closed based on suggestion from @d21211122
