### ISSUE TITLE
Add date/time utilities to common-util

### ISSUE THREAD

**Issue by m316257** [gchq/Gaffer#444]
Gaffer is about summarisation, often over time and users often need to add time buckets with start and end times or dates on their edges and entities. 

Adding some optimised utility methods to help with this inside Gaffer would help a lot.

**Comment by p013570** [comment]
What methods shall we add?

**Comment by t616178** [comment]
I'm going to add some of the methods from Gaffer1, as well as some methods to carry out "bucketisation" of time fields.

**Comment by p013570** [comment]
Merged into develop.
