### ISSUE TITLE
Build fails with Accumulo 1.8.0

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#449]
Changing the version of Accumulo to 1.8.0 causes errors in `accumulo-store/src/test/java/gaffer/accumulostore/integration/performance/BloomFilterIT.java`:
- `method openWriter in class FileOperations cannot be applied to given types`
- `method openReader in class FileOperations cannot be applied to given types`

These should be minor issues, and it should be possible to support both Accumulo 1.7.\* and 1.8.0 with the same code.

**Comment by james010101101** [comment]
It Looks like the API to read/write RFiles is a breaking change from Accumulo 1.7-1.8 and we need to remove this test to build against both.

**Comment by p013570** [comment]
Merged into develop

**Comment by p013570** [comment]
This should have been closed as it was released as part of version 0.6.3.
