### ISSUE TITLE
Provide visibility serialiser that's compatible with Accumulo's built-in visibility filtering

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#466]
We should provide a serialiser for string visibilities that works as you'd expect with Accumulo's built-in visibility filtering approach, e.g. if the visibility is "vis1&vis2" and the user has Accumulo authorisations "vis1" and "vis2", then they should be able to see it. This serialiser should automatically be used if the provided visibility property is a string. It should deal with the valid visibility of the empty string.

Note that it's possible that this already works fine with our standard string serialiser, but there don't seem to be any unit tests that check the combination of visibilities is dealt with correctly.

**Comment by t616178** [comment]
This will be fixed by issue gh-485.

**Comment by p013570** [comment]
Merged into develop.
