### ISSUE TITLE
Improve the serialisers to improve handling of null values and empty byte arrays

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#485]
Currently the Serialisation classes do not support custom handling for null values in a consistent way. This is an issue if there is a requirement for handling of non-standard edge cases (e.g. empty Strings as valid property values, as in the case of the visibility property).

**Comment by t616178** [comment]
# Migration required

The format of the Serialiser classes has changed. The serialisers are now generic classes, with the generic parameter being the type of object serialised and the target type for deserialisation.

The Serialiser classes are now also responsible for handling nulls. Default behaviour is provided by the AbstractSerialiser class, which should be extended. The default behaviour is to serialise null values as empty byte arrays and to deserialise empty byte arrays to null values again. In combination with the configuration for the Jackson ObjectMapper used, these null values will not be serialised when written as JSON.

**Comment by p013570** [comment]
Merged into develop
