### ISSUE TITLE
Replace/remove usages of deprecated classes.

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#489]
On building the project, there are a large number of compiler warnings relating to the usage of deprecated classes/methods.

Do we have a timescale for removing references to these deprecated classes (in examples etc) and for removing them from the project entirely?

**Comment by t616178** [comment]
To clarify, this applies to both external libraries and deprecated classes within the Gaffer project.

**Comment by p013570** [comment]
Merged into develop.
