### ISSUE TITLE
Failure running Gaffer standalone profile

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#497]
Running the Gaffer project with the standalone Maven profile results in an error:

<pre><code>[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.2.11.v20150529:run-war (default) on project example-rest: Execution default of goal org.eclipse.jetty:jetty-maven-plugin:9.2.11.v20150529:run-war failed: An API incompatibility was encountered while executing org.eclipse.jetty:jetty-maven-plugin:9.2.11.v20150529:run-war: java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map;</pre></code>

**Comment by t616178** [comment]
Following further investigation, this seems to be specific to my development environment. I'll leave this open for the moment in case the issue relates to Gaffer itself.

**Comment by p013570** [comment]
Merged into develop.
