### ISSUE TITLE
Move some flags from GetOperation to GetIterable operation

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#502]
There are several flags on GetOperation that only apply to iterables or elements. These should be moved to either a new operation GetIterable or GetElements.

``` java
GetIterable extends GetOperation<SEED_TYPE, Closeableiterable<RESULT_TYPE>>
```

``` java
GetElements extends GetIterable<? extends ElementSeed, ? extends Element>
```

GetIterable should have the following (moved from GetOperation):
resultLimit
deduplicate

GetElements should have the following (moved from GetOperation):
includeEdges
includeIncomingOutGoing
includeEntities
populateProperties
seedMatching
validateFlags

**Comment by t616178** [comment]
Quick representation of the new class hierarchy:

<pre><code>
                                +-----------+
                                |          I|
                                | Operation |
                                |           |
                                +-----------+
                                       ^
                                       |
                               +--------------+       +-------------+
                               |             I|       |            C|
                           +-->| GetOperation |<------| CountGroups |
                           |   |              |       |             |
                           |   +--------------+       +-------------+
                           |                ^
                           |                |
               +----------------------+   +----------------------+    +-------------+
               |                     I|   |                     I|    |            C|
          +--->| GetElementsOperation |   | GetIterableOperation |<---| Deduplicate |
          |    |                      |   |                      |    |             |
          |    +----------------------+   +----------------------+    +-------------+
          |                    ^                   ^
          |                    |                   |
+------------------+      +------------------------------+         +----------------+
|                 C|      |                             I|         |               C|
| GetRDDOfElements |      | GetIterableElementsOperation |<--------+ GetAllElements |
|                  |      |                              |         |                |
+------------------+      +------------------------------+         +----------------+
</code></pre>

**Comment by p013570** [comment]
Merged into develop.
