### ISSUE TITLE
Gaffer UI doesn't work if mapped into a URL which isn't /ui

### ISSUE THREAD

**Issue by cybermaggedon** [gchq/Gaffer#507]
For security reasons, I put a web server in front of Gaffer, reverse proxy plus certificates, and mapped it into URL `/gaffer`.  This doesn't work, the UI expects to be /ui, and /gaffer/ui breaks it  I'm guessing is this code:

```
./src/main/webapp/app/settings/settings.js:     restUrl: window.location.origin + "/rest/v1"
```

Maybe a relative URL would make this work. 

FYI, I'm using nginx as the web proxy, with proxying configured thus:

```
    location /gaffer/ {
        proxy_pass http://gaffer:8080/;
    }
```

Let me know if you want a patch.

Loving the new UI by the way! :-)

**Comment by t616178** [comment]
I'm having trouble replicating this issue locally. I currently have nginx set up (and working) with a redirect from:

http://localhost:8080/ui

to:

http://localhost:80/gaffer

Would you be able to share your entire nginx.conf file?

**Comment by t616178** [comment]
Closing for now - we'll reopen this issue if this problem resurfaces.
