### ISSUE TITLE
Add enumerated types for HDFS counters

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#511]
HDFS counters can be retrieved from the current context in two ways:

<pre><code>context.getCounter(String, String)
context.getCounter(Enum<E>)</code></pre>

Currently, we are using hardcoded Strings throughout the project to get Counter instances. Would it be better to add (and use) enumerated types going forwards?

**Comment by gaffer01** [comment]
If enumerated types are used, how are they referenced from the REST API? At some point we may want to introduce monitoring that uses the Jobtracker REST APT to retrieve information about the counters. How would they be identified using the enum?

**Comment by n3101** [comment]
Sorry, this is not going to happen.
