### ISSUE TITLE
The Accumulo store should work without aggregators

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#514]
A schema with no aggregators is valid. Currently the accumulo store cannot handle this case and will run into issues when trying to aggregate properties as it won't be able to find any aggregators in the schema.

If the accumulo store receives an schema with no aggregators it should configure the accumulo table using the versioning iterator (i.e don't delete it as we normally do) and don't add the aggregator iterator.

The operation handlers in Accumulo should also be updated to not use any query time aggregators.

**Comment by gaffer01** [comment]
"If the accumulo store receives an schema with no aggregators it should configure the accumulo table using the versioning iterator (i.e don't delete it as we normally do) and don't add the aggregator iterator."

I don't think this is right. If you add the same edge twice (i.e. identical in all ways, including the properties) then that edge should be present in the database twice, and be returned twice from queries. That's the way that all current graph databases work. If we use the versioning iterator then you only get the most recent version which isn't what you want.

The versioning iterator should be turned off and no aggregator iterator added.

**Comment by p013570** [comment]
Merged into develop.
