### ISSUE TITLE
Add an example of adding vertex cardinalities to the Getting Started guide

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#516]
This basically involves adding a 'Cardinality' Entity onto every vertex. The 'Cardinality' entity needs to have a HyperLogLogPlus property. Then in your element generator, whenever an edge (A to B) is created, it should also create cardinality entities at A and B.

These cardinality entities will then be aggregated automatically and will provide an estimate of the connectivity of each vertex in the graph.

To create the cardinality entities for an edge, you can do something like:
```java
final HyperLogLogPlus hllpSource = new HyperLogLogPlus(5, 5);
hllpSource.offer(edge.getDestination());
final Entity sourceCardinality = new Entity.Builder()
        .vertex(edge.getSource())
        .group("Cardinality")
        .property("edgeGroup", edge.getGroup())
        .property("hllp", hllpSource)
        .build();

final HyperLogLogPlus hllpDest = new HyperLogLogPlus(5, 5);
hllpSource.offer(edge.getSource());
final Entity destCardinality = new Entity.Builder()
        .vertex(edge.getDestination())
        .group("Cardinality")
        .property("edgeGroup", edge.getGroup())
        .property("hllp", hllpDest)
        .build();
```

**Comment by gaffer01** [comment]
Merged into develop.
