### ISSUE TITLE
Filters in gaffer.function.simple.filter should have toString(), equals(), hashCode() methods

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#518]
Logging information about the use / creation of filters isn't very useful as they don't have `toString()` methods.

They should also have `equals()` and `hashCode()` methods as it's possible they may get added to a set, e.g. if someone is deduping a list of filters.

These 3 methods should be added to everything in `gaffer.function.simple.filter` and probably to other classes under `gaffer.function.simple`.

**Comment by t616178** [comment]
As part of this issue, I will also update the existing toString(), equals() and hashCode() methods so that we have a consistent approach across the entire project.

**Comment by gaffer01** [comment]
Thanks - other classes that need these methods (or at least some of them) are `View` and `Schema` and other classes they use. Can this be done as part of this issue, or should it be a separate issue?

**Comment by t616178** [comment]
I can add those extra methods as part of this issue too.

**Comment by t616178** [comment]
Merged into develop.
