### ISSUE TITLE
Introduce concept of tag for groups

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#530]
The group of an element defines the properties that will be present on it. There are often natural groupings of groups, i.e. groups that are related in some way, e.g. red edges and red entities where the red entities contain properties that summarise the red edges. If groups could be tagged in the schema, and a tag used to create a view, then it would give an easy way to generate graphs containing groups that belong together.

An example would be having groups called red_edge_group, blue_edge_group, red_entity_group, big_edge_group, etc. Tags could be applied to the groups, e.g. red, colour, size. A view could be created from the red tag that would return just the red_edge_group and red_entity_group. A view from the colour tag would return red_edge_group, blue_edge_group, red_entity_group.

This is related to #519 but different as that is referring to filtering based on properties. This proposal does not involve adding a tag property to every element. It simply tags groups in the schema, so that domain knowledge of which groups belong together can be encoded in the schema and later used to easily produce views that contain elements that make sense.

This makes it easier to have rich graphs with lots of different types of data, but easily generate subgraphs with groups that together form a coherent view on the data. The ability to create your own view that produces exactly what you want would still exist.

**Comment by t616178** [comment]
@p013570 is this functionality already available through the use of global filters?

**Comment by p013570** [comment]
Rather than adding yet another field to schemas and further complicating them, I think this can be handled by creating pre canned Views, like RedElements, ColouredElements, etc. These pre canned views could be added as NamedViews after this issue is completed: #1542.
