### ISSUE TITLE
Remove some of the GetElements operations

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#534]
Currently we have:
- getElementsBySeed
- getRelatedElements
- getEntitiesBySeed
- getRelatedEntities
- getEdgesBySeed
- getRelatedEdges

These all extend from GetElements and just set various flags. It is a bit excessive and a bit confusing. We should remove some of these, resulting in:
- getElements
- getEntities
- getEdges

**Comment by t616178** [comment]
I'm working on this issue in conjunction with gh-502.

**Comment by t616178** [comment]
# Migration Steps

In this issue the following operations have been deprecated:

* GetRelatedElements
* GetRelatedEdges
* GetRelatedEntities
* GetElementsBySeed
* GetEdgesBySeed
* GetEntitiesBySeed

These operations are still available, but will be removed entirely in a future version of Gaffer. These operations have been superseded by:

* GetElements
* GetEdges
* GetEntities

each of which have properties which can be set to emulate the functionality of the removed operations.

The removed operations have also been removed from the REST API and are no longer displayed when view the Swagger UI. The REST endpoints representing these operations still exist, however, and will not result in any errors for the time being. As with the operations themselves, these REST endpoints will be removed in a future version of Gaffer.

All operation chains, workflows etc which depend on the deprecated operations should be migrated to the appropriate new operation.

**Comment by p013570** [comment]
Merged into develop
