### ISSUE TITLE
A view should contain the operation seeds

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#536]
In the future, you will be able to query Gaffer using vertex, group or property seed. The View is designed to override a Schema. So it follows that a View could override the source vertex of and edge group with some seeds. Or, a View could override a property with some seeds.

For example:

Using this schema (based on users viewing/watching films):
```json
{
  "edges": {
    "viewing": {
      "source": "userId",
      "destination": "filmId",
      "directed": "true",
      "properties": {
        "startTime": "timestamp",
        "count": "count"
      }
    }
  }
}
```

A view with some source vertex seeds may look like this:
```json
{
  "edges": {
    "viewing": {
      "source": ["user01", "user02"]
    }
  }
}
```

Or a view with that limits edges to only directed edges. This would require a magic group called "ALL" :
```json
{
  "edges": {
    "ALL":  {
      "directed": true
    }
  }
}
```

Or a view with a property seed may look like this:
```json
{
  "edges": {
      "properties": {
        "count": [5]
      }
    }
  }
}
```

This would have an effect on operation chains. Needs further designing.

**Comment by gaffer01** [comment]
Agree this needs further thought. I think putting operation parameters in the view could be confusing.

Some seeds for operations are effectively infinite (you can query for a never-ending iterable of seeds).

Some operations seeds are actually groups of seeds (e.g. edges between these sets of seeds).

Would every "seed" for every operation go in the view? What if the operation took a triangle of edges as a seed and looked for those?

**Comment by p013570** [comment]
Closing as after further thought, and as @gaffer01 pointed out, this could be quite confusing.
