### ISSUE TITLE
Make REST API more "RESTful"

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#538]
The current REST API does not look like a typical RESTful API (based around resource collections and the application of HTTP methods against those collections).

Could the REST API be refactored slightly to align more closely with REST best practice?

E.g.

<pre><code>POST http://<host>:<port>/api/graph/get/elements/related
{
  "seeds" : [ "elementSeed1", "elementSeed2" ]
}</pre></code>

Could become:

<pre><code>GET http://<host>:<port>/api/graph/elements/<elementSeed1>,<elementSeed2>/related</pre></code>

Use of path & matrix parameters could eliminate some of the POST bodies currently required for some of the simple element retrieval operations.

**Comment by p013570** [comment]
It would be nice to make the api more like a typical RESTful api, but things like putting the seeds in the url is not possible as there is a limit on the number of characters in a url, therefore users would then be limited to the number of seeds they could supply.

Perhaps we should rename the REST API to WEB API?

**Comment by p013570** [comment]
Merged into develop.

**Comment by t616178** [comment]
# Migration steps

Version 2 of the Gaffer REST API contains a number of changes which require user intervention.

* The OperationChain class is now a subclass of Operation. In order for deserialisation to work correctly, any operation chains written in JSON and submitted to the REST API must contain the type ID in the JSON body. For example:

```javascript
{
	"class" : "uk.gov.gchq.gaffer.operation.OperationChain",
	"operations" : [
		...
	]
}
```

* The API now has four distinct sections:

/graph				The graph root resource
/graph/config		Resources relating to the graph configuration
/graph/jobs			Resources relating to submitting Jobs to the graph
/graph/operations	Resources relating to executing operations on the graph

A full list of endpoints (with descriptions) is provided below:

GET 	/graph/ 									status page of some description? or redirect to home page? a summary of all graph information?

Operations

GET		/graph/operations 							list of all operations supported by the current store
POST	/graph/operations/execute					perform the submitted operation
POST	/graph/operations/execute/chunked			perform the submitted operation
POST 	/graph/operations/generate/elements			generate elements, as specified in the request body
POST 	/graph/operations/generate/objects			generate objects, as specified in the request body
GET 	/graph/operations/{className}				get information about the specified operation class
GET 	/graph/operations/{className}/example		get an example JSON body for the specified operation class
GET 	/graph/operations/{className}/next			list of all acceptable operations which can be performed after the specified operation

Jobs

POST 	/graph/jobs 								create a new job, based on the OperationChain contained in the request body
GET 	/graph/jobs 								get a list of all jobs
GET 	/graph/jobs/{id} 							get the details of the specified job
GET 	/graph/jobs/{id}/results 					get the results from running a job

Configuration

GET 	/graph/config 								get all configuration details
GET 	/graph/config/schema						get schema details
GET 	/graph/config/filterFunctions				get filter function details
GET 	/graph/config/filterFunctions/{inputClass}	get filter function details for given input class
GET 	/graph/config/transformFunctions			get transform function details
GET 	/graph/config/elementGenerators				get element generator details
GET 	/graph/config/objectGenerators				get object generator details
GET 	/graph/config/storeTraits					get store traits
POST 	/graph/config/isOperationSupported			query the graph to see if a given operation is supported
GET 	/graph/config/serialisedFields/{className}	get the serialised fields for a given class

Status

GET 	/graph/status 								get the graph status
