### ISSUE TITLE
Update Jenkinsfile to build on multiple environments

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#544]
Currently the Jenkinsfile does not specify which nodes Jenkins should use to attempt to build Gaffer on. This should be updated so that Jenkins builds each branch on all of our target platforms before a release is performed.

**Comment by t616178** [comment]
Merged into develop.

**Comment by t616178** [comment]
Reopening to fix issue with Jenkins building only from the most recent commit in the develop branch.

**Comment by p013570** [comment]
Merged into develop.
