### ISSUE TITLE
Update Travis configuration to perform releases to Maven Central

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#545]
Currently Gaffer artefacts are not pushed to a remote repository. Configuration must be added to perform a release to Maven Central so that other projects can easily use the Gaffer JARs.

**Comment by t616178** [comment]
This must be done after gh-434.

**Comment by t616178** [comment]
Switching from Jenkins to Travis for the build environment for CD.

**Comment by p013570** [comment]
Merged into develop.
