### ISSUE TITLE
FetchElementsFromHdfsTool checks a non mandatory option has been set.

### ISSUE THREAD

**Issue by james010101101** [gchq/Gaffer#558]
When doing a bulk load into accumulo, if you break up the load into two stages your mapreduce phase and the move into accumulo phase the mapreduce phase will check that the failure path for the move into accumulo phase has been set - although you may never use it.
The check for a valid failure directory should be moved into the ImportElementsToAccumuloTool.
Where the option is used.

**Comment by p013570** [comment]
Merged into develop
