### ISSUE TITLE
Tidy up dependencies for REST API

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#600]
Currently the rest api depends on multiple versions of resteasy and jersey. The multiple different versions of classes on the classpath can cause the REST API to fail to be deployed. This is linked to issue gh-497.

Probably best to remove all dependencies on resteasy and just use the jersey libraries. We need to ensure the rest api war can still be deployed to different servers (JBoss, Tomcat, Jetty, etc).

**Comment by t616178** [comment]
The changes for this branch have been merged into gh-140, gh-499 and gh-604.
