### ISSUE TITLE
Consider adding Gaffer link to Accumulo website

### ISSUE THREAD

**Issue by keith-turner** [gchq/Gaffer#617]
I would encourage this project to consider adding a link to the [Accumulo website][1].  If you are interested, I am happy to assist with this if you know what content you would like. You could also [make a PR][2] to change [pages/related-projects.md][3]

[1]: http://accumulo.apache.org/related-projects/
[2]: https://github.com/apache/accumulo-website
[3]: https://github.com/apache/accumulo-website/blob/master/pages/related-projects.md

**Comment by t616178** [comment]
PR raised on accumlo-website project to add Gaffer to list of related projects.

**Comment by keith-turner** [comment]
This is done apache/accumulo-website#7
