### ISSUE TITLE
Serialisation class Javadoc issues

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#629]
There are some issues with the Javadoc in the `Serialisation` class:

- The second line of the Javadoc at the top of the class is irrelevant - "As a minimum, any Serialisation mechanism must be able to serialise and deserialise any given Property" - there is no "Property" here - just a T. The first line is also confusing. It should be rewritten to say:
"A class that implements this interface is responsible for serialising an object of class T to a byte array, and for deserialising it back again. It must also be able to deal with serialising null values."
- The comment on the `deserialise` method should be rewritten to say "Deserialise an array of bytes to the original object."
- The comment on the `isByteOrderPreserved` method is confusing - it's not about whether the byte order is preserved - it's whether the serialised form preserves the ordering of the objects. The method should really be renamed to `preservesObjectOrder`. The Javadoc should also note what should be returned if this method makes no sense, e.g. if T is not `Comparable`. The Javadoc should say: "This method indicates whether the serialisation process preserves the ordering of the T, i.e. if x and y are objects of class T, and x is less than y, then this method should return true if the serialised form of x is guaranteed to be less than the serialised form of y (using the standard ordering of byte arrays). If T is not `Comparable` then this test makes no sense and false should be returned."

**Comment by p013570** [comment]
Merged into develop.
