### ISSUE TITLE
`deserialiseEmptyBytes` method in `HyperLogLogPlusSerialiser` doesn't work

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#638]
The `deserialiseEmptyBytes` method in `HyperLogLogPlusSerialiser` always throws an exception with the following message: "java.lang.RuntimeException: Failed to create HyperLogLogPlus sketch from given bytes". It is not possible to deserialise it from nothing - you can't simply call `new HyperLogLogPlus` as you need to know what values of `p` and `sp` are to be used. Instead an exception should be thrown to indicate that this method is invalid.

**Comment by p013570** [comment]
If the bytes are empty then the hyperLogLogPlus object must have been null to start with.
Therefore when empty bytes are deserialised the result should be null.
The deserialiseEmptyBytes method should just return null.

**Comment by gaffer01** [comment]
Merged into develop.
