### ISSUE TITLE
Integration tests fail when run against an AccumuloStore

### ISSUE THREAD

**Issue by ctas582** [gchq/Gaffer#657]
Tests run against an Accumulo 1.7.2 instance deployed onto a Hadoop 2.6.0-cdh5.7.0 cluster.

Tests in error:

- AccumuloAggregationIT.shouldAggregateOverAllPropertiesExceptForGroupByProperties:161 » Runtime
- AccumuloAggregationIT.shouldOnlyAggregateVisibilityWhenGroupByIsNull:99 » Runtime
- uk.gov.gchq.gaffer.integration.impl.VisibilityIT.shouldAccessEmptyVisibilityGroups(uk.gov.gchq.gaffer.integration.impl.VisibilityIT) » Runtime org.apache.accumu...
- uk.gov.gchq.gaffer.integration.impl.VisibilityIT.shouldAccessMissingVisibilityGroups(uk.gov.gchq.gaffer.integration.impl.VisibilityIT) » Runtime org.apache.accu...
- uk.gov.gchq.gaffer.integration.impl.VisibilityIT.shouldAccessMultipleVisibilityGroups_and(uk.gov.gchq.gaffer.integration.impl.VisibilityIT) » Runtime org.apache...
- uk.gov.gchq.gaffer.integration.impl.VisibilityIT.shouldAccessMultipleVisibilityGroups_or(uk.gov.gchq.gaffer.integration.impl.VisibilityIT) » Runtime org.apache....
- uk.gov.gchq.gaffer.integration.impl.VisibilityIT.shouldAccessNullVisibilityGroups(uk.gov.gchq.gaffer.integration.impl.VisibilityIT) » Runtime org.apache.accumul...
- uk.gov.gchq.gaffer.integration.impl.VisibilityIT.shouldAccessSingleVisibilityGroup(uk.gov.gchq.gaffer.integration.impl.VisibilityIT) » Runtime org.apache.accumu...

On the tablet servers:
Caused by: java.lang.ClassNotFoundException: uk.gov.gchq.gaffer.accumulostore.integration.AccumuloAggregationIT$VisibilitySerialiser

**Comment by ctas582** [comment]
Lots of tests failing, reporting incorrect number of elements returned and incorrect number of iterators being configured on the table.

Tablet servers reporting errors such as:
java.util.concurrent.ExecutionException: uk.gov.gchq.gaffer.accumulostore.key.exception.ElementFilterException: Element filter iterator failed to create an element from an accumulo key value pair
Caused by: uk.gov.gchq.gaffer.accumulostore.key.exception.AccumuloElementConversionException: No SchemaElementDefinition found for group BasicEntity2, is this group in your schema or do your table iterators need updating?

This is because my store.properties contains:
gaffer.store.class=uk.gov.gchq.gaffer.accumulostore.AccumuloStore

Using AccumuloStore doesn't delete the table after every test, so the schema doesn't get updated for subsequent tests. Need an equivalent of SingleUseMockAccumuloStore...

**Comment by ctas582** [comment]
If your store.properties sets 'accumulo.table' to something other than 'table1' then:

shouldCreateTableWithAllRequiredIterators(uk.gov.gchq.gaffer.accumulostore.utils.TableUtilsTest)  Time elapsed: 0.31 sec  <<< ERROR!
org.apache.accumulo.core.client.TableNotFoundException: Table table1 does not exist

**Comment by p013570** [comment]
Thanks for raising the bug. That visibility serialiser is only in the test jars as it just used for testing. Therefore it is not included in the accumulo-iterators jar that is deployed to accumulo, which is why accumulo is not able to find the serialiser.

I hadn't really imagined the integration tests would ever actually be run against a real cluster, but it does seem like a nice way of testing your cluster is setup correctly. 

If you deploy the accumulo-store-[version]-tests.jar to your cluster and rerun the tests - do they pass?

**Comment by ctas582** [comment]
I had to deploy both accumulo-store-[version]-tests.jar and integration-test-[version]-tests.jar to get the tests to pass.

Do you know if there is any reason that those tests use a serialiser that is implemented in the test classes rather than using one from the serialisation library? Is it okay to switch those tests to use StringSerialiser instead, as per my commit?

**Comment by p013570** [comment]
Merged into develop.
