### ISSUE TITLE
Consistent src and dest in undirected edges

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#659]
An undirected edge A-B is identical to the undirected edge B-A, and the `equals()` method on `Edge` will return true in this case. However when `toString()` is called the string representation of the edge will be different. The JSON version of the edge will also be different. In older versions of Gaffer, undirected edges were always created in a consistent manner, with the source being lexicographically before the destination. As the source and destination are now just objects, there may be no natural ordering, but `toString()` can be used instead.

When the edge is created the logic would be:

    if source and destination are both instances of comparable:
         if destination < source
              swap destination and source
    else
          if destination.toString() < source.toString()
              swap destination and source

This should make it easier for non-Java consumers of the data to dedupe data.

**Comment by t616178** [comment]
This is difficult to achieve in practice due to the many ways in which is possible to construct an Edge object - particularly since it is possible to build an Edge incrementally using a no-arg constructor and setter methods.

When would it be necessary for the representation to be modified? Is this something we could implement only when the toString() method is called or when the Edge is serialised?

**Comment by t616178** [comment]
# Migration steps

**Comment by javadev001001** [comment]
@t616178 can you confirm that you will still be able to use the putProperty method, and that the only immutable parts of these objects are the core parts?

**Comment by p013570** [comment]
We should do issue #906 first.

**Comment by p013570** [comment]
@javadev001001 - yes you will still have access to putProperty. I've updated the migration steps above to explain that it is just the setSource, setDestination and setDirected methods that have been removed.

**Comment by t616178** [comment]
Merged into develop.
