### ISSUE TITLE
Move classes from spark-accumulo-library that are not specific to Accumulo to spark-library

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#677]
There are some classes in spark-accumulo-library which are not specific to Accumulo. These should be moved to spark-library. The unit test `FilterToOperationConverterTest` should be changed so that it tests that the correct operations are created, rather than testing that those operations give the correct results when applied to an `AccumuloStore`. This will allow that unit test to also be moved to spark-library.

There should be unit tests for the various converters, e.g. `FreqMapConverter`. We should also create converters for the `Union` sketch from DataSketches.

**Comment by p013570** [comment]
Merged into develop.
