### ISSUE TITLE
AddElementsFromHdfsIT can't be run against an AccumuloStore

### ISSUE THREAD

**Issue by ctas582** [gchq/Gaffer#686]
`uk.gov.gchq.gaffer.accumulostore.integration.AddElementsFromHdfsIT` can't be run against an AccumuloStore as it is hardcoded to use a MockAccumuloStore and to use the local filesystem rather than HDFS.

**Comment by p013570** [comment]
AddElementsFromHdfsIT is designed to be run locally. We would need to write a separate test to run an actual map reduce job to add elements from a real hdfs cluster. I will close this issue as it will be covered in issue gh-825.
