### ISSUE TITLE
Create Store and Query Time Aggregation Traits

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#704]
There is a difference between store aggregation and query time aggregation and currently we only have 1 AGGREGATION trait. This should be split into STORE_AGGREGATION and QUERY_AGGREGATION. This will help differentiate between the different logic and allow the integration tests to target the correct traits.

This was discovered as part of implementing the HBase store.

**Comment by gaffer01** [comment]
Merged into develop.
