### ISSUE TITLE
setStoreClass method on StoreProperties throws NPE

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#708]
This code

    StoreProperties storeProperties = new StoreProperties();
    storeProperties.setStoreClass("uk.gov.gchq.gaffer.accumulostore.AccumuloStore");

produces a `java.lang.NullPointerException`. It's not normal to create `StoreProperties` this way but to a user of this class it seems like this should work. We should either throw a useful exception or initialise the underlying state so that it doesn't throw a NPE.

**Comment by p013570** [comment]
Merged into develop.
