### ISSUE TITLE
Create an exporter to cache result objects

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#721]
This follows on from gh-720.

When an operation chain is run asynchronously any output results are just lost. So this issue is to implement an exporter that can be used in an operation chain to export any results (elements, seeds, any json serialisable objects) to cache. These results could then be looked up using the async job id. The cache would need to provide visibility filtering, age off and be capable of holding a large number of results. The type of cache should be configurable.

This is similar to gh-284 but 284 only considers exporting Gaffer Elements. This issue requires any type of result object to be cached.

**Comment by t616178** [comment]
Merged into develop

**Comment by p013570** [comment]
To use the cache see the notes on the [wiki](https://github.com/gchq/Gaffer/wiki/Getting-Started#jobs) to configure your gaffer graph accordingly.

For example operations see: [operation examples](https://github.com/gchq/Gaffer/wiki/Operation-examples#exporttogafferresultcache-example)
