### ISSUE TITLE
Error with new GetEdges.Builder<EdgeSeed>()

### ISSUE THREAD

**Issue by unclassified02** [gchq/Gaffer#730]
When i write this code in Eclipse:
```
final GetEdges<EdgeSeed> operation = new GetEdges.Builder<EdgeSeed>()
        .addSeed(new EdgeSeed(1, 2, true))
        .addSeed(new EdgeSeed(2, 3, true))
        .build();
```
taken from the first **GetEdges example** of the [Operation examples wiki](https://github.com/gchq/Gaffer/wiki/Operation-examples#getedges-example), i get this error:
> Incorrect number of arguments for type GetEdges.Builder; it cannot be parameterized with arguments
> \<EdgeSeed\>

Maybe that the right code is the following?
```
final GetRelatedEdges<EdgeSeed> operation = new GetRelatedEdges.Builder<EdgeSeed>()
        .addSeed(new EdgeSeed(1, 2, true))
        .addSeed(new EdgeSeed(2, 3, true))
        .build();
```

**Comment by p013570** [comment]
That seems strange - what version of Gaffer are you using? In the latest version of Gaffer (0.6.1) GetRelatedEdges is deprecated and has been replaced with GetEdges.

**Comment by p013570** [comment]
Just looked a few older versions of Gaffer. I was able to replicate your issue on versions pre 0.5.0, before we made the changes GetEdges. On versions before 0.5.0 you will need to use GetRelatedEdges as you suggested. 

The wiki is update for each release we do and currently is aimed at release 0.6.1. You can view the wiki pages for older versions here: https://github.com/gchq/Gaffer/wiki/Operation-examples/_history

Please get in touch if you have any further problems.

**Comment by unclassified02** [comment]
Thanks so much for your assistance :+1:
