### ISSUE TITLE
Add some useful operations to convert to different data types

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#734]
For example:

- ToStream
- ToSet   (rename from deduplicate)
- ToList
- ToArray
- ToVertices (Converts Elements and ElementSeeds to vertices, optionally extract SOURCE or/and DESTINATION from Edges/EdgeSeed)
- ToEntitySeeds (converts vertices to EntitySeeds)
- ToMap (Performs GenerateObjects with MapGenerator)

These could be used within a operation chain to aid chain operations together or at the end to return results in a particular format.

**Comment by gaffer01** [comment]
As part of this will the deduplicate and resultLimit options be removed from operations like `GetElements`? I think they should be as these are really options that apply to the whole iterable. It's more consistent with standard functional style for these to be operations/functions that are applied after the iterable is created, not as part of the creation of the iterable.

**Comment by t616178** [comment]
I think the issues with incorrect options being available on certain operations is being fixed as part of gh-419.

**Comment by gaffer01** [comment]
Thanks, looks like that issue will sort it.

**Comment by t616178** [comment]
## Migration Steps
The 'Deduplicate' operation has been renamed to 'ToSet'.

**Comment by p013570** [comment]
Merged into develop.
