### ISSUE TITLE
AggregatorIterator seems to remove value(properties) on duplicate row insertion.

### ISSUE THREAD

**Issue by pg99bassist** [gchq/Gaffer#739]
I am having an issue where I have duplicate rows (same RowID, Group, GroupBy, Visibility, Properties) and when they are inserted all of the properties(value) are gone.  I have taken the AggregatorIterator off manually and seen the data is still there.

What would cause the behavior of the iterator to empty out the value of the row?

**Comment by p013570** [comment]
I haven't seen this occur before. Please could you provide the following so I can try and work out what is happening:
- the version of Gaffer you are using
- your full schema
- the elements you added
- the query you are doing and the results you get back

Thanks.

**Comment by pg99bassist** [comment]
* Gaffer 0.4.7 (the Tinkerpop implementation)
* Schema
`{
  "entities": {
    "entity": {
      "properties": {
        "type": "string",
        "visibility": "string",
      },
      "groupBy": [
        "type"
      ]
    }
  },
  "edges": {
    "knows": {
      "source": "entity",
      "destination": "entity",
      "directed": "true",
      "properties": {
        "weight": "weight"
      }
    }
    "learns": {
      "source": "entity",
      "destination": "entity",
      "directed": "true",
      "properties": {
        "weight": "weight"
      }
    }
  },
  "visibilityProperty": "visibility"
}
`
* Elements
GafferPopGraph graph = (GafferPopGraph) GraphDB.openGraphDataBase();
GafferPopVertex v1 = new GafferPopVertex("entity", "person_id_12345", graph);
v1.property(VertexProperty.Cardinality.list, "type", "person");
v1.property(VertexProperty.Cardinality.list, "visibility", "Public");
v1.property(VertexProperty.Cardinality.list, "description", "A guy who does the thing for the stuff.");
graph.addVertex(v1);

New here is the thing.  I know this is the Tinkerpop Experimental version of gaffer... but it works just like the normal Gaffer build with data insertion.  That record goes in perfectly with the proper GroupBy fields and both Vertex properties:

person_id_12345\x00\x01 entity:\x06person [Public] \x00'A guy who does the thing for the stuff.\x00\x00

The issue is that if I were to add that same vertex again... I get this:

person_id_12345\x00\x01 entity:\x06person [Public]

And if I remove the Aggregator iterator from the table I see both records with both properties as are wont because there is not Versioning iterator on the table:

person_id_12345\x00\x01 entity:\x06person [Public] \x00'A guy who does the thing for the stuff.\x00\x00
person_id_12345\x00\x01 entity:\x06person [Public] \x00'A guy who does the thing for the stuff.\x00\x00

I don't get properties back from any query or Gremlin traversal because they are "hidden or removed" by that iterator.  Does this clarify what I am experiencing?

**Comment by p013570** [comment]
OK, thanks for the details. I'll try and replicate the issue and get back to you soon.

**Comment by p013570** [comment]
Just having a look at your schema and it looks like you are missing a few things? Perhaps you missed some bits off when you sent it? When you add the GafferPopVertex, you set a value for the "description" property, but in your schema there isn't a "description" property.

Please could you also provide the dataTypes.json file (or the part of the schema containing all the types information). For each type used in the schema, e.g. "string", "weight", "entity", "true" you need to tell Gaffer what those types are. See [types](https://github.com/gchq/Gaffer/wiki/Getting-Started#the-datatypes). Also, you need to decide on how values of those types should be aggregated together. When you added the same GafferPopVertex twice Gaffer will merge the 2 entities together using the aggregator functions provided in the schema. I updated your schema to this:

```json
{
  "entities": {
    "entity": {
      "properties": {
        "type": "string",
        "visibility": "string",
        "description": "string"
      },
      "groupBy": ["type"]
    }
  },
  "edges": {
    "knows": {
      "source": "entity", "destination": "entity", "directed": "true",
      "properties": {
        "weight": "weight"
      }
    },
    "learns": {
      "source": "entity", "destination": "entity", "directed": "true",
      "properties": {
        "weight": "weight"
      }
    }
  },
  "types": {
    "type": {
      "class": "java.lang.String",
      "aggregateFunction": {
        "class": "gaffer.function.simple.aggregate.StringConcat"
      }
    },
    "string": {
      "class": "java.lang.String",
      "aggregateFunction": {
        "class": "gaffer.function.simple.aggregate.StringConcat"
      }
    },
    "weight": {
      "class": "java.lang.Double",
      "aggregateFunction": {
        "class": "gaffer.function.simple.aggregate.Max"
      }
    },
    "entity": {
      "class": "java.lang.String",
      "aggregateFunction": {
        "class": "gaffer.function.simple.aggregate.StringConcat"
      }
    },
    "true": {
      "class": "java.lang.Boolean",
      "validateFunctions": [
        {
          "function": {
            "class": "gaffer.function.simple.filter.IsTrue"
          }
        }
      ]
    }
  },
  "visibilityProperty": "visibility"
}
```

and it seems to work ok. 

I used the StringConcat aggregator function to merge "string" properties together. The StringConcat function isn't very clever and I wouldn't recommend it. If you add the same entity twice it will simply comma separate the "string" properties together even if they are the same. 

A better approach would be to either implement your own Aggregate Function (see [StringConcat](https://github.com/gchq/Gaffer/blob/master/library/core-library/src/main/java/uk/gov/gchq/gaffer/function/aggregate/StringConcat.java) as an example) - doing this you could decide exactly how 2 strings should be merged together. Or use a java.util.TreeSet containing strings instead of just a String. This way string property values are deduplicated nicely for you, but it adds a bit more complexity to adding and fetching properties. E.g:

```json
{
  "entities": {
    "entity": {
      "properties": {
        "type": "string",
        "visibility": "string",
        "description": "string.set"
      },
      "groupBy": ["type"]
    }
  },
  "edges": {
    "knows": {
      "source": "entity", "destination": "entity", "directed": "true",
      "properties": {
        "weight": "weight"
      }
    },
    "learns": {
      "source": "entity", "destination": "entity", "directed": "true",
      "properties": {
        "weight": "weight"
      }
    }
  },
  "types": {
    "type": {
      "class": "java.lang.String",
      "aggregateFunction": {
        "class": "gaffer.function.simple.aggregate.StringConcat"
      }
    },
    "string": {
      "class": "java.lang.String",
      "aggregateFunction": {
        "class": "gaffer.function.simple.aggregate.StringConcat"
      }
    },
    "weight": {
      "class": "java.lang.Double",
      "aggregateFunction": {
        "class": "gaffer.function.simple.aggregate.Max"
      }
    },
    "entity": {
      "class": "java.lang.String",
      "aggregateFunction": {
        "class": "gaffer.function.simple.aggregate.StringConcat"
      }
    },
    "string.set": {
      "class": "java.util.TreeSet",
      "aggregateFunction": {
        "class": "gaffer.function.simple.aggregate.SetAggregator"
      }
    },
    "true": {
      "class": "java.lang.Boolean",
      "validateFunctions": [
        {
          "function": {
            "class": "gaffer.function.simple.filter.IsTrue"
          }
        }
      ]
    }
  },
  "visibilityProperty": "visibility"
}
```

When you add a "description" property now you will need to do:
```java
final TreeSet<String> description = new TreeSet<>();
description.add("A guy who does the thing for the stuff."");
v1.property(VertexProperty.Cardinality.list, "description", description);
```

**Comment by pg99bassist** [comment]
Ooooohhhh... right. Crap.  I totally see that now.  I look at the docs daily and completely didn't put two and two together.  I will mess around with it and get back to you will y findings.  Until then, super big thanks!

**Comment by p013570** [comment]
No problem. If there is anything in the docs that don't make sense, please raise an issue and we will get them updated.

I haven't updated the version of Gaffer in the Tinkerpop implementation for a while, as I assumed no one was really going to use it as it is just a prototype and the performance isn't as great. I can update it tomorrow if that is helpful for you? There are some quite big breaking changes in Gaffer from 0.4.7 to 0.6.1, you would need to do a bit of migration but would be useful to do it before you get to tied to 0.4.7.

**Comment by pg99bassist** [comment]
That would be extremely helpful!

**Comment by p013570** [comment]
I've just pushed up the changes to [master](https://github.com/gchq/gaffer-experimental/tree/master/tinkerpop) so it now depends on Gaffer 0.6.1. To migrate, the easiest thing to do is just to delete your Accumulo table as your Gaffer 0.4.7 data will not be compatible with Gaffer 0.6.1. Other migration steps can be found here: https://github.com/gchq/Gaffer/releases

**Comment by pg99bassist** [comment]
I think I have found the issue... or at least where it may originate.

Making all the relevant changes you suggested I updated all my store and schema documents to your propeosed versions and ran this code:
```java
GafferPopVertex sourceVertex = new GafferPopVertex("entity", "id_123", graph);
sourceVertex.property("type", "first_type");
sourceVertex.property("visibility", "Public");
sourceVertex.property("description", "This should work.");
graph.addVertex(sourceVertex);

GafferPopVertex sinkVertex = new GafferPopVertex("entity", "id_999", graph);
sinkVertex.property("type", "second_type");
sinkVertex.property("visibility", "Public");
sinkVertex.property("description", "But it isn't for some reason.");
graph.addVertex(sinkVertex);

GafferPopEdge edge = new GafferPopEdge("knows", sourceVertex, sinkVertex, graph);
edge.property("weight", (double)0.5);
graph.addEdge(edge);
```

Now... all vertex and edge properties go in just fine.  But if I re-run that same method all properties are removed by the Aggregator on the table.

I have tried the aggregators for Exists, IsTrue, IsFalse, Sum, and Max.  All behave the same way.

Unfortunately my cluster is currently running at JDK 1.7.  I cannot update it to 1.8 this week so I will have to get back to you on the changes when I can run at 1.8.  I really appreciate you help and will let you know soon about the update to 0.6.1!!!

**Comment by p013570** [comment]
OK that seems very strange. I've created a branch in gaffer-experimental containing your schema and sample code. I wrote a quite test that adds your vertices and edge twice then does a query and the data comes back aggregated as expected. Here it is: https://github.com/gchq/gaffer-experimental/blob/gh-739-aggregation/tinkerpop/src/test/java/gaffer/gafferpop/CustomGafferPopGraphTest.java.

This is running on the old version of Gaffer, which I believe is the same version you are using. I can't think what else it might be. Perhaps you have some configuration issue with your cluster.

**Comment by p013570** [comment]
OK, so I think we have got to the bottom of your issue. It is likely to be related to gh-757, where the schema wasn't being validated correctly. If you want aggregation, then you must provide an aggregator for each property type in your schema. If you don't then the schema is invalid. Previously the schema was not validated correctly and missed aggregators meant at query time the properties would disappear - as you discovered. I will close this bug as it will be fixed as part of issue gh-757.

**Comment by pg99bassist** [comment]
I finally got back to this and yes... that is exactly what I was thinking.  I was just messing around with the current build, modified some of the schema and it magically was working.  I really, really appreciate you taking a look into this.  I'll owe you a pint!
