### ISSUE TITLE
Add UserFactory to rest-api project

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#742]
Add a UserFactory to mirror the GraphFactory object and its behaviour. This will give developers an easy hook into which User creation can be controlled.

**Comment by p013570** [comment]
Merged into develop

**Comment by p013570** [comment]
## Migration Steps

The default graph factory class has been renamed to:
```
uk.gov.gchq.gaffer.rest.factory.DefaultGraphFactory
```

A new user factory exists with class:
```
uk.gov.gchq.gaffer.rest.factory.UserFactory
```

The default UserFactory to be used in the rest api is:
```
uk.gov.gchq.gaffer.rest.factory.UnknownUserFactory
```
To override this set the rest system property: 
```
gaffer.user.factory.class
```
