### ISSUE TITLE
Change directed field in EdgeSeed to directed, undirected or either

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#752]
In `EdgeSeed` you can specify whether the `Edge` you are looking for is directed or undirected, but you can't say you are looking for any edges between A and B irrespective of whether they're directed or not. The directed field should be changed so that it's either DIRECTED, UNDIRECTED or EITHER.

One of the key design criteria in version 1 of Gaffer was to be able to find all edges between A and B in a single range. The `ClassicKeyPackage` in the Accumulo store stores data in a way that allows a single range to be constructed, but the user is forced to specify multiple `EdgeSeed`s to get all edges between A and B. As part of this change the `ClassicKeyPackage` should be able to construct one range when the EITHER option is selected.

**Comment by p013570** [comment]
To implement the change I basically just changed the directed boolean on EdgeId to be a nullable Boolean. So it is now optional to specify the directed field on an EdgeSeed when doing a query.

**Comment by p013570** [comment]
# Migration Steps
DirectedType.BOTH has been renamed to DirectedType.EITHER
uk.gov.gchq.gaffer.operation.graph.GraphFilters.DirectedType  has been renamed to  uk.gov.gchq.gaffer.data.element.id.DirectedType

IncludeIncomingOutgoingType.BOTH has been renamed to IncludeIncomingOutgoingType.EITHER.

EdgeSeed directed field has been replaced with directedType, which is now of type DirectedType. So it can take DIRECTED, UNDIRECTED or EITHER. By default it will be set to EITHER.

**Comment by t616178** [comment]
Merged into develop.
