### ISSUE TITLE
NPE if table is not set in AccumuloStore

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#756]
This code throws a NullPointerException because the table name has not been set (if a line is added to set the table name on properties it's fine) - it should throw a more useful exception.

     Schema schema = new Schema.Builder()
                .type("int", Integer.class)
                .type("string", String.class)
                .type("boolean", Boolean.class)
                .edge("EDGE", new SchemaEdgeDefinition.Builder()
                        .source("string")
                        .destination("string")
                        .directed("boolean")
                    .build())
                .build();

     AccumuloProperties properties = new AccumuloProperties();
     properties.setStoreClass(SingleUseMockAccumuloStore.class.getName());

     Graph graph = new Graph.Builder()
                .addSchema(schema)
                .storeProperties(properties)
                .build();

**Comment by p013570** [comment]
Merged into develop.
