### ISSUE TITLE
Invalid schema not detected

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#757]
With the schema below, if the same edge is inserted twice, its properties silently disappear (if only one instance of the edge is inserted the properties are present). This schema should not be allowed because aggregation should (currently) be specified for all properties or none, but no error is given.

    Schema schema = new Schema.Builder()
               .type("intnoagg", new TypeDefinition.Builder()
                       .clazz(Integer.class)
                       .build())
               .type("int", new TypeDefinition.Builder()
                       .clazz(Integer.class)
                       .aggregateFunction(new Sum())
                       .build())
               .type("string", new TypeDefinition.Builder()
                       .clazz(String.class)
                       .aggregateFunction(new StringConcat())
                       .build())
               .type("boolean", Boolean.class)
               .edge("EDGE", new SchemaEdgeDefinition.Builder()
                       .source("string")
                       .destination("string")
                       .directed("boolean")
                       .property("p", "intnoagg")
                       .build())
               .entity("ENTITY", new SchemaEntityDefinition.Builder()
                       .vertex("string")
                       .property("p2", "int")
                       .build())
               .build();

**Comment by t616178** [comment]
Merged into develop.
