### ISSUE TITLE
Create and integrate common cache service

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#763]
Currently there are a number of cache-dependent components all around Gaffer, such as the Named Operations and Job Trackers. There is a growing need for a common cache service that would remove repeated caching logic from these components and provide an interface for new cache-reliant features. 

Users may want to use a different cache implementation depending on their requirements (i.e. JCS, Hazelcast, Ehcache etc). Therefore the gaffer cache service hides the implementation behind an interface and loads the exact service at runtime using a system variable. This provides a clean interface for all components to use, whilst providing options in terms of specific implementation.

To start with the cache service will provide 3 implementations: JCS, Hazelcast and a basic HashMap. This can be expanded if required.

**Comment by gaffer01** [comment]
Can you add a description of what this common cache service would do?

**Comment by p013570** [comment]
The above comment has been updated with a description.

**Comment by p013570** [comment]
# Migration steps
There is now a single shared cache for Gaffer stores. This replaces the separate caches that were previously used by Named Operations and the Job Tracker. See the Cache [README](https://github.com/gchq/Gaffer/blob/master/core/cache/README.md).

If you were previously using the Named Operations and the Job Tracker then there will be a few changes you will need to make:

Replace:

```xml
<dependency>
    <groupId>uk.gov.gchq.gaffer</groupId>
    <artifactId>job-tracker-jcs</artifactId>
    <version>gaffer.version</version>
</dependency>

<dependency>
  <groupId>uk.gov.gchq.gaffer</groupId>
  <artifactId>named-operations-library</artifactId>
  <version>${gaffer.version}</version>
</dependency>
```

with

```xml
<dependency>
    <groupId>uk.gov.gchq.gaffer</groupId>
    <artifactId>jcs-cache-service</artifactId>
    <version>gaffer.version</version>
</dependency>

 <dependency>
  <groupId>uk.gov.gchq.gaffer</groupId>
  <artifactId>named-operation-library</artifactId>
  <version>${gaffer.version}</version>
</dependency>
```


<br/>

And replace the following properties in you store.properties file:

```properties
gaffer.store.job.tracker.class=uk.gov.gchq.gaffer.jobtracker.JcsJobTracker
gaffer.store.job.tracker.config.path=/path/to/config/file
```

with the new properties:

```properties
gaffer.store.job.tracker.enabled=true

gaffer.cache.service.class=uk.gov.gchq.gaffer.cache.impl.JcsCacheService

# Optionally provide custom cache properties
gaffer.cache.config.file=/path/to/config/file
```

**Comment by p013570** [comment]
Merged into develop.
