### ISSUE TITLE
Wiki JavaDoc points to incorrect page.

### ISSUE THREAD

**Issue by AdamRobertsEF** [gchq/Gaffer#772]
JavaDoc should link to:

http://gchq.github.io/Gaffer/

Not:

http://governmentcommunicationsheadquarters.github.io/Gaffer

Thanks
Adam

**Comment by p013570** [comment]
Hi Adam, 

Thanks for letting us know - I've just updated it.

Many thanks.

**Comment by AdamRobertsEF** [comment]
Thank you :-) 👍
