### ISSUE TITLE
Integration tests fail to spot that the same edge must be output twice if it was added twice and no aggregation is specified

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#775]
This issue arose when writing a new store. If aggregation is not being used (either the store doesn't support it or it is just not being used) then if the same edge is added twice, it should be returned twice from a query. If a store erroneously only returns the edge once, the integration tests don't spot that.

The integration tests should be extended so that they test if no aggregation is being used then the same edge should be returned twice if it was added twice.

Marked as a bug as this means an incorrect store implementation can pass the integration tests.

**Comment by p013570** [comment]
Most of the integration tests currently use the same schema - which has aggregation. We would need to create another integration test class similar to VisibilityIT that uses a different schema with no aggregation. 

A very basic test would be to Call AddElements with an Edge twice, then call GetAllElements and you should get the Edge back twice.

**Comment by p013570** [comment]
Merged into develop.
