### ISSUE TITLE
Create in-memory store backed by a Java Map

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#776]
It would be useful to have an in-memory store. The first version of this will use a standard Java HashMap. It will not scale to large volumes, but it will be very high performance for queries. It should be optimised to support aggregation efficiently.

This has the following use-cases:
- A simple in-memory cache of `Element`s that have been retrieved from a large store.
- The creation of examples of how operations work, how views work, etc, without the need to use the `AccumuloStore`.
- The aggregation of data within a streaming process, i.e. ingest data into an in-memory map aggregating properties if the same element is seen multiple times followed by periodic export of the whole graph into a larger (e.g. Accumulo-based) store.

Future versions of this could use libraries that allow off-heap storage to allow scalability to larger volumes, but the initial version will use a Java HashMap.

**Comment by AdamRobertsEF** [comment]
This functionality is something that I was planning to implement using Redis, which would be a good match. Redis supports loading of Redis HashMaps into Java HashMaps, and setting Java HashMaps into Redis HashMaps.

I believe using the Storage class would be a good starting point.

**Comment by gaffer01** [comment]
@AdamRobertsEF Apologies, we've only just noticed your comment. Implementing an in-memory store using Redis would be very interesting and useful. This issue is for a simple in-memory store that will not scale. Redis would obviously allow greater scalability. If you do implement a Redis store, please consider contributing it here.

**Comment by gaffer01** [comment]
Closing this issue as it has been merged into develop. There are other open issues to improve the current `MapStore`, and alternative in-memory stores could be developed, e.g. using Redis - new issues should be created for these.
