### ISSUE TITLE
Move the functions (koryphe) library out of Gaffer to a dedicated repository

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#779]
The functions library should be moved out of Gaffer and into it's own repository so that it can easily be shared between projects.

**Comment by gaffer01** [comment]
I think it's fine to have a dependency on an external functions library, but Gaffer should own the core interfaces that define the functions it can do (aggregate, filter elements, transform elements, etc) and these should not depend on external functions libraries. It must be possible to plug-in other function libraries later - we may want to write higher performance libraries later.

**Comment by p013570** [comment]
@gaffer01 - I agree. I have raised a separate issue to refactor the code to remove the hard dependency on Koryphe functions: gh- 820.

**Comment by p013570** [comment]
As part of this issue we should also move the functions in core-library to the koryphe library.

**Comment by p013570** [comment]
I've created a [koryphe](https://github.com/gchq/koryphe) repository ready.

**Comment by p013570** [comment]
The code has been added to the develop branch in the koryphe repo. Once koryphe version 0.1.0 has been released we can remove the koryphe code out of the Gaffer repository.

**Comment by p013570** [comment]
# Migration steps

A large number of functions, aggregators and transforms have now been moved into the Koryphe library. This has meant we have had to rename the packages for these functions.
e.g
```
uk.gov.gchq.gaffer.function.filter.IsMoreThan
-> uk.gov.gchq.koryphe.impl.predicate.IsMoreThan
```

We have also renamed packages so they match the Java 8 function interfaces:
```
filter -> predicate
aggregate -> binaryoperator
transform -> function
```

e.g
```
uk.gov.gchq.gaffer.sketches.datasketches.theta.function.aggregator.UnionAggregator
-> uk.gov.gchq.gaffer.sketches.datasketches.theta.binaryoperator.UnionAggregator
```

List the predicate [examples](https://github.com/gchq/Gaffer/wiki/Examples) for further details.

**Comment by p013570** [comment]
Merge into develop.
