### ISSUE TITLE
NamedOperation views don't allow global filters to be used

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#783]
Currently any global filters on a named operation are not expanded so the filters are not added to each element group - i.e. the global filters are not applied.

The Graph class will normally handle this for all operation views. However, the named operation contains a nested operation chain that is not passed through the setup in the Graph class. This means the named operation handler has to call view.expandGlobalDefinitions() on the views in the named operation chain itself.

**Comment by t616178** [comment]
Merged into develop
