### ISSUE TITLE
Create GraphX graphs as part of an OperationChain

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#792]
It would be useful to be able to create GraphX graphs from the results of a "GetElements" query in order to use the Spark GraphX API to perform analysis on Gaffer graphs.

**Comment by gaffer01** [comment]
This would be useful. I think most of the value will come from extracting data in parallel (via operations like `GetRDDOfAllElements`) and creating GraphX graphs from that.

**Comment by t616178** [comment]
For now, this type of functionality will be provided by gh-1436. This issue should be reopened if there is a requirement for functionality which cannot be provided by the GraphFrames library and requires GraphX.
