### ISSUE TITLE
Create chain optimiser for the MapStore

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#802]
The `MapStore` has a handler for the `CountAllElementsDefaultView` operation that allows the calculation of the number of elements in the store without needing to iterate through every element. An operation chain optimiser should be written that converts a `GetAllElements` operation (with the view set to everything, and the options set to include everything) followed by a `Count` operation to a single  `CountAllElementsDefaultView` operation. This may best be done after version 0.7 when the number of options on the operations have been reduced.

**Comment by d47853** [comment]
Merged into develop
