### ISSUE TITLE
Improve Kryo serialisation in spark-library

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#803]
Currently only `Entity`, `Edge` and `Properties` are registered in the `Registrator` class in the spark library. We should register other classes such as `FreqMap`, `HyperLogLogPlus` and the other sketches. We should provide implementations of the serialisers for classes that may be difficult/expensive to serialise (e.g. `HyperLogLogPlus`).

We should also investigate registering other classes such as `Schema`, `Graph`, `Store` and `StoreProperties`. In order to serialise `Schema`, we need to use the de.javakaffee:kryo-serialisers project, and call `UnmodifiableCollectionsSerializer.registerSerializers` in the `registerClasses` method.

**Comment by gaffer01** [comment]
Updating this issue to just do `FreqMap` and `HyperLogLogPlus`. Using Kryo serialisation for some of the sketches from the DataSketches library needs more work, as classes like `DoublesUnion` are abstract and the actual concrete implementations of them are not publicly accessible from outside the project. A separate issue will be raised for this.

A separate issue will also be raised for Kryo serialisation of `Schema` and other properties.

**Comment by p013570** [comment]
Merged into develop.
