### ISSUE TITLE
UI fails to wrap number strings vertices in quotes

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#817]
When using the UI, queries that return vertices that are number strings (i.e. "1") are not quoted so it is added to the UI as an integer (i.e. 1). This means if you try to use this integer vertex in a second query an error will be thrown.

String results in the UI should be wrapped in quotes.

An attempt to fix this was done in issue gh-724 but the fix doesn't properly check result vertices.

**Comment by t616178** [comment]
Merged into develop.
