### ISSUE TITLE
Remove BiFunction from Koryphe

### ISSUE THREAD

**Issue by d21211122** [gchq/Gaffer#819]
Koryphe currently supports both BinaryOperator and BiFunction, but BiFunction is only used to implement aggregation where the output type is different to the input type. These examples would be clearer if implemented by applying a function to either the input or output of a BinaryOperator.

Any other uses of BiFunction should be implemented as a Function that accepts a Tuple input type.

**Comment by p013570** [comment]
This has been move to the koryphe repository.
