### ISSUE TITLE
Investigate improving Kryo serialisation for classes from DataSketches

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#837]
It should be possible to register the classes from the DataSketches library that we have serialisers for in the Kryo Registrator. Their existing serialisers should just be wrapped in Kryo serialisers. This should improve the performance of Spark jobs which use them. This may not be simple though because some of the classes, e.g. `DoublesUnion`, are abstract which seems to cause Kryo problems in finding the correct serialiser. The classes that implement the abstract classes (e.g. `HeapDoublesUnion`) are not visible outside the DataSketches library so serialisers for them cannot be provided.

**Comment by p013570** [comment]
Merged into develop.
