### ISSUE TITLE
Provide example of filtering in views based on the source or destination

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#838]
Provide an example of how filters in views can take into account the values of the source or destination, e.g. the following view specifies that the destination should be "A" (of course if there is only a single seed "B" then it would be more efficient to just query for the edge A-B - it would be more interesting to filter by destination matching a regular expression - the example could show this use-case as well):

    View view = new View.Builder().edge("EDGE",
                    new ViewElementDefinition.Builder().preAggregationFilter(
                        new ElementFilter.Builder()
                                .select(IdentifierType.DESTINATION.name())
                                .execute(
                                        new IsEqual("A"))
                                .build())
                        .build())
                    .build();

An example should also be provided of the affects of these filters for undirected edges. For example, if undirected edge B-A is inserted into a graph, and B is queried for, with a filter saying that the destination should be A or match A* then no results will be returned, because B is the destination (as they are automatically reordered so that A is the source). When executing such queries on undirected edges, the user should specify that either the source or the destination is A (it will be interesting to see how easy this is to specify in the current select, execute model of filters).

**Comment by p013570** [comment]
Merged into develop.
