### ISSUE TITLE
Create TimestampSet property

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#839]
It is common to want to store a set of timestamps, to some accuracy, on an `Entity` or `Edge`. For example, store all the times the edge was observed, to minute-level accuracy.

A class should be created that is constructed with a particular accuracy level, e.g. minute or hour, and allows timestamps to be added. Internally, these are truncated to the requested accuracy (e.g. the seconds and milliseconds are removed if minute-level accuracy has been requested), converted to an int (e.g. number of minutes since the epoch), and stored in a `RoaringBitMap`. The class can be queried to produce a list of all the timestamps that have been added.

An aggregators and a serialiser for the class should also be written. These can basically wrap the existing aggregator and serialiser for `RoaringBitMap`.

**Comment by p013570** [comment]
Merged into develop.
