### ISSUE TITLE
Aggregation Example is generating invalid end date

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#842]
The end date should be 1 milli second less than midnight.

**Comment by gaffer01** [comment]
Can you explain this in more detail? Is it one of the examples built-in to Gaffer that is generating the invalid end date or a particular example you've found on your own data set?

**Comment by GCHQDeveloper404** [comment]
One of the examples built-in to Gaffer.

**Comment by p013570** [comment]
Merged into develop.
