### ISSUE TITLE
Create operations for standard functions like max

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#849]
There is an operation called `Count` that simply counts the number of items in a provided iterable. This was introduced because the `MapStore` can optimise an operation chain that retrieves all elements (with the standard `View`) and then counts the number of them, into a single operation that is implemented very efficiently (see issue #802).

We should provide other operations like max, min and sum that can be used on properties on elements returned from queries. For example a query may return an iterable of elements, and the user may want to return only the element with the largest value of a "count" long property.

Users of the Java API may find it easiest to perform these operations by converting the iterable of results into a Java Stream, and then call standard Java functions. However, these cannot be used over the REST API. The advantage of wrapping standard functions in operations is that they can then be put into operation chains and used via REST.

**Comment by p013570** [comment]
I agree. Although it is shame we have to duplicate the Java API stream functions, there should be very little code required.

For example to implement a Max operation the following would be required:

Max operation class that takes a Comparator<T>  and implements:
        Operation,
        InputOutput<Iterable<? extends T>, T>,
        MultiInput<T>

MaxHandler the operation handler for the Max operation. This could take the Iterable input convert to a stream and call max with the provided comparator.

MaxExample and example of the Max operation for the wiki documentation.


The issue with this Max operation is ensuring users can provide a comparator over the rest api. Which may result in another library of comparators being required. I can envisage a comparator such as given 2 Elements, extract the "count" properties as Longs and compare them. This could apply to any property that is comparable.

**Comment by p013570** [comment]
Operations Min and Max have been added as part of this issue. If Sum or any other operations are required then please raise separate issues.

**Comment by p013570** [comment]
Merged into develop.
