### ISSUE TITLE
Add method to rest api to execute a single operation

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#856]
If a user wants to run a non-core operation such as NamedOperation via the rest api, they currently have to wrap it in an operation chain and executing via the execute(OperationChain) method.

It would be nice to have an method execute(Operation) that users could use.

This will mean the Operation class will need to be annotated with:

```java
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "class")
```

to tell Jackson how to deserialise the operation json.

After this issue is done we will need to add the same method to the python shell in gaffer-tools.

**Comment by GCHQDeveloper404** [comment]
# Migration steps
All Operations defined in Json will require the class to be defined.

example: ` "class": "uk.gov.gchq.gaffer.operation.impl.get.GetElements"`

**Comment by p013570** [comment]
Merged into develop.
