### ISSUE TITLE
Add DEBUG system property to include stack trace in REST error messages

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#860]
Currently, the errors provided by the REST API include a representation of the full stack trace in the body of the error message. Often this message is not very useful to the end user - the default state should be that the stack trace is not included, but there should be an option to include it if required.

This could be implemented using a JsonFilter - either by creating a new filter which implements the Jackson PropertyFilter interface, or by making use of the field exclusion filter which is provided as part of the Gaffer JSONSerialiser class.

**Comment by p013570** [comment]
Please can we also make sure the stack trace is always logged.

**Comment by p013570** [comment]
Merged into develop.
