### ISSUE TITLE
SampleDataForSplitPointsJobFactory should get compression options from the operation

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#866]
`SampleDataForSplitPointsJobFactory` is hard-coded to use gzip and block compression in the `SequenceFile`s that will be output by the job. There are currently no unit tests for this job.

When writing a unit test for some code in `gaffer-tools` that need to run this sample data job, the error message "SequenceFile doesn't work with GzipCodec without native-hadoop code!" is returned.

The operation should allow the type of compression to be specified. Unit tests can then turn compression off to avoid this error.

**Comment by t616178** [comment]
Closing, as this has been fixed upstream.
