### ISSUE TITLE
Allow named operations to be run with custom parameters

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#868]
Currently when you run a NamedOperation you can set a custom view. This is applied to all operations in the named operation chain that don't have a predefined view. This doesn't work very well and does provide enough flexibility for users to configure parts of the named operation such as filtering values.

We should remove the ability provide a view in the NamedOperation class - i.e remove "implements OperationView".

Instead we need to add allow users to do something like:

```java
new NamedOperation.Builder()
    .name("1-hop")
    .input(new EntitySeed("vertex1"))
    .parameter("maxCount", 10)
    .parameter("minStartDate", "01/01/2017")
    .build();
```

The "1-hop" named operation could have an operation defined similar to:
```
new GetElements.Builder()
                .view("redEdge", new ViewElementDefinition.Builder()
                        .preAggregationFilter(new ElementFilter.Builder()
                                .select("count")
                                .execute(new IsLessThan(${maxCount}))
                                .select("startDate")
                                .execute(new IsMoreThan(${minStartDate}))
                                .build())
                        .build()
                .build();
```

So named operations need to have custom parameters that will be resolved when it is executed. The parameters should also be able to have default values and a description.

**Comment by t616178** [comment]
Merged into develop
