### ISSUE TITLE
Unnecessary line in AddElementsFromHdfsIT

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#879]
The test `AddElementsFromHdfsIT` in the Accumulo store contains the following at line 212:

    store.updateConfiguration(createLocalConf(), new View(), new User());

This line is:
- Unnecessary - the test passes without it. 
- Pointless - it updates the configuration created by `createLocalConf()` but that configuration is not used again.
- Misleading - it looks like the `updateConfiguration` method is used to cause operations on the graph like `AddElementsFromHdfs` to use a particular configuration - that's not true. In this test a local MapReduce configuration is somehow automatically created and used.

**Comment by morrme** [comment]
I can remove this line and send a PR if nobody has done it yet.

**Comment by p013570** [comment]
@morrme that would be great, thanks.

Here are our notes on [pull requests](https://github.com/gchq/Gaffer/wiki/Ways-of-Working#pull-requests).

**Comment by morrme** [comment]
@p013570 Is there a link to that contributor acceptance template? It is not rendering correctly for me (I use web based email).

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
@morrme sorry I've only just seen your comment above.
