### ISSUE TITLE
Add description field to element groups in the schema

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#88]
This will allow users to give a brief overview of the element group.

**Comment by p013570** [comment]
This should be done after gh-19.

**Comment by p013570** [comment]
Add a description field to SchemaElementDefinition and TypeDefinition. 
Add the option to serialise a Schema to json and skip the description field, such as toCompactJson(). This should be used when possible - i.e in the Accumulo store when it creates the table iterators.

**Comment by t616178** [comment]
Merged into develop.
