### ISSUE TITLE
SampleDataForSplitPoints and SplitTable don't work together

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#880]
In the `AccumuloStore`, the `SampleDataForSplitPointsHandler` uses `SampleDataAndCreateSplitsFileTool` to sample some split points and write them to file. They are written to file base64 encoded.

The `SplitTableHandler` uses `SplitTableTool` to read the split points in from file and apply them to the table. The base64 encoding is not undone when they are read from file.

This explains why only one tablet server receives data even if split points have been applied.

This should be fixed and a unit test created.

**Comment by p013570** [comment]
Merged into develop.
