### ISSUE TITLE
Speed up the travis build

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#882]
With the addition of more unit and integration tests and new store implementations, currently Travis takes approximately 35 minutes to build the project. As this will increase over time (as new features are added), any efforts to reduce the running time of the tests (for example, by using the build matrix to run the unit tests and integration tests separately or by running tests for each store in parallel) would be of benefit.

**Comment by p013570** [comment]
I've split out the unit tests, integration tests and code analysis into separate builds so they can be run in parallel on different travis VMs. We should monitor the builds and check whether we need to split them out further.

**Comment by p013570** [comment]
I've split out the code base into separate sections so they can be run in parallel on different travis VMs. We should monitor the builds and check whether we need to split them out further. Currently:

- code analysis of whole code base
- test everything except hbase and accumulo
- test accumulo
- test hbase

**Comment by p013570** [comment]
Closing this for now as the build seems to be ok.
