### ISSUE TITLE
Create general purpose aggregation operations

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#883]
We should provide some default aggregation operations that can be applied to properties on elements returned by queries. These would be executed client side and so would best suited to stores which are hosted on a single node (e.g. in-memory stores like the MapStore). For distributed store types this would be inefficient, so an ideal implementation of these default aggregation operations would delegate to the underlying store if necessary.

**Comment by p013570** [comment]
This has been done in #1341
