### ISSUE TITLE
Reduce the number of times byte arrays are copied

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#885]
The Serialisation class serialises objects into byte arrays. In accumulo and hbase these byte arrays are then copied into another byte[] and then store in an accumulo/hbase row/column/value. 

Perhaps we could add a serialise method that takes a byte[] or some byte writer and can write directly to that byte[]/writer:
```java
void serialise(Object, byte[] result)
```
or
```java
void serialise(Object, ByteWriter writer)
```

**Comment by GCHQDeveloper404** [comment]
Note: Update the logging when catching byte stream exceptions.

**Comment by GCHQDeveloper404** [comment]
gh-855 (commit 668a26a) provides a 6.5% increase in speed against develop (commit 99c0e2d) & master (commit 9a3117a)

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
Merged into develop.
