### ISSUE TITLE
Change Serialisation api to allow objects to be serialised into different types

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#886]
The accumulo and hbase stores require objects to be serialised into bytes. However, other stores may require objects to be serialised into Strings or some other type.

We should rename Serialisation to ByteArraySerialiser and create a parent interface Serialiser:

```java
public interface Serialiser<I, O> {
    O serialise(I obj);

    I deserialise(O serialisedObj);
}
```

**Comment by GCHQDeveloper404** [comment]
Improve the casting to ToBytesSerialiser

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
# Migration Steps
The method deserialiseEmptyBytes in the Serialisation interface has been renamed to deserialiseEmpty.
