### ISSUE TITLE
Ensure any operations that have a closable input are closed if an exception is thrown

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#889]
In the Graph class we should wrap the execution of an OperationChain in a try-catch and if an exception is caught we should close all operation inputs.

**Comment by t616178** [comment]
Is there any benefit to using try with resources blocks to automatically close the inputs if an exception is thrown?

This may negate the need for any additional try blocks inside the finally blocks?

**Comment by p013570** [comment]
We can't use the try with resources for a lot of the cases as we only want to close the input if there is an exception thrown. I think the try with resources would always close the input at the end of the try statement. We need the input to stay open until the output of the operation chain has been consumed by the user, either via REST or java.

**Comment by t616178** [comment]
Merged into develop.
