### ISSUE TITLE
Renaming of current serialisers

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#898]
All current serialisers could be renamed from e.g `StringSerialiser` to `StringToBytesSerialiser` following gh-886. To remove ambiguity from other future types.

We could deprecate the old classes to be empty extensions of the new class names.

**Comment by GCHQDeveloper404** [comment]
# Migration
Json schemas with serialiser will require renaming to the new formats

**Comment by m55624** [comment]
Serialisers added in #988 have been named to match this ticket.

**Comment by p013570** [comment]
We should wait until we next plan to do a major release before we make this change, due to the migration required.

**Comment by p013570** [comment]
Rather than doing this, bytes will be the default output type. All serialisers that serialise into anything other than bytes should have a class named accordingly. So for serialisers that output bytes we don't need to put ToBytes in the class name.
