### ISSUE TITLE
Validate operation chain input/output types

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#930]
If operation chains are built using the OperationChain builder then users will get compile time errors if the order of operations in their chain is invalid. The output of an operation must be compatible with the import of the next operation.

If users create operation chains via rest or python then the operation chain input/output types are not validated. User's will only notice a problem at runtime if the chain fails to execute and a class cast exception is thrown.

Prior to executing the operation chain the store already does some validation of the chain. This validation should be split into a separate class and updated to include the input/output type validation.

In addition it would be really helpful to have a rest api method 'getNextOperations' that takes an operation class and returns all the operations that would be valid to come next.

**Comment by t616178** [comment]
Merged into develop
