### ISSUE TITLE
upgrade jcs to version 2.0

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#943]
There is an issue with jcs 1.3 where, when using a distributed tcp cache, the getGroupKeys method causes an exception to be thrown. This is fixed in a later version.

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
# Migration steps

You will need to update your JCS cache.ccf config files according to: http://commons.apache.org/proper/commons-jcs/UpgradingFrom13.html

Please note there is a bug in JCS version 2.0 so if you plan on using JCS age off then it won't currently work until we update to JCS version 2.1.
