### ISSUE TITLE
User Guide error?

### ISSUE THREAD

**Issue by jg895512** [gchq/Gaffer#952]
This page: https://github.com/gchq/Gaffer/wiki/User-Guide has two POM dependencies for getting started:

<dependency>
    <groupId>uk.gov.gchq.gaffer.core</groupId>
    <artifactId>graph</artifactId>
    <version>[gaffer.version]</version>
</dependency>
<dependency>
    <groupId>uk.gov.gchq.gaffer</groupId>
    <artifactId>accumulo-store</artifactId>
    <version>[gaffer.version]</version>
</dependency>

When I put it in my POM (with version 0.7.3) and started building I got this error:
"The POM for uk.gov.gchq.gaffer.core:graph:jar:0.7.3 is missing, no dependency information available"

Looking around at the project, I dropped the ".core" in the first dependency group, changing it to: "uk.gov.gchq.gaffer", rebuilt and it completed build and has been working (so far).  

So, I think this is just a small documentation update...

Thanks,
Jeff

**Comment by jg895512** [comment]
Same issue with dependency on this page as well (I think): https://github.com/gchq/Gaffer

**Comment by p013570** [comment]
Ah, good spot - yes the groupId should be "uk.gov.gchq.gaffer".

Thanks for pointing them out.

**Comment by p013570** [comment]
Merged into the develop branch and will be released as part of version 0.7.4.
