### ISSUE TITLE
NullPointerException thrown if schema is missing

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#974]
This code throws a `NullPointerException` if the directory that the schemas are supposed to be in doesn't exist - a more helpful exception should be thrown:

    final Graph graph = new Graph.Builder()
                .addSchemas(StreamUtil.openStreams(MyClass.class, "directory_that_doesnt_exist"))
                .storeProperties(StreamUtil.openStream(MyClass.class, "mockaccumulostore.properties"))
                .build();

**Comment by p013570** [comment]
Merged into develop.
