### ISSUE TITLE
The Raw Serialisers do not preserve object ordering

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#988]
The Raw Serialisers (RawLongSerialiser, RawDateSerialiser, etc.) do not always preserve object ordering.

For example if you serialise the following longs you, they should be serialised into bytes that maintains the same ordering.

1. 1496709602656   ->  [96, 29, -40, 122, 92, 1, 0, 0]
2. 1496710980959   ->  [95, 37, -19, 122, 92, 1, 0, 0]
3. 1496710980960   ->  [96, 37, -19, 122, 92, 1, 0, 0]
4. 1496710980961   ->  [97, 37, -19, 122, 92, 1, 0, 0]

So the values of the serialised bytes ends up reordering the values into:

2. 1496710980959   ->  [95, 37, -19, 122, 92, 1, 0, 0]
1. 1496709602656   ->  [96, 29, -40, 122, 92, 1, 0, 0]
3. 1496710980960   ->  [96, 37, -19, 122, 92, 1, 0, 0]
4. 1496710980961   ->  [97, 37, -19, 122, 92, 1, 0, 0]

The ordering of the serialisers is important when using an ordered database/store, like Accumulo or HBase. If using either of these Gaffer Stores, you should use an serialiser that preserves object ordering for your vertices. If your vertices are serialised on an ordered fashion then you are able to do [range scans](https://github.com/gchq/Gaffer/wiki/Accumulo-specific-operation-examples#getelementsinranges-example).

It is advised that Properties included in the groupBy should also be serialised with an ordered serialiser to help maintain true ordering of the Accumulo/HBase row keys. However, this is not essential, but you will not be able to carry out range scans over other columns in the row key (column qualifier/visibility).

To fix this bug, we should deprecate all of the Raw Serialisers and write new serialisers based on:
https://github.com/apache/accumulo/blob/f81a8ec7410e789d11941351d5899b8894c6a322/core/src/main/java/org/apache/accumulo/core/client/lexicoder/ULongLexicoder.java.

We will need to update the Serialisation Factories, removing the deprecated serialisers and adding the new ones. This will break the serialisation of all the serialised data that has been serialised with the Raw Serialisers and have not explicitly defined them in their schema. This would occur due to new serialisation factory selecting the new serialiser, which will not be compatible with the existing serialised bytes. We must inform users that if they have an existing table in accumulo or hbase that they need to manually define the Raw Serialisers they are using in their schema.

**Comment by t616178** [comment]
Merged into develop

**Comment by p013570** [comment]
# Migration Steps
If you have an existing table in accumulo or hbase and your schema does not have serialisers defined for all of your properties and vertices then you will need to add them in manually rather than relying on Gaffer to select them for you. This is because there have been changes to which serialisers it would automatically select for you.

The Serialisation Factories were updated to replace the deprecated raw serialisers with the new ordered serialisers. This will break the serialisation of all the serialised data that has been serialised with the Raw Serialisers and have not explicitly defined them in their schema. This would occur due to new serialisation factory selecting the new serialiser, which will not be compatible with the existing serialised bytes.
