### ISSUE TITLE
Create Generic Map/Set Serialisers

### ISSUE THREAD

**Issue by james010101101** [gchq/Gaffer#994]
We should be able to serialise maps/sets by specifying the serialisers for the objects they hold, rather than creating new Map/Set serialiser every time we counter a new type/type combination.

**Comment by james010101101** [comment]
# Migration steps

If you had for example a storeType of prop.string previously you may have specified your serialiser like so :
{
    "prop.string": {
        "serialiserClass":  "uk.gov.gchq.gaffer.serialisation.implementation.StringSerialiser"
        "aggregateFunction": {
            "class": "uk.gov.gchq.gaffer.function.ExampleAggregateFunction"
        }
    }
}

Now you should specify the same like so:

{
    "prop.string": {
        "serialiser": {
            "class" : "uk.gov.gchq.gaffer.serialisation.implementation.StringSerialiser"
        },
        "aggregateFunction": {
            "class": "uk.gov.gchq.gaffer.function.ExampleAggregateFunction"
        }
    } 
}

**Comment by p013570** [comment]
Merged into develop.
