### ISSUE TITLE
The Schema should have separate methods for getting Ingest and Query Aggregator

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#996]
Currently there is only one method on the schema, getAggregator(). This returns a full aggregator to aggregate all properties in 2 elements. Depending on the type of aggregation (Ingest or Query) we may want to keep some properties constant - the groupBy properties. 

Therefore we should create getIngestAggregator and getQueryAggregator methods.

**Comment by t616178** [comment]
Merged into develop.
